### ISSUE TITLE
.NGENPDB vs. .NENPDB typo?

### ISSUE THREAD

**Issue by kkostrzewa** [microsoft/perfview#1019]
The comment references .NGENPDB and the code references .NENPDB (without the G)
Is this a typo?
https://github.com/microsoft/perfview/blob/master/src/PerfView/PerfViewData.cs#L159

**Comment by brianrob** [comment]
@kkostrzewa, yes that is a typo - it should be .NGENPDB.  Thanks for pointing this out.  Do you want to submit a PR for this?

**Comment by brianrob** [comment]
Fixed via #1020.
