### ISSUE TITLE
Enable the GCStartStopEvents CTF Tests

### ISSUE THREAD

**Issue by vancem** [microsoft/perfview#102]
I have disabled the tests GCStartStopEvents  in CtfTraceTests.cs because it asserts in the method

GetTraceEvent(CtfEvent evt)

At this assert.   

Debug.Assert(evt.Name.StartsWith("lttng") || _eventMapping.ContainsKey(evt.Name), evt.Name);

If you remove the 'Assert.Inconclusive' and run the test on a debug build it should repo.

Vance

**Comment by sharwell** [comment]
:memo: The file **auto-20151103-132930.lttng.zip** appears to be missing from the repository. When I switched the test to using the file I did find, **auto-20151103-132930.trace.zip**, it was passing.

**Comment by brianrob** [comment]
Fixed via #1117.
