### ISSUE TITLE
SpeedScopeStackSource fails to escape new-lines in json

### ISSUE THREAD

**Issue by josalem** [microsoft/perfview#1057]
Original issue in dotnet/diagnostics:
> Steps to reproduce:
> 
> ```cs
>                     using var httpClient = new HttpClient();
>                     string response = await httpClient.GetStringAsync("http://redhatloves.net/");
> ```
> 
> Log with `--providers Microsoft-System-Net-Http --format speedscope`
> 
> The resulting json file is invalid because newlines are not escaped in json strings.
> 
> For example:
> 
> ```js
> { "name": "EventData: parameters=(Method: GET, RequestUri: 'http://redhatloves.net/', Version: 1.1, Content: <null>, Headers:
> {
> })" }
> ```
_Original comment by: @tmds_

dotnet/diagnostics#623

Should just be a matter of adding encoding logic to the JSON writing logic.  Could use [the new System.Text.Json API](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodings.web.javascriptencoder?view=netcore-3.0) which is available as a nuget package to older versions of the runtime.

CC - @adamsitnik

**Comment by adamsitnik** [comment]
It was possible to fix the problem in `dotnet trace`: https://github.com/dotnet/diagnostics/pull/661

IMHO this issue can be closed. Or I can add a very defensive condition to `SpeedScopeStackSourceWriter` (I would prefer not to do it)

**Comment by josalem** [comment]
I think the fix is dotnet/diagnostics is sufficient.  Thanks for finding the issue 😃
