### ISSUE TITLE
TraceEvent library used in monitoring tool causes memory leak.

### ISSUE THREAD

**Issue by artemsv** [microsoft/perfview#1081]
Hello, perfview developers!

I am trying to build a monitoring tool that just starts a real time ETW sessions and send information to some location. The issue is that after several days of working the process eats gigabytes of memory. "Leaked" objects are 

![image](https://user-images.githubusercontent.com/1922262/71701172-0435a880-2dd9-11ea-9adb-0ebc57814be2.png)

Well, it seems that is not a real memory leak and it is by design by whether it means that it is not designed for such a case in which I want to use it?  It is working in this way:

```c#
using (var session = new TraceEventSession("MyRealTimeSession"))
{
    session.EnableKernelProvider(KernelTraceEventParser.Keywords.Process);

    using (traceLogSource = TraceLog.CreateFromTraceEventSession(session))
    {
        traceLogSource.Kernel.ProcessStart += Kernel_ProcessStart;
        traceLogSource.Kernel.ProcessStop += Kernel_ProcessStop;

        traceLogSource.Process();
    }
}
```

There are the following fields in TraceLog class that grow only:
```C#

private TraceProcesses processes;
private TraceThreads threads;

```

So is it even possible to build such a tool that will no suffer from this type of issue? Or TraceEvent lib is intended to use in short term scenarios only ?

**Comment by mjsabby** [comment]
Maybe there is some API change we could make it to improve this, but do you need to use `TraceLog`?

A real time monitoring tool would be more efficient if it did only what it needed to do, rather than using `TraceLog` which does extensive buffering to provide a richer analysis.

I would use `ETWTraceEventSource`.

**Comment by artemsv** [comment]
Thank you, @mjsabby , for the answer. Going to test your proposal and close the issue if it works.

**Comment by artemsv** [comment]
ETWTraceEventSource works well, closing the issue
