### ISSUE TITLE
How to open a PerfCollect trace file using TraceEvent

### ISSUE THREAD

**Issue by adamsitnik** [microsoft/perfview#1103]
I want to extend the `dotnet trace` tool with the possibility to convert trace files captured with PerfCollect to Speedscope file format. Just to be able to run perf investigation on Linux machine without copying the trace file to Windows and converting it to SpeedScope using PerfView.

I was hoping that it's going to be a matter of replacing [this](https://github.com/dotnet/diagnostics/blob/42f505ef918f7aabccad7de4e4e7aab7318f5de1/src/Tools/dotnet-trace/TraceFileFormatConverter.cs#L66) line of code with:

```cs
// before
var etlxFilePath = TraceLog.CreateFromEventPipeDataFile(fileToConvert, null, new TraceLogOptions() { ContinueOnError = continueOnError } );
// after
var etlxFilePath =
    fileToConvert.EndsWith(".trace.zip")
        ? TraceLog.CreateFromLttngTextDataFile(fileToConvert, null, new TraceLogOptions() { ContinueOnError = continueOnError })
        : TraceLog.CreateFromEventPipeDataFile(fileToConvert, null, new TraceLogOptions() { ContinueOnError = continueOnError });
```

However, for all the trace files I have I am getting following exception:

```log
System.IO.EndOfStreamException: No CTF Information found in ZIP file.
   at Microsoft.Diagnostics.Tracing.CtfTraceEventSource..ctor(String fileName)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromLttngTextDataFile(String filePath, String etlxFilePath, TraceLogOptions options)
```

The exception is thrown here:

https://github.com/microsoft/perfview/blob/2fb635bcde289b2995570001334c08934371003c/src/TraceEvent/Ctf/CtfTraceEventSource.cs#L83-L86

Since PerfView was able to open this trace file I've debugged it and it turned out that the exception is handled by the `GetTraceLog` method:

https://github.com/microsoft/perfview/blob/b2f8e0ebd0434fac7e40960dc5521ce121c26a72/src/PerfView/PerfViewData.cs#L8463-L8466

and later [ParallelLinuxPerfScriptStackSource](https://github.com/microsoft/perfview/blob/master/src/PerfView/OtherSources/Linux/LinuxPerfScriptStackSource.cs) is used to create a `StackSource` from the trace file. The problem is that `ParallelLinuxPerfScriptStackSource` is not part of the `TraceEvent` library so I can't use it outside of PerfView.

Have the LTTng trace file format changed and the throwing code should be updated?
Would it be OK to move `ParallelLinuxPerfScriptStackSource` to `TraceEvent` library? (I could send a PR ofc)

/cc @brianrob

**Comment by tmds** [comment]
+1, it would be great if we can do perf analysis for Linux without needing a Windows machine!

**Comment by brianrob** [comment]
@adamsitnik, the trace format hasn't changed for LTTng, but you'll see this error if there aren't any events in the trace file.  This should safely be ignorable.

With respect to ParallelLinuxPerfScriptStackSource, I am OK if you want to move this from PerfView into TraceEvent so that you can do the SpeedScope conversion there.  If it is as simple as moving this class, then please do go ahead.  If it becomes more complicated, let me know and we can discuss options.

**Comment by adamsitnik** [comment]
> I am OK if you want to move this from PerfView into TraceEvent so that you can do the SpeedScope conversion there

Great! I've created #1112, it turned out to be a matter of moving 3 files.
