### ISSUE TITLE
perfcollect: too many arguments

### ISSUE THREAD

**Issue by adamsitnik** [microsoft/perfview#1109]
I've downloaded the latest version of PerfCollect from master and run into following problem:

```log
./perfcollect: line 1416: [: too many arguments
```

![image](https://user-images.githubusercontent.com/6011991/75808956-36876600-5d88-11ea-9a5d-5f188041aa2e.png)

The produced trace file LGTM, I just wanted to report it because it might broke something that I am not using.

/cc @brianrob @ooooolivia

**Comment by brianrob** [comment]
Thanks for reporting @adamsitnik.  I can't repro this - what distro are you running on?

**Comment by adamsitnik** [comment]
@brianrob Ubuntu 18.04

**Comment by brianrob** [comment]
Let me try it there and see what I get.

**Comment by brianrob** [comment]
Hmm.. I'm not able to repro this on 18.04 either.  Would it be possible for you to uncomment the "set -x" line in the script, re-run and share the output?
