### ISSUE TITLE
PerfView SpeedScope export: ArgumentException when exporting a Linux kernel thread

### ISSUE THREAD

**Issue by antonfirsov** [microsoft/perfview#1126]
When exporting traces from a kernel thread thread `io_wqe_worker-1` to SpeedScope json:
![image](https://user-images.githubusercontent.com/6835152/76774129-d17a3a00-67a3-11ea-8fb2-2ff0f7048d1b.png)

I'm encountering the following error:
https://gist.github.com/antonfirsov/3063e42a453f5ef5f7553f26ccbb452f

**Steps to reproduce:**
Use `IoUringTransport-RPS-523K.trace.zip` from here:
https://microsoft-my.sharepoint.com/:f:/p/anfirszo/Enb3e3pEI2dMrGbxSstPKJQBYWLacpLMwuZz1Lkab_9-bw?e=KHn80o

**PerfView version:**
Latest release (Dec 17)

/cc @adamsitnik

**Comment by adamsitnik** [comment]
@antonfirsov could you please try to repo it with the latest version: https://github.com/microsoft/perfview/releases/tag/P2.0.50 ?

**Comment by antonfirsov** [comment]
Seems to be fixed in the new version, sorry for not noticing it.

**Comment by adamsitnik** [comment]
@antonfirsov no problem, I am glad that it works now!
