### ISSUE TITLE
Switching from fields to properties will make code clean and might increase performance.

### ISSUE THREAD

**Issue by HMartyrossian** [microsoft/perfview#1128]
Implementing a property instead of field will make code more maintainable and might increase performance. Please see:
https://stackoverflow.com/questions/9842917/field-vs-property-optimisation-of-performance

**Comment by brianrob** [comment]
@HMartyrossian this is not the kind of change that we want to take across the product.  This would introduce a lot of churn for minimal if any impact.

From a performance perspective, fields and simple get properties have essentially the same performance as the JIT will inline simple properties.

I am going to go ahead and close this issue.
