### ISSUE TITLE
Perfview doesn’t read Linux .nettrace collected from linux container

### ISSUE THREAD

**Issue by AmrutaMoghe** [microsoft/perfview#1140]
I ran dotnet-trace in linux container, moved it to host from container , host is windows machine. The .nettrace file is not being recognized by perfview

**Comment by brianrob** [comment]
@AmrutaMoghe can you provide a bit more information on this?  Does PerfView not display the file at all, such that you can't open it, or does it show up but give you an error when you open it?

Can you by chance share the file?

**Comment by AmrutaMoghe** [comment]
Perfview doesnot display the file.
Can you tell me how can I troubleshoot?

**Comment by brianrob** [comment]
If you're not seeing the file at all, then it's likely one of two issues:
1. The directory at the top left in the main PerfView window is incorrect.
2. The file extension has a typo in it.

PerfView simply looks for "*.nettrace" files and then displays them so that you can double click on them to open.

**Comment by TJClifton90** [comment]
I can confirm that this is not working for me either.

I took a trace from a Linux machine which generated a .nettrace file. The file is not listed in the directory view in Perf View (I even tried moving it to different directories) and attempting to type in the directory resulted in the following error in the tray at the bottom of Perf View: 

`Error: Could not determine data Template from the file extension for C:\Users\Tom\Desktop\servertrace.nettrace.`

Have you got any suggestions as to what might be going wrong or is this a bug related to nettrace captures from Linux? I have added details of the versions of the various tools below.

Dot Net Core Version: 3.1.201
Dot Net Trace Tool Version: 3.1.57502+6767a9ac24bde3a58d7b51bdaff7c7d75aab9a65
Perf View Version: 2.0.52

**Comment by TJClifton90** [comment]
Apologies, my previous comment was incorrect somehow I was running an old version of PerfView (I thought I had downloaded 2.0.52 but must have opened some other version). Running on 2.0.52 allowed me to view the trace as expected. It might be worth the OP double checking he hasn't made a similar mistake.

**Comment by brianrob** [comment]
Yes, @TJClifton90, you have a good point - please do check to make sure you're running the latest version of PerfView.  .nettrace files are relatively new and so there will be lots of old versions of PerfView that don't recognize them.

**Comment by dashesy** [comment]
When searching "PerfView" [this version](https://www.microsoft.com/en-us/download/details.aspx?id=28567) comes up for download.

**Comment by brianrob** [comment]
@dashesy, that is quite an old copy and won't have support for nettrace files.  However, there are instructions on the download page, redirecting users to the GitHub releases page.

I'm going to go ahead and close this out, as it seems that folks just need a newer copy of PerfView.

**Comment by dashesy** [comment]
It is. Is there a way to retire these old links? perhaps change that to the release page on GitHub instead.

**Comment by brianrob** [comment]
I'm not sure, as I've not dealt with the Microsoft Download Center, but I'll see if I can find any info on this.

**Comment by baekhyunee7** [comment]
so anyone  got the solution?
