### ISSUE TITLE
NullReferenceException when accessing ProcessTraceData properties

### ISSUE THREAD

**Issue by mpolicki** [microsoft/perfview#1162]
### The problem
I know the documentation says that event data objects are aggressively reused and to only access them immediately in their event handlers. However, I wasn't aware of that when I got a confusing `NullReferenceException` while trying to access a value-type property on a non-null `ProcessTraceData` object in code like the following:
```C#
    class Program
    {
        static void Main()
        {
            var processStartActions = new List<Action>();
            using(var session = new TraceEventSession(KernelTraceEventParser.KernelSessionName, TraceEventSessionOptions.NoRestartOnCreate))
            {
                Console.CancelKeyPress += (object sender, ConsoleCancelEventArgs eventArguments) => session.Dispose();
                session.EnableKernelProvider(KernelTraceEventParser.Keywords.Process);
                session.Source.Kernel.ProcessStart += (ProcessTraceData data) => processStartActions.Add(() => ProcessStart(data));
                session.Source.Process();
                foreach(var action in processStartActions)
                    action();
            }

            void ProcessStart(ProcessTraceData data)
            {
                Console.WriteLine($"{data.ProcessID}\t{data.ParentID}\t{data.ProcessName}");
            }
        }
    }
```
The access to `data.ProcessID` throws the exception. To reproduce, run the code, start a process, switch to the console and press `Ctrl C` or `Ctrl Break`.

### What I expect
A semantically appropriate exception with an explanatory message. `InvalidOperationException` perhaps?

**Comment by brianrob** [comment]
@mpolicki unfortunately, this isn't something that's easily done.  The issue is that things are re-used, and so there's not a clear opportunity to detect improper use.  We could likely do some of this, but it would be very incomplete, and probably not worthwhile overall.

I appreciate you reporting this, but I suspect the documentation will need to be good enough.
