### ISSUE TITLE
PerfView should inform the user the # of lost events for .nettrace traces

### ISSUE THREAD

**Issue by Maoni0** [microsoft/perfview#1168]
we should display the # of lost events for .nettrace files like we do with ETW traces. I have a trace with some very suspicious GCStats and it was due to lost events (it has 3 millions events with 15 million lost events based on the EventsLost from event pipe. happy to share the trace if you need. 

also CC @noahfalk who helped me look at the lost events.

**Comment by brianrob** [comment]
Please do share the trace. Happy to make this improvement.

**Comment by Maoni0** [comment]
done!
