### ISSUE TITLE
How to retrieve header EVENT_TRACE values from data which is of type TraceEvent class

### ISSUE THREAD

**Issue by SoibamRepo** [microsoft/perfview#1169]

**Comment by SoibamRepo** [comment]
Referring to one of TraceEventSamples, 31_KernalAndClrFile.cs, there is callback function Print(TraceEvent data) which print events in String format. The input parameter is "data" which is of type TraceEvent class. 

My query is as below: 

How do I retrieve header values which is in structure EVENT_RECORD from "data" of type TraceEvent 

internal struct EVENT_RECORD
{
            public EVENT_HEADER EventHeader;            //  size: 80
            public ETW_BUFFER_CONTEXT BufferContext;    //  size: 4
            public ushort ExtendedDataCount;
            public ushort UserDataLength;               //  offset: 86
            public EVENT_HEADER_EXTENDED_DATA_ITEM* ExtendedData;
            public IntPtr UserData;
            public IntPtr UserContext;
}

private static void Print(TraceEvent data)
        {
            // There are a lot of data collection start on entry that I don't want to see (but often they are quite handy
            if (data.Opcode == TraceEventOpcode.DataCollectionStart || data.Opcode == TraceEventOpcode.DataCollectionStop)
            {
                return;
            }

            // Merging inject some 'symbol' events that are not that interesting so we ignore those too.  
            if (data.ProviderGuid == SymbolTraceEventParser.ProviderGuid)
            {
                return;
            }

            // To avoid 'rundown' events that happen in the beginning and end of the trace filter out things during those times
            if (data.TimeStampRelativeMSec < 1000 || 9000 < data.TimeStampRelativeMSec)
            {
                return;
            }
            Out.WriteLine((data.ToString());

**Comment by brianrob** [comment]
It is not possible to get at all of these fields directly as `TraceEvent` attempts to make these events more consumable in managed code.

Much of this data can be retrieved through properties of the `TraceEvent` class.  Please take a look at https://github.com/microsoft/perfview/blob/master/src/TraceEvent/TraceEvent.cs#L551 for details.

**Comment by SoibamRepo** [comment]
could we typecase class "TraceEvent"  to another class SampledProfileTraceData or StackWalkStackTraceData. 

in below sample examples referred from code "32_KernelAndClrFile.cs", it takes 1 argument of type TraceEvent. 
static void Print(TraceEvent data)
        {
              out.Writeline (data.ToString());
       }
Inside Print function, we want to access fields/method of class StackWalkStackTraceData and SampledProfileTraceData from TraceEvent data. I have tried typecasting  data as below 

SampledProfileTraceData profileTraceData = data as SampledProfileTraceData;
SampledProfileTraceData profileTraceData = (SampledProfileTraceData) data ;

Both fails in typecasting. 

regards
Soibam

**Comment by SoibamRepo** [comment]
the  issue is resolved.
