### ISSUE TITLE
.NETCore\TraceEventCore.xproj not supported by vanilla VS 2015

### ISSUE THREAD

**Issue by jkotas** [Microsoft/perfview#117]
Opening src/PerfView/Perfview.sln gives me:

![image](https://cloud.githubusercontent.com/assets/6668460/18619933/30d2d52c-7dbd-11e6-8d50-345d80650bf1.png)

Is there .NET Core Preview that needs to be installed to make this work?

**Comment by MagicAndre1981** [comment]
install the .net core tools: https://go.microsoft.com/fwlink/?LinkId=827546

**Comment by vancem** [comment]
Ugg, I don't really want to be in the business of figuring out which version of VS support xproj (.NET Core) projects.   I will update the docs to let people know

1) That the TraceEventCore project is not central to the build.  They can safely ignore it (unless they want a version of TraceEvent that runs on .NET Core).    

2) How to get VS Update 3 (which should fix the problem). 

See 
https://github.com/Microsoft/perfview/blob/master/README.md
