### ISSUE TITLE
EventPipeEventSource constructor blocks until the first event is read

### ISSUE THREAD

**Issue by sywhang** [microsoft/perfview#1172]
Moving https://github.com/dotnet/diagnostics/issues/1060 to here because this repo is a better place to keep track of this issue:

From @davmason:

If you follow the sample code on how to use EventPipeEventSource but replace the provider with a provider that doesn't produce any events, it will block forever in the constructor to EventPipeEventSource.
```csharp
    var providers = new List<EventPipeProvider>()
    {
        new EventPipeProvider("Microsoft-Windows-DotNETRuntime",
            EventLevel.Informational, (long)ClrTraceEventParser.Keywords.GC)
    };

    var client = new DiagnosticsClient(processId);
    using (var session = client.StartEventPipeSession(providers, false))
    {
        var source = new EventPipeEventSource(session.EventStream);

        source.Clr.All += (TraceEvent obj) => {
            Console.WriteLine(obj.EventName);
        }
        try
        {
            source.Process();
        }
        // NOTE: This exception does not currently exist. It is something that needs to be added to TraceEvent.
        catch (EventStreamException e)
        {
            Console.WriteLine("Error encountered while processing events");
            Console.WriteLine(e.ToString());
        }
    }
```
It will block on this line: https://github.com/microsoft/perfview/blob/cb1943b8ded584e136e140746e5771ca63668c5a/src/TraceEvent/EventPipe/EventPipeEventSource.cs#L68

This seems like a pitfall, and it's not clear what is happening. I've used that code pattern lots before and it's never failed, then all of a sudden it hangs my app and I have to do a lot of digging to understand why. I imagine customers will run in to it as well.

**Comment by raffaeler** [comment]
This is very problematic when we try to hook the very first events coming from a process.
As the constructor is blocked, the events cannot be subscribed and therefore there is a high chance to lose the first events.

**Comment by brianrob** [comment]
@sywhang, are you planning to fix this?  If I understand correctly, this sounds like an issue that is specific to live sessions.

**Comment by sywhang** [comment]
Sure. I can take a look at this some time this week.

**Comment by brianrob** [comment]
Thanks much @sywhang.

**Comment by mwasplund-msft** [comment]
It looks like @sywhang  is no longer at Microsoft, @brianrob can someone else take a look at this?

**Comment by brianrob** [comment]
@josalem can you take a look at this now that @sywhang is no longer at Microsoft?  Thinking about this one a bit, I think that it's reasonable to block when waiting for the next event after Process is called, but we shouldn't be blocking in the constructor.  This would be consistent with how ETW real-time sessions work.

**Comment by josalem** [comment]
Can do. This is a recurring issue and is unexpected behavior I would argue. I think care may need to be taken on "fixing" this, however, as this has been the behavior for a long while and changing it without an opt-in has the potential to break existing tools if they update their TraceEvent version.

**Comment by brianrob** [comment]
Thanks John.  To be honest, I'm not concerned about putting this behind a flag unless it has other more far reaching implications.  If you're concerned, one thing you could consider is submitting it to the feature/perfview-3.0 branch.  I'm batching up some larger changes that I'm going to release with a 3.0 version, and so this could be part of that.

**Comment by davmason** [comment]
+1 to not requiring a flag. It is technically a behavior change, but it's hard to imagine anyone relying on it.

I have helped multiple people figure out why their code was seemingly deadlocked, it is hard/impossible for someone unfamiliar with the internal of TraceEvent to figure out what is happening.
