### ISSUE TITLE
ArgumentOutOfRangeException while listening with TraceEvent

### ISSUE THREAD

**Issue by kripergvg** [microsoft/perfview#1174]
I don't have reproducible example but sometimes our process crashes while listening to diagnostic events with TraceEvent library
Stacktrace 
![image](https://user-images.githubusercontent.com/7288803/81971867-7097a280-962a-11ea-8df5-d2c294c5cfad.png)

Microsoft.Diagnostics.NETCore.Client Version="0.2.61701"
Microsoft.Diagnostics.Tracing.TraceEvent Version="2.0.47"
.NET Core 3.1

**Comment by brianrob** [comment]
@noahfalk, can you please take a look?

**Comment by noahfalk** [comment]
@kripergvg sorry you are running into this issue! Could you check to see if this problem repros on a newer build of TraceEvent? There is at least one bug that was [fixed](https://github.com/microsoft/perfview/pull/1047) in the StreamReader after 2.0.47 that might be causing the failure you are seeing.

If that doesn't resolve it, we'd need to gather some more info to investigate productively. In lieu of a repro here are some other alternatives that might shine some light on the situation:
1. Ensure the trace data is buffered to disk before you try to parse it, then share the trace with us the next time it fails.
2. Capture a dump of the process at the time you've got that stacktrace and then share the dump

Is that something you'd be able to do?

**Comment by kripergvg** [comment]
@noahfalk I am going to update the package if it won't help I will get a dump. Thank you.

**Comment by brianrob** [comment]
Bulk closing old issues.  Please re-open if necessary.
