### ISSUE TITLE
How to access next events in TraceEvents ?

### ISSUE THREAD

**Issue by SoibamRepo** [microsoft/perfview#1179]
@brianrob 

Hello, 
Referring to sample "TraceEventSamples",  below codes get to display events sequentially in string format

private static void Print(TraceEvent data)
        {
            // There are a lot of data collection start on entry that I don't want to see (but often they are quite handy
            if (data.Opcode == TraceEventOpcode.DataCollectionStart || data.Opcode == TraceEventOpcode.DataCollectionStop)
            {
                return;
            }

            // Merging inject some 'symbol' events that are not that interesting so we ignore those too.  
            if (data.ProviderGuid == SymbolTraceEventParser.ProviderGuid)
            {
                return;
            }

            // To avoid 'rundown' events that happen in the beginning and end of the trace filter out things during those times
            if (data.TimeStampRelativeMSec < 1000 || 9000 < data.TimeStampRelativeMSec)
            {
                return;
            }
			
			Out.Writeline(data.ToString());
}	

Output:

<Event MSec=    "18.0830" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542A75262" ThreadID="0" Count="1"/>
<Event MSec=    "18.1560" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542A75262" ThreadID="0" Count="1"/>
<Event MSec=    "18.1644" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542A75262" ThreadID="0" Count="1"/>
<Event MSec=    "18.2103" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542B4D103" ThreadID="0" Count="1"/>
<Event MSec=    "18.2408" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542A75262" ThreadID="0" Count="1"/>
<Event MSec=    "18.2409" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542A75262" ThreadID="0" Count="1"/>
<Event MSec=    "18.2529" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF805429047C7" ThreadID="0" Count="1"/>
<Event MSec=    "18.2544" PID=  "-1" PName=        "" TID=   "0" EventName="PerfInfo/Sample" InstructionPointer="0xFFFFF80542A75262" ThreadID="0" Count="1"/>
<Event MSec=    "18.2640" PID=   "0" PName=        "" TID=   "0" EventName="StackWalk/Stack" EventTimeStampQPC="353,909,493,736" EventTimeStampRelativeMSec="18.2103" FrameCount="6">
  0xfffff80542b4d103  0xfffff80542a2e09e  0xfffff80542904997  0xfffff80542a78390  0xfffff80542a780b7  0xfffff80542a75262
</Event>

Query :
When it reach and process event with  MSec=    "18.2103",  how do I move forward  and  read next event MSec= "18.2640" ? Is there avaialble function which I can refere it ? Inside Print function , we have data of class type "TraceEvent"

Regards
Soibam

**Comment by brianrob** [comment]
Generally, the pattern that you'll want to use is to register callbacks, such as the `Print` method that you specified above.  Once you've registered callbacks for specific types of events, or just used the `TraceEventDispatcher.All` API to get a callback for every event, just call `TraceEventDispatcher.Process()` and this will cause the dispatcher to iterate through all events and execute any callbacks that have been registered.  Does that answer your question?

**Comment by SoibamRepo** [comment]
Thanks @brianrob . your anser gives pointers which I am looking for .. Close this issue
