### ISSUE TITLE
[TraceEvent] IndexOutOfRangeException - SymbolReader.FindSymbolFilePathForModule

### ISSUE THREAD

**Issue by suprak** [microsoft/perfview#1187]
A partner reported the following exception,

```
System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.

   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at Microsoft.Diagnostics.Symbols.SymbolReader.FindSymbolFilePathForModule(String dllFilePath, Boolean ilPDB)
   ...
```

In our use of `SymbolReader` we construct it with `new SymbolReader(this.logStream, SymbolPath.SymbolPathFromEnvironment);`. However `this.logStream` is not used in our code except on dispose (to dispose).

Also calls to `SymbolReader.FindSymbolFilePathForModule` are single threaded.

**Comment by brianrob** [comment]
@suprak, are you able to reproduce this, or do you have a process dump that you can share of this?  We'll likely need one of these to diagnose this issue.

**Comment by suprak** [comment]
Provided @brianrob a repro internally.
Recommendation is to wrap the `TextWriter` we provide with one that implements explicit locking.

However it would be good to see this land as a fix in TraceEvent it self, since the usage of the log writer in `SymbolReader` is not safe (likely due to ngen pdb process launch creation logic).

**Comment by brianrob** [comment]
@suprak, I have posted #1198 to fix this.  Note that it will help for uses within `SymbolReader`, but doesn't solve the problem for any uses of the input stream by the caller.

**Comment by suprak** [comment]
@brianrob makes sense, thank you for the quick turn around!
