### ISSUE TITLE
Generating typed client for EventSource (.NET Core)

### ISSUE THREAD

**Issue by raffaeler** [microsoft/perfview#1195]
I created a custom `EventSource` class exposinga single `EventCounter`. It works and I can use it by dynamically parsing the content on the client side.

Now I tried to create a typed client with different strategies, but all of them failed:
* Creating the manifest and later possibly using TraceParserGen
```
System.Diagnostics.Tracing.EventSource.GenerateManifest(
    typeof(CustomHeaderEventSource),
    typeof(CustomHeaderEventSource).Assembly.Location);
```
This method fails with the following Exception: 
```
Unsupported type EventCounter in event source
This exception was originally thrown at this call stack:
    System.Diagnostics.Tracing.ManifestBuilder.ManifestError(string, bool)
    System.Diagnostics.Tracing.ManifestBuilder.GetTypeName(System.Type)
    System.Diagnostics.Tracing.ManifestBuilder.AddEventParameter(System.Type, string)
```

* Using TraceParserGen tool on the dll containing the `EventSource`
I cloned the repo and compiled the tool and the run:
```
traceparsergen -EventSource:"" CustomEventSource.dll
```
The error is: `Error: Exception has been thrown by the target of an invocation.`
By running the tool under VS, the real message is `Unsupported type EventCounter in event source`.
> Note: by reversing the order of the parameters the custom event source cannot be found in the dll.

* Generating the manifest using PerfView.
Apparently there is no way for EventSource classes created in .NET Core to do that.

Can someone tell me what is going wrong here?
Thank you

**Comment by brianrob** [comment]
Following up on this older issue - if this is still an issue, I would recommending filing an issue in https://github.com/dotnet/runtime, since this is calling into code contained in the dotnet/runtime repo.
