### ISSUE TITLE
TraceLog.Dispose() can't be called a second time

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/perfview#1207]
It looks like the 2nd call on `FastSerializtion.Deserializer.Dispose()` is throwing. This is discourage to write code to dispose aggressively. Is it possible to make it can be called multiple times without throwing?

![image](https://user-images.githubusercontent.com/3674549/84601296-ef534b80-ae33-11ea-94dd-b50ab26b19b4.png)

Repo:
```csharp
            this.TraceLog?.Dispose();
            this.TraceLog?.Dispose();  // Throws on the 2nd call.
```

Callstack:

```csharp
Exception has occurred: CLR/System.NullReferenceException
Exception thrown: 'System.NullReferenceException' in Microsoft.Diagnostics.FastSerialization.dll: 'Object reference not set to an instance of an object.'
   at FastSerialization.Deserializer.Dispose()
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.Dispose(Boolean disposing)
   at Microsoft.Diagnostics.Tracing.TraceEventSource.Dispose()
```

**Comment by brianrob** [comment]
Thanks for reporting.  I've posted #1210 to address this.

**Comment by xiaomi7732** [comment]
The fix LGTM.
