### ISSUE TITLE
EventStats show duplicate entries

### ISSUE THREAD

**Issue by sywhang** [microsoft/perfview#1216]
EventStats window is showing duplicate entries for 

Microsoft-Diagnostics-DiagnosticSource/Activity1Start and Microsoft-Diagnostics-DiagnosticSource/Activity1Stop events.

![image](https://user-images.githubusercontent.com/30421794/85461386-296dcd00-b559-11ea-8ff2-1e83443ed79f.png)

**Comment by brianrob** [comment]
Bulk closing old issues.  Please re-open if necessary.
