### ISSUE TITLE
UNMANAGED_CODE_TIME frames in Linux traces

### ISSUE THREAD

**Issue by swift-kim** [microsoft/perfview#1217]
When I open up a .nettrace file (generated by the .NET Core runtime via dotnet-trace or COMPlus_EnableEventPipe=1) with **PerfView** or **speedscope**, the top most frame of every CPU sample is always either **CPU_TIME** or **UNMANAGED_CODE_TIME**.

As a result, there's no meaningful information I can get from the file when I sort the frames by **Exclusive** or **Self** time.

![image](https://user-images.githubusercontent.com/40190588/85645331-58f51480-b6d4-11ea-9fdd-fd0a0a488fc4.png)

![image](https://user-images.githubusercontent.com/40190588/85645439-affae980-b6d4-11ea-8f5a-0ef39d8319e1.png)

On Windows, I can filter them out using FoldPats in PerfView. On Linux, dotnet-trace (the speedscope exporter) doesn't provide such option so there's nothing I can do.

Is it only me seeing this issue? Or should we fix something in TraceEvent?

p.s. When I removed the following line in `SampleProfilerThreadTimeComputer.cs`, the result looked better on speedscope, showing the actual time-consuming methods in the same view.

https://github.com/microsoft/perfview/blob/91a55f2e715fe1e094ad71304f413f3bf7e53ee8/src/TraceEvent/Computers/SampleProfilerThreadTimeComputer.cs#L539

![image](https://user-images.githubusercontent.com/40190588/85646854-0fa6c400-b6d8-11ea-8fbc-06f8f8cad987.png)

**Comment by adamsitnik** [comment]
The `UNMANAGED_CODE_TIME` tells us that the time was spent in native (unmanaged) code. Personally I like to have this information because if `UNMANAGED_CODE_TIME` is high I switch from `dotnet trace` to `perfcollect`.

I assume that `CPU_TIME` means a CPU time spent in managed code? @noahfalk am I right?

Perhaps we could add some filtering to `dotnet trace convert` command?

**Comment by noahfalk** [comment]
> I assume that CPU_TIME means a CPU time spent in managed code? @noahfalk am I right?

Yeah, if at the time of thread suspension we were running managed code then we bucket it as CPU_TIME. If at the time of suspension the thread was outside managed code then we can't tell if it is executing some native code on the CPU or it is switched out in the kernel scheduler. So regardless of whether you called into native code for WaitForMutex() or DoATrillionMathOps(), the trace reports UNMANAGED_CODE_TIME.

**Comment by swift-kim** [comment]
@adamsitnik More than 99% of CPU time in my samples is UNMANAGED_CODE_TIME and the information is barely helpful for me... I would prefer eliminating those top most frames by default (e.g. by adding a filtering option like `--fold-patterns` which defaults to `CPU_TIME;UNMANAGED_CODE_TIME`) and enabling explicitly when they're required. However, adding such an option would require modifying the existing [dotnet-trace specification](https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/dotnet-tools.md) and eventually adding more and more configurable options (such as `Start`, `End`, `GroupPats`, `IncPats`, ... in PerfView). I would not put this task in my priority queue for now. Thanks anyway!

**Comment by adamsitnik** [comment]
@swift-kim I've created a proposal: https://github.com/dotnet/diagnostics/issues/1301

**Comment by swift-kim** [comment]
@adamsitnik Thanks! Let me track the proposal and help if I can.

**Comment by swift-kim** [comment]
Closing for now.
