### ISSUE TITLE
a small confusion

### ISSUE THREAD

**Issue by drduan** [Microsoft/perfview#124]
I Don't Know why there is a ' ^' ?
![confusion](https://cloud.githubusercontent.com/assets/7875572/18779920/ac8fcf3c-81ad-11e6-9dce-a2981e6a6315.png)

**Comment by bryanar** [comment]
[^ is the logical XOR operator.](https://en.wikipedia.org/wiki/Exclusive_or)

^= is a '[compound operator](https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/expressions)' 

If we expand this line out, it looks like this:
`crc32 = crc32 ^ 0xffffffffU;`
