### ISSUE TITLE
Which versions of .NetCore does PerfView work with?

### ISSUE THREAD

**Issue by clcProjects** [microsoft/perfview#1240]
hi,

This is probably a dumb question, but I've looked through the user guide: https://github.com/Microsoft/perfview/blob/master/src/PerfView/SupportFiles/UsersGuide.htm and have not been able to find which versions of .Net Core Perfview works with. We have a .Net Core 2.0 project running in win2016.  Will perfview work with 2.0?

Thanks,
Paul

**Comment by brianrob** [comment]
@clcProjects, PerfView will work with all versions of .NET Core including 2.0.  In general, if the application runs on Windows, PerfView will work with it.  For .NET runtimes specifically, some runtimes have more diagnostic data that PerfView can display than others, but you should be in reasonably good shape with .NET Core 2.0.

**Comment by clcProjects** [comment]
Many thanks Brian!
