### ISSUE TITLE
Perfview could not set CPU sample time inside a container

### ISSUE THREAD

**Issue by zhouqifan2015** [microsoft/perfview#1245]
Hey folks, I manually run a perfview collection with setting /CpuSampleMSec:10, it failed set the property:

`Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
[Error: Can't set CPU sampling to 10.000MSec.]`

And I try yo remove the CpuSampleMSec setting, it could run collection successfully.
Is this a known issue ?

**Comment by brianrob** [comment]
@zhouqifan2015 I suspect that this is likely a container limitation, as this does work outside of the container environment (I just confirmed to make sure that there wasn't a bug I was unaware of).  What kind of container are you attempting to collect in?  Is this a shared kernel or isolated kernel container?

**Comment by zhouqifan2015** [comment]
> @zhouqifan2015 I suspect that this is likely a container limitation, as this does work outside of the container environment (I just confirmed to make sure that there wasn't a bug I was unaware of). What kind of container are you attempting to collect in? Is this a shared kernel or isolated kernel container?

Thanks you Brian ! I agree this works outside of container, that's what I did before. For this issue I run into, I was just using docker to create a container with a WinServer image from docker hub. So I think this a shared kernel container.

**Comment by brianrob** [comment]
Yes, I suspect that you're right that this is a shared kernel environment.  By default, you get a shared kernel container if you run on Windows Server.  My understanding is that you will only be able to change this configuration by collecting on the host.

**Comment by zhouqifan2015** [comment]
Thank you Brian ! I think your understanding is totally correct, this makes sense to me now. Closing this issue.
