### ISSUE TITLE
http 500 when running PerfViewJS on linux

### ISSUE THREAD

**Issue by webczat** [microsoft/perfview#1260]
Hi, tried to run PerfViewJS on linux using dotnet run, newest master, dotnet core 3.1.
It builds and runs, but invoking the browser indicates empty HTTP 500 error. There are no logs accessible to me so I cannot quite say why.
I just pass port 5000 and some empty directory as data root in program arguments.

**Comment by brianrob** [comment]
@mjsabby

**Comment by mjsabby** [comment]
I will take a look in a couple of weeks. sorry for the delay here @webczat

**Comment by webczat** [comment]
friendly ping :)

**Comment by dront78** [comment]
still there

**Comment by brianrob** [comment]
Closing as PerfViewJS was moved to https://github.com/microsoft/perfviewjs.
