### ISSUE TITLE
[Question] Cannot capture events from TraceLogging Provider: Microsoft.Windows.Kernel.Power and Microsoft.Windows.Power.SleepStudy

### ISSUE THREAD

**Issue by guliteb** [microsoft/perfview#1263]
I want to capture events real time from some TraceLogging Providers: Microsoft.Windows.Kernel.Power and Microsoft.Windows.Power.SleepStudy. But I cannot see any events from them. However, events are captured in ETL by WPR and shown in WPA.

Is there any comments?

**Comment by brianrob** [comment]
Bulk closing old issues.  Please re-open if needed.
