### ISSUE TITLE
High CPU usage on IIS (w3wp.exe) gives no 'hot path' in CallTree tab

### ISSUE THREAD

**Issue by Mek7** [microsoft/perfview#1269]
Hi,
I'm troubleshooting why our production web server has high CPU usage by w3wp.exe since last release of our software.
There are more application pools (and so there are more instances of w3wp.exe) and the most relevant is process ID 9812 so I am investigating data captured from this process.
My problem is that in CallTree there is 100% in the Inc % column for the "Process64 w3wp (8912)", but when expanded, its children do not add up to 100%, and there is no obvious hot path under this node. All child nodes have some very low number in Inc % column.

![Capture](https://user-images.githubusercontent.com/12199478/93346355-2e7aa980-f834-11ea-9928-82aec490f17f.JPG)

I have read the documentation, but didn't find any clue of what went wrong or how to investigate further. I have also set the Fold percentage to zero, but it didn't help. Or maybe this situation means that all that missing CPU is consumed by native call stacks? I don't know, please advise...

**Comment by Mek7** [comment]
I'd also like to add label 'question' to this issue (as stated in the readme that I should do it, as this is not a bug report, but question) but I'm unable to find out how, probably I don't have permission.

**Comment by brianrob** [comment]
@Mek7, how close to 100% do you get if you add up all of the thread nodes under the process?  There have been some issues in this space, and they're usually related to floating point precision.  I see that you've set fold % to 0 which is the most common issue.

**Comment by Mek7** [comment]
Well, I don't know, I have fixed the performance issues in the meantime. I just wasn't sure how to interpret this, that's why I raised this question. Anyway, if I have to use PerfView again in the future, I will try to add up the numbers to see how close to 100% I can get. I am closing this issue now.
