### ISSUE TITLE
Can PerfView run on Linux system?

### ISSUE THREAD

**Issue by sunny868** [microsoft/perfview#1273]
Can PerfView run on Linux system? If not, when can we support it?

**Comment by Mek7** [comment]
See also #903

**Comment by brianrob** [comment]
PerfView itself is a WPF app, so no it does not run on Linux.  It can, however, open and parse Linux traces captured either via `perfcollect` or with `dotnet-trace`.  It is also possible to use the `TraceEvent` library on Linux to open traces if you wanted to host it in your own application.

**Comment by sunny868** [comment]
thanks
