### ISSUE TITLE
Provide GUI warning popup when closing PerfView during rundown/zipping

### ISSUE THREAD

**Issue by rauhs** [microsoft/perfview#1293]
Hi all,

first of all: Thanks for PerfView, it has recently become a very valuable tool in our company! 👍 

We deploy a very large .NET application to our customers and hence we (developers) don't run PerfView but instead our customers do. This is an issue since they very often don't wait for the rundown/zipping. Of course we try to give as detailed instructions as possible and tell them to await the rundown (while it blinks in the bottom right corner) but it's often in vain. About 30% of the ETL files are prematurely aborted :/

Hence: Would it be possible to have a warning window if the user wants to quit PerfView while the rundown/zipping is going on?

Cheers from Germany

**Comment by brianrob** [comment]
@rauhs, I'm glad that PerfView has been useful to you.  This is actually the first time that I've heard of this issue - it's interesting that you get that many ETLs that are not merged.  One thing that might help would be to have customers specify the `/AcceptEULA` and `/NoGui` arguments.  This would mean that the they would just get a command line view of what's happening, which might help make it clear that work is still happening.

It is possible to add a warning, but the NoGui option might give you immediate relief.  I'll keep this issue around, but I'm not sure when we'd get to it.  If this is something that you're interested in submitting, we'd certainly accept a PR in this space.

**Comment by rauhs** [comment]
Just a little note: Nico is a student in our company and he's worked on this for us.
