### ISSUE TITLE
Is it possible to use TraceEvent Library to do profiling app without elevation?

### ISSUE THREAD

**Issue by cheverdyukv** [microsoft/perfview#1298]
Hi

I have an idea to do automatic monitoring of certain activities of our application to detect performance issues. I'm planning to use TraceEvent Library to capture only CPU Samples then analyzing them and then ask user to upload capture if some issue is detected. 

But as I see most activities in TraceEvent Library requires elevation. Is it possible to do only CPU Samples without elevation?
It looks to me that it is not possible, but I just would like to double check.

Thank you,
Vlad

**Comment by brianrob** [comment]
@cheverdyuku, unfortunately not.  ETW requires administrator privileges to create a session that enables kernel events, such as CPU samples.

**Comment by cheverdyukv** [comment]
Ok, thank you

**Comment by miloush** [comment]
What if I don't need kernel events, and I want to monitor only events from my own process?

How does Diagnostic Hub in Visual Studio collect events without elevation?

**Comment by brianrob** [comment]
If you're just listening to user-mode events in processes you have access to, then you should be able to create a session that listens to just those processes without having to elevate.
