### ISSUE TITLE
The "build" assets in the "Microsoft.Diagnostics.Tracing.TraceEvent" package should also be "buildTransitive"

### ISSUE THREAD

**Issue by tompazourek** [microsoft/perfview#1301]
## Problem

The `Microsoft.Diagnostics.Tracing.TraceEvent.props` file that's stored inside the `build` folder of the `Microsoft.Diagnostics.Tracing.TraceEvent` package is responsible for copying the native DLLs to the output directory. (Looking at the current version `2.0.61`)

However, due to the nature of how `build` assets work in NuGet, this will only be applied on the project that directly references this package. If there's another dependency step between, the native DLLs will not end up in the other projects. More info [here](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior).

## Example

For example, `ProjectA` references the `Microsoft.Diagnostics.Tracing.TraceEvent` package, and `WebApplicationB` references `ProjectA`. Then the native DLLs won't end up in the final output of `WebApplicationB`, which is where they are needed, because `ProjectA` is just a class library, not an executable.

## Solution?

This can be solved by having the `Microsoft.Diagnostics.Tracing.TraceEvent.props` file twice in the NuGet package -- once in the `build` folder, and once in the `buildTransitive` folder.

**Comment by brianrob** [comment]
@tompazourek, this seems like a reasonable thing to do.  Would you be up for submitting a PR?
