### ISSUE TITLE
suggestion: add some clear descptions about how to run it in readme.md

### ISSUE THREAD

**Issue by YUbuntu0109** [microsoft/perfview#1316]
🤔the content of description not clear in `README.md` bro, such as you should tell me the step about `how to run it`. . .

**Comment by brianrob** [comment]
@YUbuntu0109, take a look at the user's guide to get started: http://htmlpreview.github.io/?https://github.com/Microsoft/perfview/blob/master/src/PerfView/SupportFiles/UsersGuide.htm

**Comment by YUbuntu0109** [comment]
> @YUbuntu0109, take a look at the user's guide to get started: http://htmlpreview.github.io/?https://github.com/Microsoft/perfview/blob/master/src/PerfView/SupportFiles/UsersGuide.htm

ohh thanks bro
