### ISSUE TITLE
Question: How to install perfview using PowerShell on Server Env

### ISSUE THREAD

**Issue by marafiq** [microsoft/perfview#1328]
Question: How to install perfview using PowerShell on Server? Or is there a package which can be installed using PowerShell or choco.

**Comment by brianrob** [comment]
@marafiq, PerfView doesn't require an install - you can just download the exe and run it.  Thus, there isn't an installer package.

**Comment by marafiq** [comment]
@brianrob thanks I guess I was looking for this to automate it.

~~~
$installpath="c:\profiling-tools\perfview"
New-Item -Path $Installpath -ItemType "directory"
Invoke-WebRequest https://github.com/microsoft/perfview/releases/download/P2.0.62/PerfView.exe -OutFile "$installpath\perfview.exe"
Invoke-WebRequest https://github.com/microsoft/perfview/releases/download/P2.0.62/PerfView64.exe -OutFile "$installpath\perfview64.exe"
~~~
