### ISSUE TITLE
EventPipe call stack logging

### ISSUE THREAD

**Issue by MendelMonteiro** [microsoft/perfview#1340]
I can see that it is possible to get call stacks associated with events from a `TraceLog` instance when it has been created by loading an EventPipe file however I would like to know if it is possible to do this with a real time `EventPipeEventSource` (i.e. without writing to a file)?

This would be equivalent functionality to using ETW with `TraceLog` + `TraceEventSession`.

**Comment by brianrob** [comment]
I don't believe that this is possible based on the existing code.  It is possible to create a real-time `EventPipeEventSource` and consume it, but `TraceLog` does not have a mechanism to consume it in real-time.  @josalem, do I have this correct?

**Comment by josalem** [comment]
You're correct, Brian.  There isn't a way to use the `TraceLog` API with a live EventPipe session from `EventPipeEventSource`.

**Comment by MendelMonteiro** [comment]
Thanks for the quick response.

Is this something that is on the roadmap?

**Comment by MendelMonteiro** [comment]
I'll assume that's a "no" ;-)

**Comment by vaind** [comment]
I've come here looking for the same as OP. Has there been any change in this regard in the meantime? Are there any workarounds (other than writing everything to file first? :) ) you know of?

**Comment by brianrob** [comment]
No changes that I'm aware of.  I would recommend filing an issue in https://github.com/dotnet/runtime, as I believe this will require runtime support first.
