### ISSUE TITLE
RelatedActivityIds no longer showing up in newer versions of perfview

### ISSUE THREAD

**Issue by davidmikh** [microsoft/perfview#1345]
This change seems to have been introduced in version 2.0.61 of perfview and is likely due to a change in TraceEvent since it seems to also occur in things that consume TraceEvent (such as Visual Studio).

Repro instructions:

Open the following diagsession in version 2.0.60 or older of perfview: [5.0session.zip](https://github.com/microsoft/perfview/files/5811518/5.0session.zip) (any file containing events with RelatedActivityIds in it will also work for this, the images here though are specific to that file)

Open the events and navigate to this event type: Microsoft-Diagnostics-DiagnosticSource/Activity2Start/Start

Observe how some of the events have RelatedActivityIds as shown below:

![hasRelatedActivityIds](https://user-images.githubusercontent.com/12531222/104523579-868fa580-55b3-11eb-95de-9c789f475a90.jpg)

Now open the same diagsession in version 2.0.61 or newer of perfview

Navigate to the same event type as before (Microsoft-Diagnostics-DiagnosticSource/Activity2Start/Start)

Observe how none of the events have RelatedActivityIds in the newer version of perfview

![noRelatedActivityIds](https://user-images.githubusercontent.com/12531222/104524241-b50d8080-55b3-11eb-8bdc-de173b2b3fc4.jpg)

**Comment by brianrob** [comment]
Thanks for reporting this @davidmikh.  I have posted #1346 to address this.
