### ISSUE TITLE
What does information does GC Heap Net Mem Stacks convey?

### ISSUE THREAD

**Issue by szarykott** [microsoft/perfview#1350]
Greetings!

I apologize if question I am about to ask has a trivial answer that I just missed, but I've spent over a week looking for the answer and it is still not clear for me.

I am trying to understand what information does view in Memory Group named GC Heap Net Mem Stacks (and its sampled version) present. I read PerfView user guide, browsed through issues on GitHub, [asked a question on StackOverflow](https://stackoverflow.com/questions/65636165/difference-between-views-in-perfview) and tried to reverse engineer it with sample application. And I failed.

According to documentation:
> Once you have the data [collected with .NET SampAlloc or .NET Alloc - reminder from me] you can view the data in the 'GC Heap Net Mem', which shows you the call stacks of all the allocations where the metric is bytes of GC Net GC heap.

The way I understand it, it should tell me how many bytes were allocated by a given type while PerfView was collecting trace.

To verify it I created a simple .NET Core 3.1 console application in C# that just allocates a known number of types of known size to verify PerfView information with it. You can find the code underneath.
```cs
using System;
using System.Diagnostics;

namespace Allocations.App
{
    class Program
    {
        private static int ByteArrayAllocations = 10_000_000;
        private static int StringAllocations = 20_000_000;
        
        static void Main(string[] args)
        {
            var stopwatch = Stopwatch.StartNew();
            
            var counter = 0;
            var arraySize = 345;
            for (int i = 0; i < ByteArrayAllocations; i++)
            {
                var bytes = new byte[arraySize];
                counter += Count(bytes);
            }
            
            for (int i = 0; i < StringAllocations; i++)
            {
                var word = new string[arraySize];
                counter += Count(word);
            }
            
            Console.WriteLine($"Done {counter} in {stopwatch.ElapsedMilliseconds} ms");
        }

        static int Count(byte[] bytes)
        {
            var counter = 0;
            for (int i = 0; i < bytes.Length; i++)
            {
                counter++;
            }

            return counter;
        }
        
        static int Count(string[] word)
        {
            var counter = 0;
            for (int i = 0; i < word.Length; i++)
            {
                counter++;
            }

            return counter;
        }
    }
}
```
Size of byte = 1.
Size of pointer = 8 (64bit OS)

I expect to see:
* 10_000_000 allocations of byte[] where total size of allocations should be 10_000_000 * 345 * 1 = 3 450 000 000 bytes
* 20_000_000 allocations of string[] where total size of allocations should be 20_000_000 * 345 * 8 = 55 200 000 000 bytes.

Results are unexpected.

I get two main types of views in Memory Group:
* GC Heap Alloc Ignore Free Stacks - this one gives me information I want as depicted below
![image](https://user-images.githubusercontent.com/32487860/105985929-79d37d00-609c-11eb-8b4e-5cbc156dc0ed.png)

Results are almost accurate. Version with coarse sampling is mistaken regarding object count, but is more less accurate with bytes allocated. This is unexpected as documentation does not even mention this view, whereas this is the one that gives results I expect.

* GC Heap Net Mem Stacks
![image](https://user-images.githubusercontent.com/32487860/105986120-bef7af00-609c-11eb-8e45-b21270445fb9.png)

I do not understand what is the exact information presented here. Despite the fact that indeed string[] is most commonly allocated type in my application, I cannot understand what information this view conveys as numbers presented do not correspond to anything and byte[] is gone. 

**So the question is - what is the exact information presented in GC Heap Net Mem Stacks?**

I will gladly submit a PR to documentation with explanation if you explain it to me!

I cannot attach attach ETL file from which I took screenshots because it is too big. If you do need it to answer, I can put it on some file hosting service for it to be accessible.

I am attaching zipped C# solution used to take the trace.
[Allocations.zip](https://github.com/microsoft/perfview/files/5879929/Allocations.zip)

**Comment by brianrob** [comment]
@szarykott, the GC Heap Net Mem Stacks views should show you net allocations, meaning that it will show you the allocations that were allocated and are still alive during the time range that you're looking at.  Allocations that have been unrooted and collected will not appear in this view because they are not part of the set of "net live allocations".

The non-coarse version of the view will show you all allocations, and so the numbers should be exact.  The coarse version will not be exact, as it uses allocation sampling.  The view does try to scale up the results to be closer to actual, but it isn't generally 100%, and so that would explain why you see close but not exact results.  In the coarse version, the size and count are based on the allocation quantum (100K), and not the size of the actual object, which is another factor that can make these results incorrect.  In general, the goal of the coarse version is to point you in the right direction, which it generally does, even though the results are not 100% accurate.

**Comment by szarykott** [comment]
@brianrob, thank you for the answer. I'll try to submit PR to enhance documentation with this information soon for future users!

**Comment by brianrob** [comment]
Sounds good, thanks @szarykott!

**Comment by szarykott** [comment]
Thank you for merging my PR. I am closing the issue as resolved :)
