### ISSUE TITLE
NullReferenceException opening IIS Stats

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/perfview#1366]
PerfView version: 2.0.65 (x86 and x64)

```text
Exception Occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at PerfView.PerfViewIisStats.WriteHtmlBody(TraceLog dataFile, TextWriter writer, String fileName, TextWriter log)
   at PerfView.PerfViewHtmlReport.GenerateReportFile(StatusBar worker, TraceLog trace)
   at PerfView.PerfViewHtmlReport.<>c__DisplayClass17_1.<Open>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
````

**Comment by brianrob** [comment]
@paulomorgado, can you share the trace where you saw this please?

**Comment by paulomorgado** [comment]
@brianrob, sent privately.

**Comment by paulomorgado** [comment]
The provided trace fails the following asserts:

https://github.com/microsoft/perfview/blob/main/src/TraceEvent/Parsers/SymbolTraceEventParser.cs#L548
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L4226
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2748
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2564
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2553
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2754
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2563
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/Parsers/KernelTraceEventParser.cs#L7030
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2255
https://github.com/microsoft/perfview/blob/main/src/TraceEvent/TraceLog.cs#L2264

The exception occurs at:

https://github.com/microsoft/perfview/blob/main/src/PerfView/PerfViewData.cs#L2131

Because the `Name` of `slowestPipelineEvent` is null at:

https://github.com/microsoft/perfview/blob/main/src/PerfView/PerfViewData.cs#L2130

Causing `slowestPipelineEvent.ToString()` to return `null`.

This caused by `slowestPipelineEvent` being initialized "empty" and a slowest event never being found.

Changing https://github.com/microsoft/perfview/blob/main/src/PerfView/PerfViewData.cs#L2131 to this, will solve this exception:

```CSharp
if (slowestPipelineEventDisplay != null && slowestPipelineEventDisplay.Length > 55)
```

This will cause the report to show:

| Method | Path | cs-bytes | sc-bytes | HttpStatus | Duration(ms) | Slowest Module | Time Spent In Slowest Module(ms) | %Time Spent In Slowest Module | Stack Traces |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| UNKNOWN | [Unkwown (GENERAL\_REQUEST\_START event not captured in trace)](command:detailedrequestevents:8003e58e-0401-e700-b63f-84710c7967bb;72376.4660937512;180879.344718124) | - | - | - | 108502.88 | GENERAL\_READ\_ENTITY | 0.01 | 0.00% | [Activity Stacks](command:activitystacks:36988;00000000-0000-0000-0000-000000000000;72376.4660937512;72376.4739706821) [Thread Time stacks](command:threadtimestacks:36988;51500;72376.4660937512;72376.4739706821) |
|  |

Maybe https://github.com/microsoft/perfview/blob/main/src/PerfView/PerfViewData.cs#L2491 should return `null` if no slowest event is found.

Either way, it's not  a good idea to unconditionally instantiate an instance of `IisPipelineEvent` and throw away most of the time.

A better design would be for `IisPipelineEvent` to be read-only and having an `Empty` static instance.
