### ISSUE TITLE
Automatic CPU Analysis: http://aka.ms/perfviewautoanalysis/unfairsemaphore.wait is not defined

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/perfview#1367]
The http://aka.ms/perfviewautoanalysis/unfairsemaphore.wait redirection is not defined.

**Comment by brianrob** [comment]
Yup, this is a known issue.  I've not yet created any of the aka.ms links in auto analysis yet, but this is on my list.

**Comment by paulomorgado** [comment]
It would be better to just point to a landing page with some "coming soon" message than having it go "nowhere".

**Comment by brianrob** [comment]
These are now marked as TBD.
