### ISSUE TITLE
Failed to run PerfView to collect ETW in windows container

### ISSUE THREAD

**Issue by northtyphoon** [microsoft/perfview#137]
Repro

1. Follow https://docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc to set up a windows container in WS2016 + IIS + ASP.NET
2. Launch a cmd in a new interactive session (eg, docker exec -it <container name> cmd)
3. Download PerfView if it's not the container. 
4. Run "PerfView collect /NoGui /MaxCollectSec:30 /LogFile:log.txt /AcceptEULA"

Error attached at the end. I'm not sure if it's currently a windows container restriction that blocks the kernel session. I haven't found any public document about it. Report the issue to track.

It worked if I collected only APS.NET events using "PerfView collect /NoGui /MaxCollectSec:30 /LogFile:log.txt /AcceptEULA /OnlyProviders:*Microsoft-Windows-ASPNET".

[EXECUTING: PerfView collect /NoGui /MaxCollectSec:30 /LogFile:log.txt /AcceptEULA]
Circular buffer size = 0, setting to 500.
[Kernel Log: C:\tools\PerfViewData.kernel.etl]
Kernel keywords enabled: Default
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
[Exception Occurred: System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.ExecuteCommand(CommandLineArgs parsedArgs)]

**Comment by vancem** [comment]
The operating system group is planning ETW support in windows containers late 2017.

**Comment by aelij** [comment]
@vancem Somewhat related to this, do you know if there's some way to read ETW events that were written inside a container (non-hyper-v) on the **host**? I tried and it didn't work (no errors).

**Comment by vancem** [comment]
@aelij I have forwarded your question to experts in ETW and asked them to reply.

**Comment by vancem** [comment]
Forwarding from Doug Cook on the OS team:

Question can you get at events generated by the processes in the container from the host?
```
In general, the answer is no. Data from a “provider running in a container context” will not show up in a host session, and this is by design. The intended way to capture these events is to start a session within the container.
```

**Comment by aelij** [comment]
Thanks @vancem.

I really wish this was configurable. ETW would've been be a great way to get logs out of containers.

**Comment by vancem** [comment]
Closing this issue, as we have support for Windows containers now.   
https://github.com/Microsoft/perfview/pull/393
https://github.com/Microsoft/perfview/pull/729

I updated the docs for this ether by searching the PerfView Users guide 

*  Using PerfView inside Windows Server (Docker) Containers 

Or by following this link 

http://htmlpreview.github.io/?https://github.com/Microsoft/perfview/blob/master/src/PerfView/SupportFiles/UsersGuide.htm#WindowsContainers

**Comment by brianrob** [comment]
Actually closing the issue.
