### ISSUE TITLE
Illegal characters in path when opening Thread Time with StartStop activities

### ISSUE THREAD

**Issue by stej** [Microsoft/perfview#138]
I collected some data with Perfview at Azure VM and tried to open that. CPU stacks are fine, no problem opening. Tried Thread Time  (with StartStop Activities) Stacks and nothing happened. Status bar shows "Illegal characters in path".

Log content after click on the stacks:
```
Started: Opening Thread Time (with StartStop Activities) Stacks
Symbol reader _NT_SYMBOL_PATH= {
    C:\Users\j.user\AppData\Local\Temp\PerfView;
    SRV*C:\Users\J8675~1.USR\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols;
    }
This can be set using the File -> Set Symbol Path dialog on the Stack Viewer.
Created SymbolReader with SymbolPath C:\Users\j.user\AppData\Local\Temp\PerfView;SRV*C:\Users\J8675~1.USR\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols
Warning: An activity was started that was not scheduled at 1 746,168  in process w3wp of kind IOThreadPool
...... repeated many times
Warning: An activity was started that was not scheduled at 1 786,695  in process w3wp of kind IOThreadPool
No code addresses are in mscorlib.ni that have not already been looked up.
[Loading symbols for d:\windows\assembly\nativeimages_v4.0.30319_32\mscorlib\d1265d6159ea876f9d63ea4c1361b587\mscorlib.ni.dll]
FindSymbolFilePath: *{ Locating PDB mscorlib.ni.pdb GUID d1265d61-59ea-876f-9d63-ea4c1361b587 Age 1 Version 4.0.30319.34209 built by: FX452RTMGDR
FindSymbolFilePath: Pdb is for DLL d:\windows\assembly\nativeimages_v4.0.30319_32\mscorlib\d1265d6159ea876f9d63ea4c1361b587\mscorlib.ni.dll
FindSymbolFilePath: Probed file location C:\Users\j.user\AppData\Local\Temp\PerfView\mscorlib.ni.pdb does not exist
FindSymbolFilePath: Found in cache C:\Users\J8675~1.USR\AppData\Local\Temp\symbols\mscorlib.ni.pdb\d1265d6159ea876f9d63ea4c1361b5871\mscorlib.ni.pdb
FindSymbolFilePath: *} Successfully found PDB C:\Users\J8675~1.USR\AppData\Local\Temp\symbols\mscorlib.ni.pdb\d1265d6159ea876f9d63ea4c1361b5871\mscorlib.ni.pdb GUID d1265d61-59ea-876f-9d63-ea4c1361b587 Age 1 Version 4.0.30319.34209 built by: FX452RTMGDR
Opening PDB C:\Users\J8675~1.USR\AppData\Local\Temp\symbols\mscorlib.ni.pdb\d1265d6159ea876f9d63ea4c1361b5871\mscorlib.ni.pdb with signature GUID d1265d61-59ea-876f-9d63-ea4c1361b587 Age 1
Opened Pdb file C:\Users\J8675~1.USR\AppData\Local\Temp\symbols\mscorlib.ni.pdb\d1265d6159ea876f9d63ea4c1361b5871\mscorlib.ni.pdb
Loaded, resolving symbols
Warning: NOT IN RANGE: address 0x27b040 start 2c7a54 end 2c7a70 Offset fffb35ec Len 1c, symbol System.GC.ReRegisterForFinalize(System.Object), prefixing with ??.
Warning: NOT IN RANGE: address 0x27b9a0 start 2c7a54 end 2c7a70 Offset fffb3f4c Len 1c, symbol System.GC.ReRegisterForFinalize(System.Object), prefixing with ??.
Warning: NOT IN RANGE: address 0x27ce47 start 2c7a54 end 2c7a70 Offset fffb53f3 Len 1c, symbol System.GC.ReRegisterForFinalize(System.Object), prefixing with ??.
    Addresses to look up       166
        Found Symbols          166
        Distinct Found Symbols 135
        Unmatched Symbols 0
Completed: Opening Thread Time (with StartStop Activities) Stacks   (Elapsed Time: 0,234 sec)
Error: Illegal characters in path.

```

**Comment by vancem** [comment]
Are you using V1.9 of PerfView?  I can't find something in the code base that would create the log that you show above.  

If you can publish the ETL.ZIP file that you used, I can download it and repro the problem.

**Comment by stej** [comment]
Yes, it's 1.9 

![image](https://cloud.githubusercontent.com/assets/253560/20167862/9358be8e-a71e-11e6-8054-db7dabbbac58.png)

**Comment by stej** [comment]
I also tried to open GC Heap Net Mem (Coarse Sampling) Stacks and got "Illegal characters...". And when trying to close the window, perfview reported unhandled exception.

```
StackTrace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PerfView.StackWindow.<FinishInit>b__207_1(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by vancem** [comment]
I looked in the delegate in FinishInit and found what is probably the null dereference (it is hard to really know for sure given the information we have).    I will be incorporating that into the next release.   

However the Null ref is certainly unrelated to your original problem.  

You could send me the .etl.zip file securely by uploading to some cloud storage (e.g. OneDrive or equivalent), and send me the access URL (vancem@microsoft.com).   

It is also likely that the following will work OK.  Simply run a 'PerfView collect' while you are running the other instance of PerfView.  All PerfView collections include exceptions (with stack traces), do we will get a very nice stack trace where the File API was called from (see the 'Exceptions Stacks' view).  

You could mail me the stack (or better publish the *.etl.zip file (which does not have private info in it).  

You can also run PerfView under control of a debugger, and set the debugger to stop on exceptions, this will stop you in the right place (there may one or more exceptions that are 'expected' before you get to the one you care about).   This has the advantage of showing you the path.

**Comment by stej** [comment]
Downloaded PerfView src, built in Debug and started Debugging. During load of the etl file there was an assert in TraceEvent at

1)  
```
Debug.Assert(false, "The template " + methodName +
" for the parser " + typeName +
" for provider " + provider +
" exists in EnumerateTemplates enumeration but not as a C# event, please add it.");
```
typeName: Microsoft.Diagnostics.Tracing.Parsers.KernelTraceEventParser
methodName: MemInfo
provider: "Windows Kernel

2) 
```
Debug.Assert(false, "The C# event " + methodName +
" for the parser " + typeName +
" for provider " + provider +
" does NOT exist in the EnumerateTemplates enumeration, please add it.");
```
methodName: MemoryMemInfo
typeName: Microsoft.Diagnostics.Tracing.Parsers.KernelTraceEventParser
provider: Windows Kernel

3)
then during loading the ETL file there is a lot of asserts, but not sure whether it's problem or not

4) when opening Thread Time (stacks), there are additional asserts in TraceEvent like in (1) and (2)
`if (0 < enumSet.Count)` - Count = 255
`if (0 < declaredSet.Count)` - Count = 394
I guess it's because it's running on Azure VM and there is bunch of unregistered providers in PerfView.

The provider is ""Microsoft-Windows-Application Server-Applications". Some of the events: 
methodName: "WorkflowInstanceRecordWithId", 
methodName: "WorkflowInstanceSuspendedRecord", 
methodName: "WorkflowInstanceSuspendedRecordWithId", 
methodName: "WorkflowInstanceTerminatedRecord", 
methodName: "WorkflowInstanceTerminatedRecordWithId", 
methodName: "WorkflowInstanceUnhandledExceptionRecord", 
methodName: "WorkflowInstanceUnhandledExceptionRecordWithId", 
methodName: "WorkflowInstanceUpdatedRecord", 
methodName: "WrappedKeyDecryptionStart", 
methodName: "WrappedKeyDecryptionSuccess", 
methodName: "WritePoolMiss", 
..............

**Comment by stej** [comment]
The cause of the exception is this:

stacktrace:
```
 	mscorlib.dll!System.IO.Path.GetFileName(string path)	Unknown
>	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.Etlx.TraceModuleFile.Name.get() Line 8317	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ActivityComputer.ResolveWellKnownSymbols() Line 1106	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ActivityComputer.TrimETWFrames(Microsoft.Diagnostics.Tracing.Etlx.CallStackIndex callStackIndex) Line 957	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ActivityComputer.GetCallStackWithActivityFrames(Microsoft.Diagnostics.Tracing.Etlx.CallStackIndex baseStack, Microsoft.Diagnostics.Tracing.Etlx.TraceActivity activity, System.Func<Microsoft.Diagnostics.Tracing.Etlx.TraceThread, Microsoft.Diagnostics.Tracing.Stacks.StackSourceCallStackIndex> topFrames) Line 904	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ActivityComputer.GetCallStack(Microsoft.Diagnostics.Tracing.Stacks.MutableTraceEventStackSource outputStackSource, Microsoft.Diagnostics.Tracing.TraceEvent data, System.Func<Microsoft.Diagnostics.Tracing.Etlx.TraceThread, Microsoft.Diagnostics.Tracing.Stacks.StackSourceCallStackIndex> topFrames, bool trimEtwFrames) Line 311	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GetCallStack(Microsoft.Diagnostics.Tracing.TraceEvent data, Microsoft.Diagnostics.Tracing.Etlx.TraceThread thread) Line 648	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.OnSampledProfile(Microsoft.Diagnostics.Tracing.TraceEvent data) Line 544	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.Parsers.Kernel.SampledProfileTraceData.Dispatch() Line 8790	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(Microsoft.Diagnostics.Tracing.TraceEvent anEvent) Line 2917	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.Etlx.TraceLogEventSource.Process() Line 3508	C#
 	Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateThreadTimeStacks(Microsoft.Diagnostics.Tracing.Stacks.MutableTraceEventStackSource outputStackSource, Microsoft.Diagnostics.Tracing.Etlx.TraceEvents traceEvents) Line 323	C#
 	PerfView.exe!PerfView.ETLPerfViewData.OpenStackSourceImpl(string streamName, System.IO.TextWriter log, double startRelativeMSec, double endRelativeMSec, System.Predicate<Microsoft.Diagnostics.Tracing.TraceEvent> predicate) Line 2703	C#
 	PerfView.exe!PerfView.PerfViewStackSource.OpenStackSource(string streamName, System.IO.TextWriter log, double startRelativeMSec, double endRelativeMSec, System.Predicate<Microsoft.Diagnostics.Tracing.TraceEvent> predicate) Line 2349	C#
 	PerfView.exe!PerfView.PerfViewStackSource.Open.AnonymousMethod__0() Line 2367	C#
 	PerfView.exe!PerfView.StatusBar.StartWork.AnonymousMethod__0(object <state>) Line 216	C#
```

FilePath  = "
....REMOVEDactionprocessing.iactioninputtable<REMOVED.actions.blobsizescollecting.blobsizescollectinginput>"
(there were some sensitive information, replaced with REMOVED)

**This has probably something to do with dynamically generated code. The code in perfview assumes that there is always some path to disk, but this is not true for dynamic assemblies. Sadly our assembly has `<` and `>` in the name and that's causing problems for `IO.Path` when getting file name.**

**Comment by vancem** [comment]
Thanks.  I have checked a fix that should avoid the issue

c58c950d 	Fix bug where 'illegal Chars' exception is thrown in cases where dynamic assemblies have non-Windows file names.  

You can build PerfView yourself, or send me mail at vancem@microsoft.com and I will send you a rebuilt version.

**Comment by stej** [comment]
Thank you, I'll build it by myself.
