### ISSUE TITLE
"The specified module could not be found" (versions > 2.0.62)

### ISSUE THREAD

**Issue by Lombra** [microsoft/perfview#1387]
The following application throws a Win32Exception "The specified module could not be found" at `EnableKernelProvider`.
```cs
static void Main(string[] args) {
	using var session = new TraceEventSession(KernelTraceEventParser.KernelSessionName);
	session.EnableKernelProvider(KernelTraceEventParser.Keywords.Process);
}
```
Version 2.0.62 works. 2.0.64 through 2.0.66 do not.

Windows 7 64 bit. .NET 5.0.

**Comment by brianrob** [comment]
Bulk closing issues.  Please re-open if needed.
