### ISSUE TITLE
GC Rollup By Generation report generates negative numbers for "Total Alloc MB"

### ISSUE THREAD

**Issue by jstranik** [microsoft/perfview#1390]
I would not have expected a negative numbers in the "Total Alloc MB" column in the summary GC Stats report. 

GC Rollup By Generation
--

ALL | 256 | 4.7 | 536.0 | 10,129.029 | 97.5 | 6,111.6 | 62.7 | ∞ | 0.4 | 0
0 | 235 | 4.6 | 536.0 | 10,129.029 | 55.1 | 8,917.8 | 0.0 | ∞ | 0.2 | 0
1 | 1 | 4.7 | 205.5 | 0.000 | 4.7 | -426.2 | 0.0 | ∞ | 4.7 | 0
2 | 20 | 3.8 | 536.0 | 9,998.753 | 37.7 | -2,380.0 | 0.0 | ∞ | 1.9 | 0

**Comment by brianrob** [comment]
Bulk closing issues.  Please re-open if needed.
