### ISSUE TITLE
Bad trace from Windows Container

### ISSUE THREAD

**Issue by vdvarlamov** [microsoft/perfview#1393]
I have .Net Core application run in windows container. I run command from container: _PerfView.exe /nogui /accepteula /NoView /Zip:TRUE /Merge:TRUE /logFile=log.txt /TrustPdbs /MaxCollectSec:30 collect .\PerfViewData.etl.zip_
After i copy _PerfViewData.etl.zip_ on node, where the container is running and opening trace in PerfView GUI.
In logs,i see many WARNING below.
Hence, I get a bad trace, with unknown modules.
![image](https://user-images.githubusercontent.com/47747798/111790336-2549c280-88d3-11eb-96e2-40742b325546.png)

It looks like the problem lies in the shared dlls with the host.
If i run the application on the host and take the trace, everything is fine.
Tell me how to properly capture the trace from the container and then read it?

> WARNING: The log file does not contain exact PDB signature information for c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\clrjit.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\clrjit.dll
Could not find PDB file.
[Quick lookup of coreclr]
[Loading symbols for c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll]
No PDB signature for c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll in trace.
The file c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll does not exist on the local machine
Attempting to convert c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll to a volume-based path in case the file inside of a container.
Successfully converted to \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll.
FindSymbolFilePathForModule: searching for PDB for DLL \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll.
FindSymbolFilePath: *{ Locating PDB F:\workspace\_work\1\s\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\Release\coreclr.pdb GUID 7e9cb043-cd92-4496-8f8c-ff7a869dc737 Age 1 Version 4,700,20,51601 @Commit: d989459717cbce34262060c4b8b949185033e379
FindSymbolFilePath: Pdb is for DLL \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll
FindSymbolFilePath: Checking relative to DLL path \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll
FindSymbolFilePath: Probed file location \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.pdb does not exist
FindSymbolFilePath: Probed file location \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\symbols.pri\retail\dll\coreclr.pdb does not exist
FindSymbolFilePath: Probed file location \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\symbols\retail\dll\coreclr.pdb does not exist
FindSymbolFilePath: Probed file location F:\workspace\_work\1\s\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\Release\coreclr.pdb does not exist
FindSymbolFilePath: Probed file location C:\tmp\coreclr.pdb does not exist
FindSymbolFilePath: no file at cache location C:\Users\bear\AppData\Local\Temp\2\SymbolCache\coreclr.pdb\7E9CB043CD9244968F8CFF7A869DC7371\coreclr.pdb and cacheOnly set, giving up.
FindSymbolFilePath: *} Failed to find PDB coreclr.pdb in local cache GUID 7e9cb043-cd92-4496-8f8c-ff7a869dc737 Age 1 Version 4,700,20,51601 @Commit: d989459717cbce34262060c4b8b949185033e379
FindSymbolFilePathForModule returns NULL for F:\workspace\_work\1\s\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\Release\coreclr.pdb 7e9cb043-cd92-4496-8f8c-ff7a869dc737 1 4,700,20,51601 @Commit: d989459717cbce34262060c4b8b949185033e379
WARNING: The log file does not contain exact PDB signature information for c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\device\harddiskvolume4\programdata\docker\windowsfilter\44bde83a39bda06ded80a93090beee24380871b755c5b47dfd4818b558ddefbc\files\program files\dotnet\shared\microsoft.netcore.app\3.1.10\coreclr.dll
Could not find PDB file.
[Quick lookup of schannel]
[Loading symbols for c:\windows\system32\schannel.dll]
No PDB signature for c:\windows\system32\schannel.dll in trace.
The local file C:\Windows\Sysnative\schannel.dll has a mismatched checksum found 522738 != expected 528669
Attempting to convert c:\windows\system32\schannel.dll to a volume-based path in case the file inside of a container.
Unable to convert c:\windows\system32\schannel.dll to a volume-based path.
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\windows\system32\schannel.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\windows\system32\schannel.dll
Could not find PDB file.
[Quick lookup of rpcrt4]
[Loading symbols for c:\windows\system32\rpcrt4.dll]
No PDB signature for c:\windows\system32\rpcrt4.dll in trace.
The local file C:\Windows\Sysnative\rpcrt4.dll has a mismatched checksum found 1202380 != expected 1201801
Attempting to convert c:\windows\system32\rpcrt4.dll to a volume-based path in case the file inside of a container.
Unable to convert c:\windows\system32\rpcrt4.dll to a volume-based path.
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\windows\system32\rpcrt4.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\windows\system32\rpcrt4.dll
Could not find PDB file.
[Quick lookup of kernelbase]
[Loading symbols for c:\windows\system32\kernelbase.dll]
No PDB signature for c:\windows\system32\kernelbase.dll in trace.
The local file C:\Windows\Sysnative\kernelbase.dll has a mismatched checksum found 2755989 != expected 2720513
Attempting to convert c:\windows\system32\kernelbase.dll to a volume-based path in case the file inside of a container.
Unable to convert c:\windows\system32\kernelbase.dll to a volume-based path.
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\windows\system32\kernelbase.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\windows\system32\kernelbase.dll
Could not find PDB file.
[Quick lookup of advapi32]
[Loading symbols for c:\windows\system32\advapi32.dll]
No PDB signature for c:\windows\system32\advapi32.dll in trace.
FindSymbolFilePathForModule: searching for PDB for DLL c:\windows\system32\advapi32.dll.
FindSymbolFilePath: *{ Locating PDB advapi32.pdb GUID 51d14697-a7f5-875e-2510-c3bda4e61b61 Age 1 Version 10.0.17763.1131 (WinBuild.160101.0800)
FindSymbolFilePath: Pdb is for DLL C:\Windows\Sysnative\advapi32.dll
FindSymbolFilePath: Checking relative to DLL path C:\Windows\Sysnative\advapi32.dll
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\advapi32.pdb does not exist
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\symbols.pri\retail\dll\advapi32.pdb does not exist
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\symbols\retail\dll\advapi32.pdb does not exist
FindSymbolFilePath: Probed file location C:\tmp\advapi32.pdb does not exist
FindSymbolFilePath: no file at cache location C:\Users\bear\AppData\Local\Temp\2\SymbolCache\advapi32.pdb\51D14697A7F5875E2510C3BDA4E61B611\advapi32.pdb and cacheOnly set, giving up.
FindSymbolFilePath: *} Failed to find PDB advapi32.pdb in local cache GUID 51d14697-a7f5-875e-2510-c3bda4e61b61 Age 1 Version 10.0.17763.1131 (WinBuild.160101.0800)
FindSymbolFilePathForModule returns NULL for advapi32.pdb 51d14697-a7f5-875e-2510-c3bda4e61b61 1 10.0.17763.1131 (WinBuild.160101.0800)
Attempting to convert c:\windows\system32\advapi32.dll to a volume-based path in case the file inside of a container.
Unable to convert c:\windows\system32\advapi32.dll to a volume-based path.
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\windows\system32\advapi32.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\windows\system32\advapi32.dll
Could not find PDB file.
[Quick lookup of bcryptprimitives]
[Loading symbols for c:\windows\system32\bcryptprimitives.dll]
No PDB signature for c:\windows\system32\bcryptprimitives.dll in trace.
FindSymbolFilePathForModule: searching for PDB for DLL c:\windows\system32\bcryptprimitives.dll.
FindSymbolFilePath: *{ Locating PDB bcryptprimitives.pdb GUID 8047eeeb-d29f-83d8-993d-0bf3f8f3ad48 Age 1 Version 10.0.17763.1613 (WinBuild.160101.0800)
FindSymbolFilePath: Pdb is for DLL C:\Windows\Sysnative\bcryptprimitives.dll
FindSymbolFilePath: Checking relative to DLL path C:\Windows\Sysnative\bcryptprimitives.dll
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\bcryptprimitives.pdb does not exist
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\symbols.pri\retail\dll\bcryptprimitives.pdb does not exist
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\symbols\retail\dll\bcryptprimitives.pdb does not exist
FindSymbolFilePath: Probed file location C:\tmp\bcryptprimitives.pdb does not exist
FindSymbolFilePath: no file at cache location C:\Users\bear\AppData\Local\Temp\2\SymbolCache\bcryptprimitives.pdb\8047EEEBD29F83D8993D0BF3F8F3AD481\bcryptprimitives.pdb and cacheOnly set, giving up.
FindSymbolFilePath: *} Failed to find PDB bcryptprimitives.pdb in local cache GUID 8047eeeb-d29f-83d8-993d-0bf3f8f3ad48 Age 1 Version 10.0.17763.1613 (WinBuild.160101.0800)
FindSymbolFilePathForModule returns NULL for bcryptprimitives.pdb 8047eeeb-d29f-83d8-993d-0bf3f8f3ad48 1 10.0.17763.1613 (WinBuild.160101.0800)
Attempting to convert c:\windows\system32\bcryptprimitives.dll to a volume-based path in case the file inside of a container.
Unable to convert c:\windows\system32\bcryptprimitives.dll to a volume-based path.
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\windows\system32\bcryptprimitives.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\windows\system32\bcryptprimitives.dll
Could not find PDB file.
[Quick lookup of kernel32]
[Loading symbols for c:\windows\system32\kernel32.dll]
No PDB signature for c:\windows\system32\kernel32.dll in trace.
FindSymbolFilePathForModule: searching for PDB for DLL c:\windows\system32\kernel32.dll.
FindSymbolFilePath: *{ Locating PDB kernel32.pdb GUID 07efa046-5afb-4214-cbd5-328b0b5ed084 Age 1 Version 10.0.17763.475 (WinBuild.160101.0800)
FindSymbolFilePath: Pdb is for DLL C:\Windows\Sysnative\kernel32.dll
FindSymbolFilePath: Checking relative to DLL path C:\Windows\Sysnative\kernel32.dll
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\kernel32.pdb does not exist
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\symbols.pri\retail\dll\kernel32.pdb does not exist
FindSymbolFilePath: Probed file location C:\Windows\Sysnative\symbols\retail\dll\kernel32.pdb does not exist
FindSymbolFilePath: Probed file location C:\tmp\kernel32.pdb does not exist
FindSymbolFilePath: no file at cache location C:\Users\bear\AppData\Local\Temp\2\SymbolCache\kernel32.pdb\07EFA0465AFB4214CBD5328B0B5ED0841\kernel32.pdb and cacheOnly set, giving up.
FindSymbolFilePath: *} Failed to find PDB kernel32.pdb in local cache GUID 07efa046-5afb-4214-cbd5-328b0b5ed084 Age 1 Version 10.0.17763.475 (WinBuild.160101.0800)
FindSymbolFilePathForModule returns NULL for kernel32.pdb 07efa046-5afb-4214-cbd5-328b0b5ed084 1 10.0.17763.475 (WinBuild.160101.0800)
Attempting to convert c:\windows\system32\kernel32.dll to a volume-based path in case the file inside of a container.
Unable to convert c:\windows\system32\kernel32.dll to a volume-based path.
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\windows\system32\kernel32.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\windows\system32\kernel32.dll
Could not find PDB file.
[Quick lookup of ntdll]
[Loading symbols for c:\device\harddiskvolume4\windows\system32\ntdll.dll]
No PDB signature for c:\device\harddiskvolume4\windows\system32\ntdll.dll in trace.
The file c:\device\harddiskvolume4\windows\system32\ntdll.dll does not exist on the local machine
Attempting to convert c:\device\harddiskvolume4\windows\system32\ntdll.dll to a volume-based path in case the file inside of a container.
Successfully converted to \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\ntdll.dll.
FindSymbolFilePathForModule: searching for PDB for DLL \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\ntdll.dll.
FindSymbolFilePath: *{ Locating PDB ntdll.pdb GUID b77a183b-bc51-3b94-1db6-2f7e5a4bd20b Age 1 Version 10.0.17763.1728 (WinBuild.160101.0800)
FindSymbolFilePath: Pdb is for DLL \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\ntdll.dll
FindSymbolFilePath: Checking relative to DLL path \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\ntdll.dll
FindSymbolFilePath: Probed file location \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\ntdll.pdb does not exist
FindSymbolFilePath: Probed file location \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\symbols.pri\retail\dll\ntdll.pdb does not exist
FindSymbolFilePath: Probed file location \\?\Volume{83da0a50-7e7c-4f96-aea2-704a62a09d62}\windows\system32\symbols\retail\dll\ntdll.pdb does not exist
FindSymbolFilePath: Probed file location C:\tmp\ntdll.pdb does not exist
FindSymbolFilePath: no file at cache location C:\Users\bear\AppData\Local\Temp\2\SymbolCache\ntdll.pdb\B77A183BBC513B941DB62F7E5A4BD20B1\ntdll.pdb and cacheOnly set, giving up.
FindSymbolFilePath: *} Failed to find PDB ntdll.pdb in local cache GUID b77a183b-bc51-3b94-1db6-2f7e5a4bd20b Age 1 Version 10.0.17763.1728 (WinBuild.160101.0800)
FindSymbolFilePathForModule returns NULL for ntdll.pdb b77a183b-bc51-3b94-1db6-2f7e5a4bd20b 1 10.0.17763.1728 (WinBuild.160101.0800)
WARNING: could not find PDB signature of a 64 bit OS DLL.  Did you collect with a 32 bit version of XPERF?

> WARNING: The log file does not contain exact PDB signature information for c:\device\harddiskvolume4\windows\system32\ntdll.dll and the file at this path is not the file used in the trace.
PDB files cannot be unambiguously matched to the EXE.
Did you merge the ETL file before transferring it off the collection machine?  If not, doing the merge will fix this.
The /UnsafePdbMatch option will force an ambiguous match, but this is not recommended.
Failed to find PDB for c:\device\harddiskvolume4\windows\system32\ntdll.dll
Could not find PDB file.
Completed: Looking up high importance PDBs that are locally cached   (Elapsed Time: 0.094 sec)

**Comment by brianrob** [comment]
A couple of questions on this:
 - What kind of container did you run this in (process isolation container or Hyper-V container)?
 - What OS image did you base your container on?

**Comment by vdvarlamov** [comment]
- mcr.microsoft.com/windows/servercore:ltsc2019 (process isolation)
- Windows Server 2019 Std

**Comment by brianrob** [comment]
Thanks.  Can you try running `PerfView.exe merge <path\to\etl> -ImageIDsOnly` on the host, and see if that solves the problem.  There are some access issues between the host and process isolation containers specifically that often require that you merge the trace both on the host and inside the container.

**Comment by brianrob** [comment]
Nothing immediately jumps out at me as an issue.  That said, this area has some complexity as we're dealing with two somewhat isolated systems (the host and the container).

As a path forward, I would recommend that you diff the traces that you've taken when running the app inside the container and on the host.  This should help us to understand which modules are not being resolved when you run inside the container.  That will hopefully help me to understand what might be happening.

In case you're not familiar with the diffing capabilities of PerfView, here are some instructions to get you started:
1. Open both traces in a single instance of PerfView.
2. Open the stack view from each trace and filter it to the equivalent process and work for each trace.
3. In the window with the missing symbols, select the Diff menu at the top, and choose the other stack view as the baseline.

Assuming that the work done in both traces was equivalent, the missing symbols will show up at the top with a positive cost in the `Exc` column.  Below that, you'll see negative cost for the modules and symbols that likely represent the missing symbols, and hopefully they will add up to somewhere near the cost of the missing symbols.

Feel free to also share the traces with me, and I can take a look.  The key here is to make sure that the traces represent equivalent work.

**Comment by vdvarlamov** [comment]
> Feel free to also share the traces with me, and I can take a look. The key here is to make sure that the traces represent equivalent work.

The inspect process name - _WebApplication1_.
[PerfViewData_from_host.etl.zip](https://github.com/microsoft/perfview/files/6203525/PerfViewData_from_host.etl.zip)
[PerfViewData_without_ImageIDOnly_from_container.etl.zip](https://github.com/microsoft/perfview/files/6203535/PerfViewData_without_ImageIDOnly_from_container.etl.zip)
[PerfViewData_with_ImageIDOnly_from_container.etl.zip](https://github.com/microsoft/perfview/files/6203539/PerfViewData_with_ImageIDOnly_from_container.etl.zip)
Thanks!

**Comment by vdvarlamov** [comment]
@brianrob , are there any ideas for the provided traces?

**Comment by vdvarlamov** [comment]
@brianrob , hello, can I hope for your help?

**Comment by brianrob** [comment]
Coming back to this issue.  There have been a number of fixes in this area.  I recommend retrying this with the latest version of PerfView.  I'm going to close this issue and if needed, please re-open.
