### ISSUE TITLE
Questions about NetTrace format

### ISSUE THREAD

**Issue by noahfalk** [microsoft/perfview#1396]
@TrayanZapryanov originally wrote this this in [another issue](https://github.com/microsoft/perfview/issues/1267#issuecomment-808769048) and I moved it here:

I am sorry, if this is not the correct place to ask a question.
We built a custom UI over Microsoft.Diagnostics.Tracing.TraceEvent nuget and it works fine until we moved our service in Linux Azure App Service. Following guide in section in How to leverage dotnet-trace in App Services Linux we are able to produce nettrace file. And the questions are:
Is it possible to replay this type like normal ETL file ?
Is there a way to convert from nettrace to ETL?
What is your advice for a solution to our problem ?

Thank you in advance.

**Comment by noahfalk** [comment]
> Is it possible to replay this type like normal ETL file ?

nettrace files can be read by the TraceEvent library by creating an [EventPipeEventSource](https://github.com/microsoft/perfview/blob/main/src/TraceEvent/EventPipe/EventPipeEventSource.cs#L29). If you are using Perfview nettrace files can be opened in the UI identically to .etl files.

> Is there a way to convert from nettrace to ETL?

You might be able to convert it to .etlx using [this API](https://github.com/microsoft/perfview/blob/f460b42b61bd72affa01a5f7792b1b8f7bb4bfaf/src/TraceEvent/TraceLog.cs#L77) but I have never investigated it. TraceEvent doesn't provide any support to write out the .etl format that I am aware of but with effort I assume something like that could be built.

> We built a custom UI over Microsoft.Diagnostics.Tracing.TraceEvent nuget and it works fine until we moved our service in Linux Azure App Service ... What is your advice for a solution to our problem ?

If you were previously creating `new ETWTraceEventSource("foo.etl")`, replace that constructor with `new EventPipeEventSource("foo.nettrace")`. If your previous code wasn't directly using ETWTraceEventSource or you are running into other trouble you may need to provide a little more detail what APIs your current code is calling so we can get you pointed in the right direction : )

Hope that helps!

**Comment by TrayanZapryanov** [comment]
@noahfalk Thank you for the great help.
Your suggestion works fine and I was able to read the data.
There is one minor change between these 2 types of loading : TraceEvent.FormattedMessage is null in case of nettrace.
I've made some adjustments in our UI and it looks pretty close to previous state.

**Comment by noahfalk** [comment]
Glad it worked well for you! The nettrace serialization format doesn't currently support storing the formatted message string so the null there is expected. Its something I'd like to improve in the future.
