### ISSUE TITLE
ForceGC throws errors: "The GUID passed was not recognized as valid by a WMI data provider. (Exception from HRESULT: 0x80071068)"

### ISSUE THREAD

**Issue by bigbearzhu** [Microsoft/perfview#142]
I was trying to use PerfView to force GC on a process as suggested by http://stackoverflow.com/a/26033289/1837339, however, it seems not working and I got an error like this:

```
Loading the ETWClrProfiler.
Turning on debug privilege.
Highest Runtime in process is version v4.0.30319
  0.0s: Trying to attach a profiler.
  0.0s: Done Attaching ETLClrProfiler ret = 0
Attached ETWClrProfiler.
  0.1s: Enabling JScript Heap Provider
  0.1s: Enabling EtwClrProfiler
  0.1s: Enabling CLR GC events
  0.1s: Requesting a JScript GC
  0.1s: Requesting a DotNet GC
  0.1s: Requesting .NET Native GC
HeapDump Error: System.Runtime.InteropServices.COMException (0x80071068): The GUID passed was not recognized as valid by a WMI data provider. (Exception from HRESULT: 0x80071068)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.CaptureState(Guid providerGuid, UInt64 matchAnyKeywords, Int32 filterType, Object data)
   at GCHeapDumper.TriggerAllGCs(TraceEventSession session, Stopwatch sw, Int32 processID)
   at GCHeapDumper.ForceGC(Int32 processID)
   at Program.MainWorker(String[] args)
```

Any idea what could be causing the issue? Thanks.

**Comment by bigbearzhu** [comment]
However, I found that the issue doesn't appear when I build the HeapDump.exe locally with latest code from master branch. It seems only happen on the version 1.9.0 I downloaded from https://www.microsoft.com/en-au/download/details.aspx?id=28567

**Comment by dmsergeev** [comment]
I have the same problem with PerfView downloaded from the link pasted above.

**Comment by matsydoodles** [comment]
Getting the latest compiled version from this site worked for me.

**Comment by vancem** [comment]
I am closing this as it does not seem to reproducible from the current source 

Note that you can get built binaries of PerfView from https://github.com/Microsoft/perfview/releases 

We will update the download center, but probably not for a few months yet.
