### ISSUE TITLE
empty cpu stacks when following tutorial

### ISSUE THREAD

**Issue by dcatteeu** [microsoft/perfview#1438]
I just tried out the tutorial but end up with empty CPU stacks: every process seemingly spent 0 ms.

I did the following:
1. download perfview.exe and start it
2. select "Collect", then "Run"
3. grant admin rights
4. enter "Tutorial.exe" in "Command" field
5. click "Run command"
6. wait ~30seconds
7. select "CPU stacks"

There seem to be ~100K events, but the CPU stacks are empty. 

There's a warning in the log about a missing PDB file, but I don't immediately see an error.

What am I missing here? I am new to perfview.

The log file is attached. I'll gladly provide any extra details.
[perfview_tutorial.txt](https://github.com/microsoft/perfview/files/6568188/perfview_tutorial.txt)

**Comment by EgorBo** [comment]
@dcatteeu do you by any chance have Intel VTune installed in your system?
I had the same empty callstacks recently and fixed it by uninstalling VTune.

**Comment by dcatteeu** [comment]
@EgorBo : No, I don't, but thank you for sharing your experience

I tried the same thing on another machine and had no issue (except for some broken stacks), so I conclude there could be something on my machine that breaks it.

**Comment by brianrob** [comment]
Does this persist if you reboot?  I am working to get eyes on this issue.

**Comment by dcatteeu** [comment]
Yes it does.

Thank you for having a look, Brian. Let me know if I can provide extra input.

**Comment by dcatteeu** [comment]
Some additional info:

When I collect CPU usage in Visual Studio (as in Step 1 of https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling?view=vs-2019) I have a similar issue to the one described here: https://developercommunity.visualstudio.com/t/profiling-cpu-still-states-no-user-code-was-runnin/607535. There is no CPU usage data at the end of the collection.

It seems like this is rather an ETW issue, than a PerfView issue, no? Would there be a better place to report this?What kind of software would prevent ETW from working correctly?

BTW, I'm on a brand new laptop.

**Comment by dcatteeu** [comment]
I found a work around on Stack Exchange: https://stackoverflow.com/a/62793971/3855204

If I disable my Nvidia card in device manager and reboot, all is fine...

**Comment by brianrob** [comment]
Yes, @dcatteeu, this is an ETW issue.  You could file an issue in the Feedback Hub, and that would get routed to the right team.  I am also working with the folks who are engaged on looking at this.  Thanks for confirming that you were able to work around this.

**Comment by brianrob** [comment]
Bulk closing old issues.
