### ISSUE TITLE
Hide Utilities namespace

### ISSUE THREAD

**Issue by andkamashev** [microsoft/perfview#1448]
Lots of devs has Utilities static class(es) in project and after installing this nuget all calls of methods like Utilities.Sum(228,1488) throw error on compilation. It is quite easy to fix, but not if you have hundreds of projects.

**Comment by brianrob** [comment]
From a quick look at the Utilities namespace, it looks like this would not change any public surface area.  Would you be interested in submitting a PR to merge the Utilities namespace with Microsoft.Diagnostics.Utilities?

**Comment by andkamashev** [comment]
Sure, it will be nice, anything except global Utilities namespace will be perfect

**Comment by JpWebster** [comment]
Any chance of getting these namespaces cleaned up, we are hitting this same issue as https://github.com/microsoft/perfview/issues/1049

**Comment by brianrob** [comment]
Fixed via #1805.
