### ISSUE TITLE
Question: Does Perfview have support for source files  included via EmbedAllSources

### ISSUE THREAD

**Issue by Xhanti** [microsoft/perfview#1487]
Hi,

I logged this [here](https://github.com/microsoft/perfview/discussions/1483), which might be the wrong place., adding here as well. 

In addition to source link support, does perfview support getting source code from a dll where the source code has been embedded in the dll via EmbedAllSources? If not what might it take to include such support? I would like to take a look at that, if it does not support it.
In addition can it also find embedded pdb's?

**Comment by brianrob** [comment]
@Xhanti, I have not done any specific work to support this, so I doubt that it does work.  Embedded PDBs might work, but I would need to test that.  I don't know what would be required to support either of these - first step here is likely an investigation.

**Comment by Xhanti** [comment]
Thank you

**Comment by pharring** [comment]
There is tooling to support reading Source Link information from symbols:
NuGet: https://www.nuget.org/packages/Microsoft.SourceLink.Tools/
Source: https://github.com/dotnet/sourcelink/tree/main/src/SourceLink.Tools

**Comment by Xhanti** [comment]
@pharring thank you for the response. We are forced to rely on embedded sources since we use an on premise gitlab instance and source link does not work for us without a proxy in the middle see (https://github.com/dotnet/sourcelink/issues/135) so we loading sources does not work us at the moment. VS does this right, so I was hoping perfview had support for it
