### ISSUE TITLE
Update perfview on download center

### ISSUE THREAD

**Issue by danmosemsft** [microsoft/perfview#149]
Using the one of download center which is from July I hit some failure loading symbols. Cloning and building the latest fixed the problem. @safern hit the same issue. It would be nice to update the one on download center.

**Comment by gholliday** [comment]
I am also waiting for the latest version on the download center.

**Comment by vancem** [comment]
Just FYI, you can get binary of PerfView from

https://github.com/Microsoft/perfview/releases

**Comment by brianrob** [comment]
PerfView binary releases are now delivered via GitHub releases.
