### ISSUE TITLE
Add more safe Event Types filter

### ISSUE THREAD

**Issue by victorklimkovich** [microsoft/perfview#150]
Make two lists Event types.
* First All event types
* Second Displayed Event types
It's more safe to use such filter, because selection in list box easy to corrupt
![perfview_eventtypefilter](https://cloud.githubusercontent.com/assets/16319233/21933008/87aa4526-d9b4-11e6-809e-e2ba0f4d3513.png)

**Comment by vancem** [comment]
For what it is worth, what I typically do is use the 'Filter' to cut down the events to ones that I am interested in choosing.   Note that the | operator is pretty useful here.   For example 

DWMDraw|Process/

Might get me the events with DWMDraw and Process start and stop events.  Once the number of event types have been cut down to a reasonable number, selection is no longer so fragile.  

Changes in the user interface that increase its complexity or have other potentially negative effects need a certain amount of vetting (at the least we should have a few votes (using the thumbs up reaction), before proceeding.

**Comment by brianrob** [comment]
Closing this issue, recommending @vancem's suggestion above.
