### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by szlatkow** [microsoft/perfview#1505]
Hello,
I am Svetoslav from PipelineFoundation and we are making CI/CD pipeline for your project, there are few specifics that I would like to know about the GitHub Releases
How are you packaging your GitHub Releases the first one is in production and the other one is in test ?

**Comment by brianrob** [comment]
@szlatkow, all of the releases that are published to GitHub are production releases.

**Comment by szlatkow** [comment]
@brianrob,
 Okay what is the difference from the Release marked with "T" on the version and the one marked with "P"?

**Comment by brianrob** [comment]
The difference is in the files that are published.  T == TraceEvent, and P == PerfView.
