### ISSUE TITLE
StackOverflow Exception when loading "Thread Time (with StartStop Activities) Stacks"

### ISSUE THREAD

**Issue by zbrilhart** [microsoft/perfview#1516]
When attempting to load the view "Thread Time (with StartStop Activities) Stacks" with Perfview or Perfview64.exe a stackoverflow exception is produced. 
![StringBuilderStackOverflow](https://user-images.githubusercontent.com/12052855/140938311-726580ef-9ba0-4708-bd61-b44ec6740f7b.png)

Debugging with visual studio gives a null reference at `System.Text.StringBuilder.get_Capacity()`
[stringbuilder.txt](https://github.com/microsoft/perfview/files/7505365/stringbuilder.txt)

The StringBuilder object was created with this Acquire Method from StringBuilderCache. 
[stringbuildercache.txt](https://github.com/microsoft/perfview/files/7505261/stringbuildercache.txt)

`
namespace Microsoft.Diagnostics.Tracing.Utilities
internal static class StringBuilderCache
	
		public static StringBuilder Acquire(int capacity = 16)
		{
			if (capacity <= 360)
			{
				StringBuilder cachedInstance = CachedInstance;
				if (cachedInstance != null && capacity <= cachedInstance.Capacity)
				{
					CachedInstance = null;
					cachedInstance.Clear();
					return cachedInstance;
				}
			}
			return new StringBuilder(capacity);
		}`
		
As you can see cachedInstance.Capacity is called and somehow `System.Text.StringBuilder.get_Capacity()` is returning null. 

StackFrame Screenshots
![stackframe2_10513repeats Microsoft Diagnostics Tracing Traceevent dll_Microsoft Diagnostics Tracing StartStopActivity GetActivityStack](https://user-images.githubusercontent.com/12052855/140938307-c042267d-17e2-4297-bcec-f8c57ab8ab18.png)
![stackframe1_OpenStackSourceImpl](https://user-images.githubusercontent.com/12052855/140938301-de3d3e82-bab8-47b4-b1cc-ecc8b73708eb.png)

The etl file is over 100MB

**Comment by brianrob** [comment]
Bulk closing old issues.  Please re-open if needed.
