### ISSUE TITLE
.NET 3.5 support for TraceEvent library

### ISSUE THREAD

**Issue by NN---** [microsoft/perfview#153]
Currently TraceEvent cannot be compiled for .NET 3.5.

Missing parts:
1. Concurrent collections, NuGet package can be used for this: https://www.nuget.org/packages/System.Threading.dll/
2. System.Tuple class, There is NuGet package for this too https://www.nuget.org/packages/NetLegacySupport.Tuple/
3. Missing framework methods such as string.IsNullOrWhitespace can be emulated with simple wrapper class.

I can help with PRs if you need any help there.

**Comment by vancem** [comment]
Support for older environments tends to create tradeoffs (forcing the code to conform to old conventions etc).    TraceEvent has support V3.5 runtimes in the past and I am open to continuing this IF IT IS NOT TOO CONSTRAINING.    My experience with the past V3.5 support was not too bad, but it is getting harder to do (use of newer features start to become more and more 'indispensable').   I do not wish constrain forward looking updates much at all.

Ultimately I think what we will end up with is a V3.5 BRANCH.   Maybe some of those changes can be integrated into master without pain,but the rest will simply live in the other branch.    Yes there is pain associated with picking up updates from the master branch into the V3.5 branch, but I think that is the best we can do.

**Comment by NN---** [comment]
I understand that 3.5 is a problem, but it is still officially supported by MS.

**Comment by sharwell** [comment]
@NN Can you provide a bit more information about what a .NET 3.5 build of this application would help you accomplish?

**Comment by NN---** [comment]
I am using the library as ETW consumer. More functionality is not needed right now.
The only important part for me is to have continuous bugfixes.

**Comment by sharwell** [comment]
@NN Thanks for the additional information! I'm new to looking at this project so I wasn't yet clear on the difference between the TraceEvent library and the PerfView application. (I'm sure it made sense to @vancem the whole time, but you did help me.)

**Comment by NN---** [comment]
No problems.
Perhaps you can split repositories to develop library and UI independently and use NuGet reference.
With new VS2017 ProjectReference feature it is very easy to maintain.

**Comment by NN---** [comment]
Btw for .NET 3.5 there is TaskParralellsLibrary NuGet workaround to provide Concurrent collections and Tasks.

**Comment by brianrob** [comment]
This issue has been open for some time, and things have only become more tied to newer releases.  As such, we are not going to provide support for .NET 3.5.  Closing this issue.
