### ISSUE TITLE
Can not visit channel9 PerfView video tutorials anymore.

### ISSUE THREAD

**Issue by Ruikuan** [microsoft/perfview#1538]
When trying to visit http://channel9.msdn.com/Series/PerfView-Tutorial, it's redirected to https://docs.microsoft.com/en-us/teamblog/channel9joinedmicrosoftlearn, without any useful information.

**Comment by Xhanti** [comment]
Hi,
Does anyone know where they have moved to? Doing a search on learn platform does not bring them up

**Comment by danharlin** [comment]
I'm also looking for the tutorial.

**Comment by MokoSan** [comment]
[This](https://www.youtube.com/watch?v=NDU-vTFfXgE&list=PLUw72SgBBmQxqm_e2g4QAdkyc88ZPL3aq) playlist has the first few videos. Alternatively, Wayback machine has been a life saver. [Here](https://web.archive.org/web/20200821043012/http://channel9.msdn.com/Series/PerfView-Tutorial) are all the old links. I am considering downloading all of them.

**Comment by Xhanti** [comment]
Can someone download them and put them on YouTube? What is the copyright on them?

**Comment by brianrob** [comment]
I am investigating what we should do here.  Will report back once I know more.

**Comment by danharlin** [comment]
Thanks, MokoSan, for the links.  They are a lifesaver.

**Comment by ronnieholm** [comment]
@MokoSan How do you download episodes from [archive.org](https://archive.org/)? For instance, on

https://web.archive.org/web/20200816135232/https://channel9.msdn.com/Series/PerfView-Tutorial/PerfView-Tutorial-7-Using-the-Event-Viewer-in-ASPNET-Scenarios

the source of the download links aren't archived.

**Comment by MokoSan** [comment]
@ronnieholm , thanks for the idea: I wrote a [Console App](https://github.com/MokoSan/Channel9VideoArchiveRetriever) that pulls in almost all the now unavailable Channel 9 links. Still working on a last few ones to process but added the ability to get videos from the archive based on a keyword. 

The specific one for PerfView can be found [here](https://github.com/MokoSan/Channel9VideoArchiveRetriever/blob/main/Channel9VideoArchiveRetriever/output/Mined/PerfView.md).

**Comment by brianrob** [comment]
As an FYI, I'm told that these videos will be migrated over from Channel9, but there is not yet an ETA.  Once it happens, I should get notified, and I can share here.

**Comment by adamsitnik** [comment]
@walkingcat did an amazing job of recovering the archive: https://walkingcat.github.io/ch9-index/?p=Series_PerfView-Tutorial

**Comment by WalkingCat** [comment]
I listed the .wmv format video links on that page, if you want other formats (.mp4) you can find them from Wayback Machine, simply remove the web.archive.org prefix and use the actual original url (https://sec.ch9.ms/....)

**Comment by Ruikuan** [comment]
@WalkingCat Thank you very much!

**Comment by mahamr** [comment]
These videos are now officially available here:
https://docs.microsoft.com/en-us/shows/perfview-tutorial/

**Comment by brianrob** [comment]
Thanks @mahamr!  Great to see this back up.  I have posted #1649 to update the links in PerfView.
