### ISSUE TITLE
Download link is not working as described in Downloading.md

### ISSUE THREAD

**Issue by turboscholz** [microsoft/perfview#1543]
In the file `Downloading.md`, section "Shortcut to Download the Latest PerfView.exe" (linked on the GitHub main page) it states:

> In the common case, you only need one file, PerfView.exe, to use the tool. The most recent copy of this file can be downloaded here:
> 
> GitHub release (latest SemVer)
> 
> Once you click the above link in your browser it will start downloading, the details of which vary from browser to browser. In some cases it will prompt for more information (IE) and in others (Chrome) it may not be obvious that you clicked on anything (look at the bottom of the pane for changes). The result, however will be a PerfView.exe on your local machine.

However, when I click on the link, neither with Firefox, nor with Chrome nor Edge the download starts. Instead, I see this page (see screenshot below), but there is nothing pointing me to `PerfView.exe`:

----
![image](https://user-images.githubusercontent.com/5513310/145066718-960d41a4-53da-4945-be86-14bf089265a5.png)
 
Can someone fix the wording on the documentation _or/and_ add the missing exe file into the download section? Or am I just missing something else?

**Comment by NSKC** [comment]
Requesting the same as user turboscholz.  The download instructions are not accurate for downloading perfview.exe.

**Comment by mregen** [comment]
try the 'releases' link: https://github.com/microsoft/perfview/releases/

**Comment by NSKC** [comment]
> try the 'releases' link: https://github.com/microsoft/perfview/releases/

Thanks!  I swear it looked different last week ;)

**Comment by brianrob** [comment]
I have updated Download.md via https://github.com/microsoft/perfview/pull/1548 to just link to the releases page, since it seems that getting the right order of releases has been tough for me.  :)

**Comment by turboscholz** [comment]
Maybe it was solved some days ago, but the PerfView.exe file is still/again not visible in the mentioned link above.
![grafik](https://user-images.githubusercontent.com/5513310/150207388-94ffc9bc-5d9a-482f-b271-fb887e3b7e6f.png)

**Comment by brianrob** [comment]
For each version, there is a PerfView release and a TraceEvent release.  So for 2.0.74, you have found the TraceEvent release.  If you go to the releases page, there will also be a PerfView 2.0.74.  This is the one that you want.

**Comment by turboscholz** [comment]
Thank you, now I got it. :)
