### ISSUE TITLE
PerfView cannot open ".diagsession" file on win 8 machine

### ISSUE THREAD

**Issue by weng5e** [Microsoft/perfview#155]
Hi,

I collected diagsession files on on Windows Server 2012 Datacenter (Build 9200, "win 8" for short in the following text) machine using the VSStandardCollector service. The file can be opened by PerfView on win 10 machines. (although not all the events are parsed correctly. This is mentioned in another [issue](https://github.com/Microsoft/perfview/issues/154).) However, the file cannot be opened on Win 8 machine. Logs indicate the file is loaded, but the corresponding etl file is not showing up in the main window:

![image](https://cloud.githubusercontent.com/assets/22308724/22079648/7e2e634a-dd71-11e6-89b7-ba12a260db77.png)

Tested with Version 1.9.00 and 1.9.49.

Thanks!

The diagsession file:

[sample_diagsession_file.zip](https://github.com/Microsoft/perfview/files/714830/sample_diagsession_file.zip)

The log:

Started with command line: "D:\Users\webworkeradmin\Desktop\PerfView2\PerfView.exe" 
PerfView Version: 1.9.49  BuildDate: Fri 01/06/2017 11:58:23.98
Started: View
Warning: PdbScope not found at D:\Users\webworkeradmin\Desktop\PerfView2\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at D:\Users\webworkeradmin\Desktop\PerfView2\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.067 sec)
Started: Opening iistest0200.diagsession
Opening diagnostics session file iistest0200.diagsession
Found 'e314b2e5-f3b8-4252-ba75-f59c7c7bf1c8' resource '0797E42F-003D-4F91-A845-6404CF289E84.m.etl'. Loading ...
Loaded 0797E42F-003D-4F91-A845-6404CF289E84.m.etl. Loading ...
Completed: Opening iistest0200.diagsession   (Elapsed Time: 0.109 sec)

**Comment by vancem** [comment]
I believe we have fixed this problem already.  

In particular I was able to open your diagsession with my recent version of PerfView.

Please pick up a new version from https://github.com/Microsoft/perfview/releases to see if it fixes the problem for you.   If not feel free to reopen this issue.
