### ISSUE TITLE
[TraceEvent] when reading a manifest that has 2 providers only 1 is shown 

### ISSUE THREAD

**Issue by yoziv** [microsoft/perfview#1551]
When reading a manifest file using TraceEventSession.Source.Dynamic.ReadAllManifests(FileName.man), i noticed that if my manifest contains two providers when i try to check which providers are registered i only get the first one in the file even though i get events from the second provider which "isn't registered" according to TraceEventSession.Source.Dynamic.DynamicProviders

`using var session = new TraceEventSession(TraceSessionName);
session.EnableProvider(Guid.Parse(SeciondProviderGuid));
session.Source.Dynamic.ReadAllManifests(ManifestsFolderName);
if (!session.Source.Dynamic.DynamicProviders.Any(manifest => manifest.Guid.Equals(Guid.Parse(SecondProviderGuid))))
{
//this will enter here 
}`

**Comment by brianrob** [comment]
@yoziv, looking at the code, it appears that the code is written to just handle one manifest per `man` or `manifest.xml` file.  It is possible to change the code to handle multiple manifests, but as it is written, this looks to be by design.
