### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by priceluke** [microsoft/perfview#1552]
I enable the Published Microsoft-Windows-DNS-Client provider and set the following callback function:
```
private void SessionEventCallback(TraceEvent data)
        {
            if (data != null && events.Count > TEXT_BLOCK_LENGTH)
            {
                events.RemoveAt(0);

            }
            events.Add(data);
            string sCombinedEventStrings = "";

            foreach (TraceEvent sEvent in events)
            {
                sCombinedEventStrings += TraceEventToString(sEvent); 
            }

            Application.Current.Dispatcher.Invoke(() =>
            {
                OutputTextBlock.Text = sCombinedEventStrings;
            });
        }
```
This allows me to have a buffer of `TEXT_BLOCK_LENGTH` events that I can display to the user.

The issue I am having arises when I try and access basic properties of the TraceEvent Object. I specifically get the NullReferenceException when retrieving the TimeStamp attribute.

Any ideas?

**Comment by brianrob** [comment]
Take a look at [Lifetime Constraints on TraceEvent Objects](https://github.com/microsoft/perfview/blob/main/documentation/TraceEvent/TraceEventProgrammersGuide.md#lifetime-constraints-on-traceevent-objects).  The issue here is likely that you are missing a call to `data.Clone()` before you add it to `events`.

**Comment by priceluke** [comment]
This solved my issue! Thank you very much :)

**Comment by priceluke** [comment]
@brianrob I've got a background thread running the TraceEventSession which updates a GUI. I find the session will sometimes close, not that I can work out why. Come across anything similar before or got any ideas on how you'd set this up?

**Comment by brianrob** [comment]
Glad that fixed things.  I'm not sure why the session would close unless it's being disposed.  Is it possible that its being disposed unintentionally or that the thread dies unintentionally, and so the session gets finalized?  FWIW, I would call `TraceEventSession.Process` on a background thread, and then as the events get processed on that background thread, update the data structures that the GUI uses.  What you're describing at a high-level sounds very reasonable to me.

**Comment by priceluke** [comment]
@brianrob I have implemented as you describe and works perfectly for the most part. When the background thread, responsible for processing events as they are created, pauses it can be successfully reconfigured to monitor new ETW providers. However, when it is monitoring very intensive providers, it doesn't ever break from processing and therefore doesn't restart with the new settings.

What is the best way to force the session to be reset from another thread? 

I've tried calling `session.Source.StopProcessing();` and `session.Source.Dispose();` so far.

Thanks again

**Comment by brianrob** [comment]
I think there is something happening that I didn't catch originally.  Are you trying to stop, change configuration, and restart the session?  If so, you should just be able to change the configuration of the session without stopping it, and if I recall correctly, it doesn't matter which thread you do this from, so you don't have to wait for the event stream to pause.  If you want to stop the session from another thread, you can call `session.Stop()` or dispose of the session if you're done with it.
