### ISSUE TITLE
How PerfView suppose to work with NGENed imaged

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [microsoft/perfview#1553]
Hi

I have a PerfView capture that was taken on client machine when client was using our software.  Our software has multiple .NET assemblies that are NGENed during installation process. We are using .NET Framework 4.8.

In that capture, I can see 2 PDB files generated by PerfView during capture process. I can see it from ```LogFile.txt``` from .etl.zip. I don't see attempts to generate any other PDB file except these 2.

But there are at least 5 more native images that present in callstacks but .PDB files are not there and as result PerfView image cannot display or load any information about them.

Looks like our client used relatively recent version:
```PerfView Version: 2.0.74  BuildDate: Mon, 08 Nov 2021 22:34:08 GMT```

All these assemblies built by the same build process. I checked project files and I don't see any difference between them for Release configuration.

I would like to ask, how is it suppose to work with native images that created by NGEN? Is it bug in PerfView or is it problem on our side?

Thank you,
Vlad

**Comment by brianrob** [comment]
There shouldn't be anything else that you need to do - PerfView should call `ngen.exe /createPDB` automatically to generate them.  You can generate them manually too, but you should not have to.  Would it be possible for you to share the trace file where you saw this, as well as which assemblies are NGEN images that didn't get generated?  You can share it here, or you can e-mail it to me at brianrob at microsoft.

**Comment by vladimir-cheverdyuk-altium** [comment]
Hi Brian

Thank you for prompt response. I sent link to file to your email as I'm not sure if our customer want this file public.

Also you said I can generate them too, just in case, could you please explain how, as it will help my investigation.

Thank you,
Vlad

**Comment by brianrob** [comment]
Thanks @vladimir-cheverdyuk-altium.  I received the file, and from a quick look, I would have expected the other NGEN assemblies to be generated, so I will need to debug this to understand further what happened.

If you want to generate the assemblies manually, you can run this command (customize for your assembly/machine):

```
C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\ngen.exe createpdb "C:\Windows\assembly\NativeImages_v4.0.30319_32\System\7eff558bb25b205bc169e86e89032f9d\System.ni.dll" "C:\Users\<userid>\AppData\Local\Temp\symbols"
```

PerfView should pick these up as long as this location is part of your symbol path.  You can also place the symbols elsewhere and just point PerfView to them via the symbol path.

**Comment by vladimir-cheverdyuk-altium** [comment]
Thank you @brianrob. I will wait for result.

About generating PDB files. I assumed that generating native images depends on processor architecture and will be different on different computers. So ```System.ni.dll``` on my PC will not be the same as ```System.ni.dll``` on customer PC. Did something change in this area, or do we all have the same class of processors and NGEN will always generate the same native image?

Vlad

**Comment by brianrob** [comment]
Correct - for .NET Framework, which this app is running on, the native images are all generated on the customer machine, and so the images and the PDBs are specific to that machine.  For .NET Core, any precompiled native images are generated as part of app deployment, and so while they'll be architecture specific, PDBs won't need to be generated at trace collection time.

**Comment by brianrob** [comment]
I think I have figured this out.  We use stack events to determine which NGEN images we need to generate symbols for.  One of the stack logging mechanisms isn't currently being used, and so when stacks are "compressed", they aren't considered when generating NGEN images.  The fix is just to consider this additional source of stack events.  Expect a PR shortly.

**Comment by vladimir-cheverdyuk-altium** [comment]
@brianrob, thank you for so quick diagnostics!

**Comment by brianrob** [comment]
You're welcome.  Would you by chance be able to test this change and make sure that it solves your problem?

**Comment by vladimir-cheverdyuk-altium** [comment]
Sorry I'm new to processes here. Is there any new version I can send to customer?

**Comment by brianrob** [comment]
The best way is to build it from source.  I have also just sent you an e-mail with a private copy to avoid posting unsigned bits here.
