### ISSUE TITLE
Do you want more Computers?

### ISSUE THREAD

**Issue by MatthewMWR** [Microsoft/perfview#156]
Over the years I've built up a library (wraps TraceEvent) that derives various domain specific facts about a trace. For example: Group Policy ran for user session x with parameters y and took duration z, etc. More recently I noticed that TraceEvent has a similar concept in the form of Computers (e.g. TcpIpComputer, TraceProcess, et al).

I'm wondering in the future whether to keep writing such things external to TraceEvent, or if it makes more sense to integrate with TraceEvents's Computers layer. Do you want TraceEvent's set of Computers to grow-- or were they just meant to be an internal enablers for specific parser/perfview scenarios? Are the facts (created by Computers) intended for broad consumption by callers?

**Comment by MagicAndre1981** [comment]
do you mean the Parsers? Have you created parsers for other Providers?

**Comment by MatthewMWR** [comment]
I mean the activity related computers that sit on top of parsers, like  https://github.com/Microsoft/perfview/tree/master/src/TraceEvent/Computers

**Comment by vancem** [comment]
Sorry for the delay, my spam filter was a bit too aggressive and I did not see these comments in real time.  

Computers are things that take a stream of events, and compute use things.  Typically they are state machines, remember information about past events so you know what the 'current' thing is.   For example the state every thread (whether it is blocked or not, and where it blocked) is kept by a 'Thread Time' computer, and is the heart of the 'Thread Time View'.  

To answer @MatthewMWR 

I think the basic model of a computer (you give it a TraceLogEventSource or a TraceEventDispatcher, and it subscribes to what it needs, and then is available to provide its information to anyone who needs it turning trace processing), it reasonable, and ideally others would use it when they have needs.  

Whether these computers belong in the TraceEvent DLL is another question.  That is mostly dictated by dependencies (do you need special parsers for your Computer), and general utility (is it something that others are likely to need).     

The good news is that that policy decision (where the code lives), is relatively easy to change, so we can start as it being a private thing and then decide on a case-by-case basis if it makes sense to be in the 'standard' set.

**Comment by vancem** [comment]
I am going to close this issue as it was a question and I probably answered it.    

Note that the concept of 'computers' is still pretty raw / unfinished, so if you pursue this, lets have a discussion before you invest in a particular direction.    They are likely to morph, so that requires a certain amount of coordination if ultimately want to pull them into this library.
