### ISSUE TITLE
Better error handling for opening Linux dumps

### ISSUE THREAD

**Issue by noahfalk** [microsoft/perfview#1562]
Visual Studio supports loading Linux core dumps (with a .dmp extension added) on Windows which leads our .NET developers to speculate that other tools such as PerfView will also work. Looking at PerfView's code I assume it isn't intended to be supported right now, but the error message doesn't help developers understand that.

**Repro:**
1. Open PerfView UI
2. Use the file picker to double-click a Linux core dump that has had the .dmp extension appended to it
3. In the modal dialog box which pops up click 'Dump GC Heap'

**Expected result:** Some error message appears in the status bar or elsewhere in the UI indicating that Linux dumps are not supported
**Actual result:** Status bar displays "HeapDump failed with exit code 1". Log shows:
```
Creating heap dump E:\devdumps\core_20220202_011152.gcdump from process dump E:\devdumps\core_20220202_011152.dmp.
HeapDump Error (-2147024809): Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: Could not load crash dump, HRESULT: 0x80070057
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader..ctor(String dumpFile)
   at Microsoft.Diagnostics.Runtime.DataTarget.LoadCrashDump(String fileName)
   at GCHeapDumper.InitializeClrRuntime(String processDumpFile, DataTarget& target, ClrRuntime& runtime)
   at GCHeapDumper.DumpHeapFromProcessDump(String processDumpFile)
   at Program.MainWorker(String[] args)
```

**Comment by brianrob** [comment]
Thanks for pointing this out @noahfalk.  Seems reasonable to have a better error message here - I will see if I can get this done soon.
