### ISSUE TITLE
Test GenerateBaselineXmlFiles fails when running it with a german os

### ISSUE THREAD

**Issue by nicnike** [microsoft/perfview#1581]
When running the tests with a German operating system, both GenerateBaselineXmlFiles tests fail because the two files have different time formats. One has 12h format and the other the 24h format.

A possible solution might be attribute [UseCulture("en-US")]

![2022-03-07_14h20_47](https://user-images.githubusercontent.com/57753615/157042154-355618bb-31ed-4253-9c49-abf51e6275d9.png)

**Comment by brianrob** [comment]
Yes, I think you're right.  Does this change fix the issue?

**Comment by nicnike** [comment]
Yes after the change the test ran without problems.
