### ISSUE TITLE
[Request] Make is possible to work with captured stack traces

### ISSUE THREAD

**Issue by simonthum** [microsoft/perfview#159]
In some (admittedly particular) circumstances, it can be very beneficial to log stack traces captured by custom diagnosis routines. There even is an msdn example:

https://msdn.microsoft.com/en-us/library/windows/desktop/dn904628%28v=vs.85%29.aspx

That is, the final event contains a string attribute with the trace as seen by .net. If perfview would allow to analyze using such custom traces instead of, or in addition to the system-provided ETW traces that would be very helpful.

**Comment by vancem** [comment]
PerfView does have the ability to log stack traces from users events.

The first step is to log the event with an EventSource see 

https://blogs.msdn.microsoft.com/vancem/2012/07/09/introduction-tutorial-logging-etw-events-in-c-system-diagnostics-tracing-eventsource/

For details.   (you can make it that other logging systems turn around and log EventSource events if desired).   

Once you have an EventSource you can get stacks traces for your EventSource by using the syntax

/providers=YOUR_EVENTSOURCE@StacksEnabled=true 

See the PerfView documentation for more on the syntax for specifying providers.      

Once you do that your EventSource Events show up in the 'Any Stacks' view under the 'Advanced Group'.

**Comment by simonthum** [comment]
Hi Vance,

thanks for your time, but I think you misunderstood my use case. My event is triggered by a diagnosis algorithm to signal a condition **in another thread**.  The example I linked logs the stack trace of an exception to ETW, I am logging the stack I care about, but both log the really interesting stack traces **as text**. But I'd like to analyze based on these stacks, which means I need to teach PerfView how to use them right?

I am already using the ETW-provided stack traces for numerous purposes. I will try as you say but I believe this is the built-in stuff I know quite well by now.

**Comment by vancem** [comment]
I have reopened the issue, but it is not at all clear to me that this is a case that is worth building reusable infrastructure for.  

Note that PerfView's infrastructure supports creating stack views out of just about anything (in the source code see the 'Other Sources' directory and in particular maybe the FileSizeStackSource is a useful example.  

I could envision you making a user command that takes a trace looks for your events, and creates a stack source (or writes it out as a .PerfView.xml file).   Merging two stack sources (that is combining it with other stack data, is also pretty straightforward.

**Comment by simonthum** [comment]
Vance, that sounds very useful, I'll give it a shot!

What I notice is that in .net, there is a de facto stack representarion, namely StackTrace.ToString and Exception.ToString. Basically I'm asking for built-in support for these 'text stacks' in PerfView.

What makes it look worth to me is the fact that I can be much smarter about the issues, meaning I can collect better data with much less volume. That last bit is important to me, I need to collect on relatively small devices for prolonged periods.

**Comment by simonthum** [comment]
Vance, I went with .perfView.xml files and they work great. Thanks for the tip!

However, I still think of this a useful addition, because I had to add a side path into my collection strategy. Also, I am limited to PerfView with this particular diagnosis.

**Comment by vancem** [comment]
I have left this open as a long term item.   My expectation is that it will probably require inspiration from the community to move forward.

**Comment by simonthum** [comment]
Maybe the real requirement is making any kind of hierarchical information (not just stacks) more accessible for analysis. I experimented with WPA, which is impressive in general, but man did I miss the folding and grouping of PerfView!

**Comment by brianrob** [comment]
Per @vancem's comments above, it would be possible to write a user command that does this.  If you want to contribute this, we'd be open to taking a PR.  That said, given the age of this issue, I am going to close this.  Please re-open if you would like to contribute this to PerfView.
