### ISSUE TITLE
StopOnBGCFinalPauseOverMsec incurs an exception

### ISSUE THREAD

**Issue by Maoni0** [microsoft/perfview#1591]
with this command 

`PerfView /nogui /accepteula /StopOnBGCFinalPauseOverMsec:30 /Process:corerun /DelayAfterTriggerSec:0 /CollectMultiple:1 /KernelEvents=ThreadTime+Memory+VirtualAlloc /ClrEvents:GC+Stack /BufferSize:3000 /CircularMB:3000 /Merge:TRUE /ZIP:True collect`

I'm seeing this exception

`Only allowing process corerun with ID 61308 stop the trace.
Collecting   10 sec: Size= 94.5 MB. Error: Exception thrown during monitoring: Unable to cast object of type 'Microsoft.Diagnostics.Tracing.Parsers.DynamicTraceEventData' to type 'Microsoft.Diagnostics.Tracing.Parsers.Clr.GCSuspendEETraceData'.`

with the latest ver of perfview.

**Comment by brianrob** [comment]
@Maoni0, how reliably are you seeing this?  I suspect that to diagnose this, I'd need to run the workload that you're running, since this is an exception in the live session used for monitoring during collection.

**Comment by Maoni0** [comment]
I can repro this with any workload. I just use corerun to run a test and run perfview with that commandline and it doesn't seem to matter what test I'm running (it may or may not be doing BGCs at all) and I can repro this exception. eg

corerun ..\..\GC\Performance\Tests\ConcurrentSpin\ConcurrentSpin.dll

corerun ..\..\GC\Performance\Tests\GCSmall\GCSmall.dll

**Comment by brianrob** [comment]
Thank you.  I will see if I can repro this.

**Comment by brianrob** [comment]
This should now be fixed and will be included in the next release.

**Comment by Maoni0** [comment]
thanks for fixing this!
