### ISSUE TITLE
Port Perfview to .net 6.0

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/perfview#1594]
Is it possible to target .net 6.0 to get more perf fixes from the runtime?

> This is certainly something that could be considered, but would need to be evaluated to determine how much work it is.

_Originally posted by @brianrob in https://github.com/microsoft/perfview/issues/1579#issuecomment-1076933699_

**Comment by MagicAndre1981** [comment]
I also see that [Perfview misses ARM support](https://github.com/microsoft/perfview/blob/c52d255aa070a53429a4e660a73dec56917a3dd7/src/PerfView/App.cs#L127), with .net6 it can run an ARM64 as .net6 has WPF support on ARM64

**Comment by brianrob** [comment]
As an FYI, PerfView supports capture on arm64 by running in x86 or amd64 emulation mode.  It should just work without any extra steps.

**Comment by MagicAndre1981** [comment]
yes, but native ARM64 support would be better

**Comment by brianrob** [comment]
I'm going to close this issue for now as there is now native arm64 .NET Framework and so PerfView will be able to run natively on these machines.  That said, considering moving PerfView to .NET 6 is something that we'll keep as an option.
