### ISSUE TITLE
System.Runtime.InteropServices.COMException when running SimpleEventSourceMonitor in Visual Studio Debug Mode

### ISSUE THREAD

**Issue by ld0614** [microsoft/perfview#1598]
Visual Studio Version: 2022 - 17.1.1
.Net Framework 4.6.2

When starting the SimpleEventSourceMonitor sample in a new project using the standard start with debug (F5) I get the following error message on line 109 (session.Source.Dynamic.All += delegate (TraceEvent data)).  The weird thing is that if the code is run without the debugger enabled (Ctrl + F5) the code works correctly.  If the SimpleMontitorSession session is already created the application works correctly even in debug mode.

```
System.Runtime.InteropServices.COMException
  HResult=0x800705AA
  Message=Insufficient system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA)
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnsureStarted(EVENT_TRACE_PROPERTIES* properties)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.get_Source()
   at TraceEventSamples.SimpleEventSourceMonitor.Run() in C:\Source\TraceEvent\TraceEvent\Program.cs:line 109
   at TraceEventSamples.SimpleEventSourceMonitor.Main(String[] args) in C:\Source\TraceEvent\TraceEvent\Program.cs:line 190

  This exception was originally thrown at this call stack:
    [External Code]
    TraceEventSamples.SimpleEventSourceMonitor.Run() in Program.cs
    TraceEventSamples.SimpleEventSourceMonitor.Main(string[]) in Program.cs
```

Removing this code offending section causes the code to break later on, it appears that any reference to session.Source causes the COMException.

Running `logman query -ets` I see 56 entries with the debugger enabled (paused at first exception) with 50 when no application is being debugged.  Could it be these extra 6 VS managed traces which are causing this?  If so are there any ways to reduce the data collector sets without impacting functionality?

**Comment by brianrob** [comment]
Can you confirm that Visual Studio is running as an administrator?  The process itself must run as an administrator in order to have permissions to start a session.  If Visual Studio is not running as an administrator, then when you F5, it won't have permissions to start the session.

**Comment by ld0614** [comment]
Visual Studio does run as administrator, it seems to work fine on another computer so looks like my main system just has a lot of other sessions open by default which is odd...

**Comment by brianrob** [comment]
Hitting the session max could definitely do it.  There are hidden sessions when you run `logman query -ets`, so you may have just hit the session max on that machine.

**Comment by brianrob** [comment]
Bulk closing old issues.  Please re-open if this is still an issue that needs attention.
