### ISSUE TITLE
The ToString() method of StructValue in DynamicTraceEventParser produces a json string with unquoted keys

### ISSUE THREAD

**Issue by xinyugu1998** [microsoft/perfview#1618]
I'm trying to read the "TraceIdentifier" from Microsoft-Diagnostics-DiagnosticSource/Activity1Stop/Stop events, which have 3 payloads: SourceName, EventName and Arguments:
![image](https://user-images.githubusercontent.com/104054856/164161737-099da647-6308-4bb8-a833-8532241f2f61.png)
I get the "Arguments" payload like this:
```
object[] arguments = (object[])traceEvent.PayloadValue(2);  // This is actually StructValue[], length=2
string traceIdentiferJsonStr = arguments[0].ToString();     // Invokes ToString() method of StructValue
```
The "Arguments" payload is an array of StructValue defined in [DynamicTraceEventParser](https://github.com/microsoft/perfview/blob/main/src/TraceEvent/DynamicTraceEventParser.cs), whose ToString() method should produce a valid json string, so that it can be deserialized by tools like System.Text.Json. But as we can see in line 858 of DynamicTraceEventParser, the key is added without double quotation marks:
![image](https://user-images.githubusercontent.com/104054856/164162998-2cfaeee3-46f7-4a18-8b3e-5b817f1c4e03.png)
So ToString() method produces a string like this: 
`"{ Key:\"TraceIdentifier\", Value:\"8034b159-0003-1d00-b63f-84710c7967bb\" }"`
The keys are not quoted, causing errors when deserialized.
Are there any reasons why the keys are not quoted? The produced json string is invalid.

**Comment by brianrob** [comment]
@xinyugu1998, this is likely just a bug.  It seems reasonable to fix this.  I will post a PR shortly.

**Comment by xinyugu1998** [comment]
Thank you! @brianrob
