### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by ulimartinez** [microsoft/perfview#1625]
Trying to enable a provider using a name I am getting an error saying An item with the same key has already been added. Each time I get this error the key is different and also not the name of the provider I am trying to enable.

`System.ArgumentException: An item with the same key has already been added. Key: [Windows Kernel Trace, 9e814aad-3204-11d2-9a82-006008a86939]
   at System.Collections.Generic.TreeSet1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedSet1.Add(T item)
   at System.Collections.Generic.SortedDictionary2.set_Item(TKey key, TValue value)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.get_ProviderNameToGuid()
   at Microsoft.Diagnostics.Tracing.Session.TraceEventProviders.GetProviderGuidByName(String name)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(String providerName, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)`

**Comment by brianrob** [comment]
Can you please provide the command line that you used that caused this?

**Comment by ulimartinez** [comment]
Actually it was using the Microsoft.Diagnostics.Tracing nuget package for c#

**Comment by brianrob** [comment]
Gotcha.  Looking at that code, this calls into the OS to get every provider that is registered on the system.  This implies that you have multiple providers with the same name and GUID registered on the system.  Can you confirm this via a call to `logman query providers`?  When I run this on my machine, I only see one instance of this provider.

**Comment by ulimartinez** [comment]
I ran logman query providers but I only see one entry for the provider shown in the error. I checked for any duplicates and I do not see duplicate provider names, I do however see duplicate guids in the output, here are examples:

- 
- UMDF - WDF Core                          {485E7DE9-0A80-11D8-AD15-505054503030}
- Wudfx02000_KmdfTraceGuid                 {485E7DE9-0A80-11D8-AD15-505054503030}
- UMDF - Framework Trace                   {485E7DE9-0A80-11D8-AD15-505054503030}

All have the same guid

- Microsoft-Windows-RestartManager         {0888E5EF-9B98-4695-979D-E92CE4247224}
- RmClient_RestartManager                  {0888E5EF-9B98-4695-979D-E92CE4247224}

also share the same guid

**Comment by brianrob** [comment]
From the output above, the key is a combination of the name and the GUID.  I'm surprised that you're seeing this.  Does this repro for you on multiple machines?  If it does, I'd like to ask for a minimal repro so that I can try to understand what's happening here.

**Comment by ulimartinez** [comment]
Yes I am seeing this on multiple machines. One thing to mention is that it is being run on devices with TeamOS version of windows

**Comment by brianrob** [comment]
@ulimartinez if you're able to repro this on an official build of Windows, then we should definitely investigate.  If this just repros on TeamOS, then that is likely unsupported.

**Comment by ulimartinez** [comment]
This is the build that is run on Surface Hub devices as per: https://docs.microsoft.com/en-us/surface-hub/differences-between-surface-hub-and-windows-10-enterprise

does it not count as an official build?

**Comment by brianrob** [comment]
Thanks for clarifying.  That's not what I thought you meant.  Yes, the official OS running on Surface Hub would be supported.  I had not heard of this version of the OS and searching for TeamOS sent me elsewhere.  Unfortunately, I don't have a Surface Hub that I can test this on, but if you can share the source code for a simple repro, I'll see what I can figure out.

**Comment by brianrob** [comment]
No worries at all.  I am not able to repro this, and have been trying a few things over here to see what might be happening.  A few questions:

1. Is it possible that you're calling `EnableProvider` concurrently on multiple threads?  From the implementation of `SortedDictionary`, that could cause this behavior.  `TraceEventSession.ProviderNameToGuid` creates the `SortedDictionary` in a non-threadsafe fashion, and `SortedDictionary` itself isn't threadsafe.
2. What version of .NET are you running this against?

**Comment by ulimartinez** [comment]
Ah I think the issue is in EnableProvider being called elsewhere from a different thread. For now I have mitigated the crash by calling EnableProvider with the guid directly instead of by name as that is one of the overloads.

**Comment by brianrob** [comment]
Ok, that makes sense.  These APIs are not thread-safe, and so calling `EnableProvider` concurrently from another thread is likely to cause odd issues like this.  I'm going to go ahead and close this issue, please let me know if you have any other issues.
