### ISSUE TITLE
Latest version of PerfView do not collect CPU sampling data

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [microsoft/perfview#1639]
Hi

I received PerfView files from our customer that were recorded with 3.0 version of PerfView. When I open CPU Stacks with same version of PerfView, I see that CPU MSec column is zero for all processes. I couldn't find anything incorrect or any errors in log file.

We have document how to setup PerfView to collect this information here:
https://www.altium.com/documentation/knowledge-base/altium-designer/how-do-i-use-perfview-to-collect

And I asked customer to double check settings again, he did it and sent me new file and it has exactly the same problem. I assumed that they will do the same mistake twice.
I was trying to play with different settings and I couldn't reproduce it in any way. I never seen such problem before and I'm not sure if this is issue on customer's PC or he didn't set proper settings.

I can upload files to cloud and send link to appropriate person, if needed. I cannot publish them here, because they may contain sensitive information.
Files sizes are: 11, 12 and 31 megabytes for about 1 minute. Duration is 71, 153 and 68 seconds. File sizes looks too short to me.

Thank you,
Vlad

**Comment by brianrob** [comment]
@vladimir-cheverdyuk-altium I have seen this sort of thing before where there is a driver on the machine that interferes with the profiling interrupt setup.  Examples of apps that I've seen cause this are VTune and OEM manufacturer performance monitors.  Usually uninstalling these apps and rebooting solves the problem.

If you would like to upload a trace to a shared location and send a link to me at brianrob [at] microsoft, I can look at the trace file and log and make sure there isn't something else going on.

**Comment by vladimir-cheverdyuk-altium** [comment]
Hi Brian

I sent you email with link.

>OEM manufacturer performance monitors
Maybe you know some specific name of such application, so I can advise customer to uninstall it? I afraid that it could be some bloatware that vendors installed by PC vendor.

Thank you for checking this,
Vlad

**Comment by brianrob** [comment]
I was looking for examples in my e-mail but couldn't find the ones that I was hoping were still there.  I remember specifically that Lenovo has a tool that has caused this.  Maybe it's [this](https://support.lenovo.com/us/en/downloads/ds105193-lenovo-performance-tuner-thinkstation-thinkpad) one, but I don't recall for sure.

**Comment by brianrob** [comment]
Closing this issue as we discussed this offline, and this is likely a machine-specific issue.
