### ISSUE TITLE
Port TraceEvent to .NET Core 

### ISSUE THREAD

**Issue by vancem** [Microsoft/perfview#165]
This is transferring the following bug that was in the corefx repo https://github.com/dotnet/corefx/issues/4864

Basically we want the Microsoft.Diagnostics.Tracing.TraceEvent nuget package to work on .NET Core.

**Comment by adamsitnik** [comment]
@vancem I just want to let you know that BenchmarkDotNet would love to have `Microsoft.Diagnostics.Tracing.TraceEvent` ported to .NET Core. We are currently using the existing version, and would like to give our .NET Core users great experience.

**Comment by ViktorHofer** [comment]
@vancem Is there any progress on that matter or are you still investigating? We have some disabled tests in corefx for that.

**Comment by vancem** [comment]
I have not made progress.  It should be a straightforward exercise (at least to make SOME progress), I just have not had time.    I will raise its priority a bit, but I still offer no promises.

**Comment by vancem** [comment]
This has been fixed by PR #360.

**Comment by adamsitnik** [comment]
@vancem When do you plan to release the new NuGet package?

**Comment by vancem** [comment]
> When do you plan to release the new NuGet package

There is some work to do before I can release the package on Nuget.   In particular it needs to be signed, and some testing has to be added.   Also it has to be tested on the scenarios we have for that package (e.g.  there are samples).    This is not my top priority right now so it is hard to give a deadline, but it will be at least another week or so (the wildcard is how much time I can give it)

**Comment by TyOverby** [comment]
Hi @vancem, it looks like this package has not made its way to nuget yet.  Is there anything I can do to help publish it?  I'm just down the hall from you if you want to chat!

**Comment by benaadams** [comment]
Was trying to listen to some kernel events with .NET Core to detect blocking calls; but alas...

Would be great when the packages are shipped! 😉
