### ISSUE TITLE
Does PerfView have WSL Support or have plans of supporting WSL?

### ISSUE THREAD

**Issue by mtmulch** [microsoft/perfview#1668]
Hello there, 

I was working elsewhere  in the depths while Microsoft Open Source movement was happening. This looked like an interesting tool to use and potentially contribute to. 

Does PerfView have any plans for WSL support either Ubuntu or Kali?

**Comment by mtmulch** [comment]
@brianrob It took me a moment to discover what you where referring to. I have found the docker files associated with running perfcollect. I will look further into the tool at another point in time and post another issue if I have any further questions.

**Comment by brianrob** [comment]
Sounds good!
