### ISSUE TITLE
SaveCPUStacks user command returns error

### ISSUE THREAD

**Issue by slevenstein** [microsoft/perfview#1669]
Hi!

I'm trying to save the view for CPU Stacks of a specific process as an xml file through the command line. 

I've been able to get the xml file successfully through the GUI, but when attempting to execute the User Defined Command to do the same thing, which I believe is `SaveCPUStacks`, I run into this error:

>  The process cannot access the file `C:\Users\Scl33\AppData\Local\Temp\PerfView\PerfViewLogFile.txt' because it is being used by another process.

I closed all windows of Perfview and used Process Explorer to make sure nothing else was accessing that log file, and I ran it again but still the same results. I've tried this on different machines, etl files, processes, and versions of Perfview, yet the same error persists.

Steps to Reproduce:
- Use Collect or Run to create etl file (Alt + C or Alt + R) 
   - uncheck zip to make sure everything is in the same directory
- File -> User Command (Alt + U)
- Type in `SaveCPUStacks [file name] [process name]` and press OK (e.g. `SaveCPUStacks PerfViewData.etl Perfview`)
   - Alternatively, open command prompt and run `Perfview UserCommand SaveCPUStacks [file name] [process name]` in the correct directory

Any ideas of what I could be doing wrong or what could be causing this?

**Comment by brianrob** [comment]
@slevenstein thanks for reporting this.  I ran into the same issue - it seems that the log can be locked when writing out the stacks.  The code is trying to save the log along with the rest of the context for the stack view.  This is likely nice to have but not required, so I've changed the code to not fail if we can't get the log.

**Comment by slevenstein** [comment]
Thanks Brian, you're the best!
