### ISSUE TITLE
Cancel the instance with stop trigger through command line

### ISSUE THREAD

**Issue by BadriL** [microsoft/perfview#1671]
This is a query and not an issue. Apologies if this is not the right forum.

While running perfview through command line, if I use a stop trigger, for example, /StopOnGCOverMSec, a command window shows up asking for S to be pressed. Suppose, I start with /FocusProcess:"12345" and this process has restarted, that is, the process with PID 12345 no longer exists and that I want to stop the perfview instance focusing on that process with PID 12345. How could I do this programmatically? If simply kill that process, will it be okay? I ask because the message warns "Do NOT close this console window. It will leave collection on! Type S to stop collection..." and I don't want to do that. So, what is the correct programmatic way to cancel such instances?

**Comment by brianrob** [comment]
@badril, this is a good place for these types of questions.  If you are limiting to a specific process and want to stop when the process dies, you should not just kill the process, as this will leave the ETW session alive.  You will want to kill it by programmatically sending an "S" to the console of PerfView.  Another option if you want more fine-grained control of things is to create your own collector app using TraceEvent, but I would recommend trying to script PerfView if you can.

**Comment by BadriL** [comment]
Thanks for the prompt response. Will try sending S to the console programmatically.
