### ISSUE TITLE
PerfView 3.0.4 (3.0.3 works) cannot dump x64 memory dumps

### ISSUE THREAD

**Issue by AloisKraus** [microsoft/perfview#1704]
PerfView 3.0.4 uses for x64 dumps the 32 bit HeapDump which cannot work. Seems to be a regression issue. 
Please fix.

**Comment by brianrob** [comment]
There was a break in this area that I just recently fixed via #1702.  Can you see if that addresses the issue for you?

**Comment by AloisKraus** [comment]
Yes the latest version works. But I had issues to compile it because PerfView needs 

`System.Numerics.Vectors\4.5.0\lib\net46\System.Numerics.Vectors.dll`

which it did not find. After adding a direct nuget package reference it still did not work. At least on my machine it was located at

`C:\Program Files\dotnet\sdk\NuGetFallbackFolder\System.Numerics.Vectors\4.5.0\lib\net46\System.Numerics.Vectors.dll`

**Comment by brianrob** [comment]
Glad that it worked.  System.Numerics.Vectors is required for heapdump, but the version required is not available as a NuGet package.  Instead, it is picked up from the SDK because the dependency comes from Microsoft.Diagnostics.Runtime, which is built against netstandard20.
