### ISSUE TITLE
What is reason 8 for ThreadPoolWorkerThreadAdjustmentAdjustment event?

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/perfview#1708]
EventPipe captured thread adjustment event with reason 8:
![image](https://user-images.githubusercontent.com/3674549/188954639-0335c2e6-e19f-41c4-998e-c7417933c8bd.png)

According to this document, there are listed reasons from 0x00 to 0x07:
https://docs.microsoft.com/en-us/dotnet/framework/performance/thread-pool-etw-events#threadpoolworkerthreadadjustmentadjustment

**Do we know what does 0x08 means?**

I also don't see an enum for the reason in the runtime repo:

Refer to this [Runtime code](https://github.com/dotnet/runtime/blob/4cf2e3bb18162d750e7a128bb805c49c9fd52612/src/libraries/System.Private.CoreLib/src/System/Threading/NativeRuntimeEventSource.PortableThreadPool.NativeSinks.cs#L59)
Am I looking into the right place?

Thanks!

**Comment by xiaomi7732** [comment]
Hey @brianrob Thanks for the quick turn-around. What does CooperativeBlocking mean? Do you have any documentation to help understand it?
It will also be great if there's any documentation to explain other reasons in the enum too.
Thanks!

**Comment by brianrob** [comment]
CooperativeBlocking is a behavior that allows the threadpool to detect behavior that looks like sync-over-async and increase the rate of thread injection to avoid thread starvation.

**Comment by xiaomi7732** [comment]
Makes sense. Thanks for the info.
