### ISSUE TITLE
OOM Exception inside Perfview when trying to analyze a largish etl file

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/perfview#171]
An unhanded exception occured.

At this point you can opt to continue, however it is possible that the aborted computation will cause additional failures.   Because PerfView generally only opens files for reading, there is no danger of corrupting  files, so it generally does not hurt to try.   However be on guard for unusual/incorrect behavior going forward.

You can of course exit and restart PerfView to be completely safe.

__The fact that this exception went unhanded is a programmer error.   It should be reported so it can be fixed.  Please set along the following stack trace information which will be useful in diagnosing the problem.__

StackTrace:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at Controls.TextEditorWriter.<Flush>b__3_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

--------------------------

![image](https://cloud.githubusercontent.com/assets/4236651/24858472/c5c47a94-1dec-11e7-8aa2-db16c3d156f3.png)

This occured when trying to open "Thread Time" on a 2.7GB etl file.

If you need it I can either send you the original etl, or a dump of perfview itself.

-------------------

![image](https://cloud.githubusercontent.com/assets/4236651/24858548/0db02420-1ded-11e7-8057-e95fe75b3f99.png)

(latest from official download center)

**Comment by vancem** [comment]
See my comment at the top of #175 for a work around of making a 64 bit version of PerfView.
