### ISSUE TITLE
Sort order should not change in By Name view after symbol lookup

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#173]
### Steps to reproduce

1. Switch to **By Name** tab
2. Set grouping to **[no grouping]**
3. Set sort order to **Inc** (descending)
4. Right click on any run and click **Lookup Symbols**

### Expected result

Sort order remains as **Inc** (descending).

### Actual result

Sort order switches to **Exc** (descending).

**Comment by vancem** [comment]
This *should* be easy.   If anyone wants to tackle it and needs some guidance I will tell you what I know.
