### ISSUE TITLE
Why thread pool starvation with a few the worker threads

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/perfview#1730]
This is an ETW trace, on the ThreadPoolThread adjustment:
![image](https://user-images.githubusercontent.com/3674549/195960654-01cc9818-f0b3-45e0-a79e-0e62851dbc1d.png)

32 seconds in, ThreadPool adjusted due to `Starvation`, the NewWorkerThreadCount is only 2, and then 3 in 2 seconds, and then there were no events for adjustments.

Why did the .NET Framework runtime behave like that? Any suggestion on what to check? Is it caused by some invalid configurations?

**Comment by xiaomi7732** [comment]
@brianrob, Thanks for the reply. 2 follow up questions

1. According to the doc:
> By default, the minimum number of threads is set to the processor count
Does that mean, the target app has been deployed into an environment that has 1 or 2 cores? Generally, would it be appropriate to suggest setting the minimum value to 8 or 16 ish?

2. Thread pool thread count is always adjusting, not all of them show the reason for Starvation. What could have caused it than climbing?

**Comment by brianrob** [comment]
> Does that mean, the target app has been deployed into an environment that has 1 or 2 cores? Generally, would it be appropriate to suggest setting the minimum value to 8 or 16 ish?

It is reasonable to try setting the value higher and see how things perform.  The default value is generally safe, but not always optimal, especially when there are large swings in the amount of queued work items.  You can tell for sure how many CPUs are present on the machine by looking at the Trace Info.

> Thread pool thread count is always adjusting, not all of them show the reason for Starvation. What could have caused it than climbing?

Right, the thread pool is constantly trying to find the optimal number of threads to maximize throughput.  `ClimbingMove` represents the thread pool hill climbing algorithm trying out a new thread count to see how it impacts the work item throughput.

**Comment by xiaomi7732** [comment]
That makes sense. Thanks.
