### ISSUE TITLE
Sort order should be descending by default

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#174]
### Steps to reproduce

1. Switch to **By Name** view, with the sort order set to any column except **Inc**
2. Click **Inc**

### Expected results

Sort order is now **Inc** (descending).

### Actual results

Sort order is now **Inc** (ascending).

**Comment by vancem** [comment]
I *think* this is behavior that PerfView gets from the underlying (Windows Presentation Foundation) WPF control.   There is a good chance this can only be fixed easily by modifying WPF code.
