### ISSUE TITLE
Always show MemoryAnalyzer?

### ISSUE THREAD

**Issue by mahamr** [microsoft/perfview#1771]
Right now the MemoryAnalyzer feature is hidden from non-internal users. This is code that was pulled-in to GH when it was first added
https://github.com/microsoft/perfview/blame/9dd10abfa9bbce7df9b14331841dba08c2774b13/src/PerfView/PerfViewData.cs#L7475

Seeing as this is now open source and when it did work (I no longer see this at least on corp VPN, maybe in-office it works, can test later) it was pretty useful, I feel this is worth opening up to everyone. 

Thoughts?

If this is approved I can submit a PR for it.

Thanks!

**Comment by brianrob** [comment]
@mahamr, thanks for pointing this out.  For some reason, I thought I had already done this.  Yes, please do submit a PR to remove the internal check.

**Comment by mahamr** [comment]
@brianrob sure thing! Will get that done this week and send the PR
