### ISSUE TITLE
perf artifact recorded without -a option failed to be loaded on WPA

### ISSUE THREAD

**Issue by ami-GS** [microsoft/perfview#1793]
Please refer WPA extension project (PerfDataExtensions). link below

https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/issues/108

**Comment by brianrob** [comment]
@ami-GS, this is expected behavior.  The parser implementation expects that the `-a` argument was used during capture.

**Comment by ami-GS** [comment]
Because data captured with -a is too big (slow) to open especially converting framegraph.
I want to reduce artifact as small as possible

**Comment by brianrob** [comment]
I see.  Unfortunately, this is expected behavior.  I imagine it's possible to change this, but this is the current behavior today.  I don't anticipate this would be super high on the priority list, but if this is a change you'd like to contribute, that's an option.
