### ISSUE TITLE
Clean build have issues

### ISSUE THREAD

**Issue by kant2002** [microsoft/perfview#1800]
1. Clone repo
2. Nuke Nuget cache. so 
3. Try to build and notice that build complain about missing resource.

this line cannot be embedded, since nobody pull that dependency explicitly in the project.
https://github.com/microsoft/perfview/blob/e2696ec466d4cacdfc057adf0e09ce22728573a5/src/PerfView/PerfView.csproj#L515-L521

**Comment by brianrob** [comment]
I think you just need to run msbuild /t:restore. Can you see if that solves the problem?

**Comment by kant2002** [comment]
It does not help. what is referenced is `System.Numerics.Vectors\4.4.0` via [`System.Reflection.Metadata = 5.0.0`](https://www.nuget.org/packages/System.Reflection.Metadata/5.0.0) which has dependency onn https://www.nuget.org/packages/System.Collections.Immutable/5.0.0 which has dependency onn `System.Memory=4.5.4` and then `System.Numerics.Vectors\4.4.0`

**Comment by brianrob** [comment]
PerfView has a little bit of a quirky dependency capture mechanism, and so I suspect this is coming from HeapDump.  We likely just need to add an explicit <PackageReference/> for this to PerfView.csproj.  If you do that, does it solve the problem?

**Comment by kant2002** [comment]
Looks like this is reason for https://github.com/microsoft/perfview/issues/1704#issuecomment-1236172881 or somewhat related.

**Comment by kant2002** [comment]
HeadDump has their own entry 
https://github.com/microsoft/perfview/blob/e2696ec466d4cacdfc057adf0e09ce22728573a5/src/PerfView/PerfView.csproj#L286-L292

Adding direct entry does not work, since on my computer this Nuget package comes from `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\` which is slightly different then Nuget cache. I assume that this is change from newer .NET (or .NET SDK)
