### ISSUE TITLE
TraceEvent doesn't support loading symbols on Linux

### ISSUE THREAD

**Issue by clguiman** [microsoft/perfview#1832]
A call to `Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.GetSourceLine` on Linux will cause the following exception:

> System.DllNotFoundException:` Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory

call stack:

> Microsoft.Diagnostics.Tracing.TraceEvent.dll!NativeDlls.LoadLibraryEx(String lpFileName, IntPtr hReservedNull, LoadLibraryFlags dwFlags)
> Microsoft.Diagnostics.Tracing.TraceEvent.dll!NativeDlls.LoadNative(string simpleName)	C#
> Microsoft.Diagnostics.Tracing.TraceEvent.dll!Dia2Lib.DiaLoader.GetDiaSourceObject()	C#
> Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Symbols.NativeSymbolModule.NativeSymbolModule(Microsoft.Diagnostics.Symbols.SymbolReader reader, string pdbFilePath, System.Action<Dia2Lib.IDiaDataSource3> loadData)	C#
> Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Symbols.SymbolReader.OpenSymbolFile(string pdbFilePath)	C#
> Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.OpenPdbForModuleFile(Microsoft.Diagnostics.Symbols.SymbolReader symReader, Microsoft.Diagnostics.Tracing.Etlx.TraceModuleFile moduleFile)	C#
> Microsoft.Diagnostics.Tracing.TraceEvent.dll!Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.GetSourceLine(Microsoft.Diagnostics.Symbols.SymbolReader reader, Microsoft.Diagnostics.Tracing.Etlx.CodeAddressIndex codeAddressIndex)	C#

Can the TraceEvent library add support for symbols on linux? Probably that will only include portable pdbs.

**Comment by pharring** [comment]
TBH, I didn't realize we were close to getting TraceEvent working on Linux.

In this case, I think it's as straightforward as adding:
```csharp
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
   ...
}
```
at the appropriate place in SymbolReader.cs (Microsoft.Diagnostics.Symbols.SymbolReader.OpenSymbolFile)

**Comment by clguiman** [comment]
I don't know if it's true for all other features, but the symbols loading was the only issue I encountered when trying to process a trace.
