### ISSUE TITLE
Question-TraceEvent: How to get Win10 Patchlevel on Win10v1703 - Build 15063?

### ISSUE THREAD

**Issue by MagicAndre1981** [Microsoft/perfview#184]
In the creators Update v1703 Build 15063, installing an cumulative update rollup [no longer updates](https://aka.ms/v6rjlo) the `BuildLabEx `value. It is always `15063.0.amd64fre.rs2_release.170317-1834` / `15063.0.x86fre.rs2_release.170317-1834`.

So when I capture a Trace with WPR.exe and use TraceEvent to parse it, subscribe to kernelTraceEventParser.SysConfigBuildInfo Event I only get the default Buildlab with the .0 instead of the expected Patchlevel .250 from [April 2017 Rollup KB4016240](https://support.microsoft.com/en-us/help/4016240/windows-10-update-kb4016240).

So I can no longer use this to group my trace according to a Patchlevel.

I see that there is a value `UBR` under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion` which shows the patchlevel, but I have no idea if WPR exposes that data if my Profile captures those meta events:

```
<TraceMergeProperties>
      <CustomEvents>
          <CustomEvent Value="ImageId"/>
          <CustomEvent Value="BuildInfo"/>
          <CustomEvent Value="VolumeMapping"/>
          <CustomEvent Value="EventMetadata"/>
          <CustomEvent Value="PerfTrackMetadata"/>
          <CustomEvent Value="NetworkInterface"/>
      </CustomEvents>
    </TraceMergeProperty>
```

and how to parse it with TraceEvent.

Next I tried to get the FileVersion data for the ntoskrnl.exe from source.Kernel.ImageGroup / symbolParser.ImageIDFileVersion Eventhandlers, but this fails. I see all DLLs loaded, but I never got the Event for Kernel exe.

Does anyone have any idea?

**Comment by MagicAndre1981** [comment]
I noticed that PerfView shows it for processid 0 - Idle:
`
    <Event MSec= "67964,2564" PID=   "0" PName=    "Idle" TID="6772" EventName="ImageID/FileVersion" ImageSize="0x0088A000" TimeDateStamp="0x58F6FD47" OrigFileName="ntkrnlmp.exe" FileDescription="NT Kernel &amp; System" FileVersion="10.0.15063.250 (WinBuild.160101.0800)" BinFileVersion="10.0.15063.250" VerLanguage="1033" ProductName="Microsoft® Windows® Operating System" CompanyName="Microsoft Corporation" ProductVersion="10.0.15063.250" `

But this  FileVersion="10.0.15063.250 **(WinBuild.160101.0800)**" is also confusing as hell. I see  **(WinBuild.160101.0800)** for all Windows files, no matter which FileVErsion they have:

![grafik](https://cloud.githubusercontent.com/assets/8274816/25837563/bd504f10-348e-11e7-96ab-db5f5eb90733.png)

**Comment by vancem** [comment]
I don't have useful advice for you.   Certainly the ImageID/FileVersion event is where I would expect such information you have already figured that out.

**Comment by MagicAndre1981** [comment]
ok, after several trial & error I'm able to get the version for kernel. I need to run several passes and after 1st full pass I got the data, so first I tried to use data before the parse even got thwm. It would be still nice if capturing BuildInfo `<CustomEvent Value="BuildInfo"/>`would read the `UBR` value from registry and include it in the trace and if TraceEvent would parse it in `kernelTraceEventParser.SysConfigBuildInfo` .

**Comment by MagicAndre1981** [comment]
the BuildLab gets updated now again for 16299/17134/17763. Looks like someone at Microsoft now noticed this issue and requested the change.
