### ISSUE TITLE
Tuturial 2 - called methods RecSpin RecSpinHelper not showing on stacks

### ISSUE THREAD

**Issue by jiruss** [microsoft/perfview#1865]
I am trying to follow through tutorial 2 but when I view the call stacks using Top Down or Bottom Up approach, none of the managed methods except for the call to tutorial!Program.Main are showing up. I have tried this on multiple machines and get the same result. The tutorial does not mention setting any extra collection options that I can see so I am at a loss as to why I cannot see the managed methods that are taking the CPU time.

Here you can see what my Callers tree looks like
![PerfViewTutorial2-Issue](https://user-images.githubusercontent.com/20343098/235959980-97a4d015-40f3-4095-8aad-1659133446d6.png)

The same view from the Tutorial correctly shows the SpinForASecond, RecSpinHelper and RecSpin child methods 
![PerfViewTutorial2-Issue2](https://user-images.githubusercontent.com/20343098/235960908-ec0f3bdc-298a-41b5-8268-776f2bf974f8.png)

**Comment by Xhanti** [comment]
See https://github.com/microsoft/perfview/issues/1723

**Comment by jiruss** [comment]
@Xhanti can you be more specific. I do not see anything relevant in #1723 to my issue.

**Comment by jiruss** [comment]
Ok I have figured out the issue. It was due to the GroupPats being set to [group module entries]  {%}!=>module $1 (which comes up by default).

I changed it to [Just My App]           \ver.2023-04-13.03.40.38.000\%!->;!=>OTHER and now it is working the same as in the tutorial video.
