### ISSUE TITLE
Support for new PGO features coming in .NET 8

### ISSUE THREAD

**Issue by AndyAyersMS** [microsoft/perfview#1866]
.NET 8 will introduce two new tiering levels for methods:
* tier0 (aka quick jit) code + instrumentation
* tier1 code + instrumentation

Along with this we should update the user's guide to accurately reflect the various tiering and pgo config settings and how they can impact app behavior.

https://github.com/microsoft/perfview/blob/570cc0364c7e2407222f84600aebb9d9cb2f6007/src/PerfView/SupportFiles/HtmlReportUsersGuide.htm#L204-L218

**Comment by brianrob** [comment]
@AndyAyersMS thanks.  I am doing a bit of searching, but I don't see anywhere that we emit the tier for methods when they get jitted.  Do you know if there is an event that does this that I'm missing?  Right now, jitstats states whether or not a method is compiled by tiered compilation by looking at the tiered compilation events, but these events aren't method specific.

**Comment by AndyAyersMS** [comment]
It is encoded in the flags for the MethodLoad event:

https://github.com/microsoft/perfview/blob/564309807cb280823377db4e6fc24a1aeae34a90/src/TraceEvent/Parsers/ClrTraceEventParser.cs#L11349-L11365

https://github.com/microsoft/perfview/blob/564309807cb280823377db4e6fc24a1aeae34a90/src/TraceEvent/Parsers/ClrTraceEventParser.cs#L13110-L13128

I can send a PR to update the enum, that part is simple enough.
