### ISSUE TITLE
Reduce memory pressure from TraceGarbageCollector in real-time streaming scenarios

### ISSUE THREAD

**Issue by ryandle** [microsoft/perfview#1873]
Opening this after having a conversation with @Maoni0 

The `TraceEventSession` class supports a way to easily hook into parsed GC event data via the `TraceLoadedDotNetRuntime.GCEnd` event. This what tools like [RealMon ](https://github.com/Maoni0/realmon) use for live streaming of GC events.

One issue I noticed when trying to build my own real-time GC event streaming tool is that the internal `TraceGarbageCollector` class keeps an ever-growing list of all `TraceGC`s that have happened so far. For a long-lived process that wants to monitor GC events, this creates significant memory pressure as it grows without bound.

One idea for solving this would be to add a way to configure TraceGarbageCollector such that it doesn't keep a list of `TraceGC`s - this is useful for the real-time scenario where a subscriber wants to know about a GC event once and not again after that.

In the meantime, one workaround for others hitting this would be to periodically restart the `TraceEventSession`. The downside to this (besides being a general extra thing to maintain) is that you may miss events unless you carefully manage the restart.

**Comment by jeffschwMSFT** [comment]
You should be able to do this via the Lifetime tracking built into the GC collector: https://github.com/microsoft/perfview/blob/a79143be3467ae0dd221c481ba65d24917b48455/src/TraceEvent/TraceEvent.cs#L310

**Comment by ryandle** [comment]
@jeffschwMSFT thanks! That looks viable. Will give it a try.

**Comment by jeffschwMSFT** [comment]
For realtime streaming, another great tool is the dispatchhook.  You can use this to pre-filter what events are allowed for processing or discarded.

https://github.com/microsoft/perfview/blob/a79143be3467ae0dd221c481ba65d24917b48455/src/TraceEvent/TraceEvent.cs#L3313

This filter may only allow events from a given process, etc.  The dispatch hook can help reduce volume.

**Comment by ryandle** [comment]
Setting `TraceEventSource.DataLifetimeMsec` addresses my issues - memory use stays relatively constant now and is no longer expanding without bound. Thanks a lot @jeffschwMSFT for the suggestion!

I marking this item as closed.
