### ISSUE TITLE
Lost events due to setting EnableSourceContainerTracking

### ISSUE THREAD

**Issue by ms-hujia** [microsoft/perfview#1877]
I use `TraceEventSession` to collect ETW events generated by `EventSource` running in container. The observed issue is:
1. PerfView will prompt lost events during opening the ETL file even if I increase all the buffer size. There is no schema for the collected ETW events.
2. If I removed the flag `EnableSourceContainerTracking`, everything works as expected.

Could you help with this issue, thanks!

**Comment by brianrob** [comment]
We should track this in https://github.com/dotnet/runtime/issues/87255
