### ISSUE TITLE
Use a single ETW session to collect data on Windows 8 and above

### ISSUE THREAD

**Issue by vancem** [Microsoft/perfview#189]
In Windows 7, kernel events could only be collected in a special Kernel session.   Conversely, when you capture non-kernel events it CANNOT be in a kernel session.   This means that PerfView (which needs both), has to have two sessions (which mean two files), that have to be merged. after the trace completes.  

Having two files (sessions) is ugly when the buffer is circular because it it means that WINDOW for kernel events and user mode events are different.  This can cause confusing interpretations when the analysis needs BOTH events to work properly (GC tracking is the most common example).    It is also wasteful (since any place where you are only collecting one is basically wasted, as it is incomplete).   

We can fix this by simply using one session when we can (on windows 8 and above).   

Note that I would like the code for this to be organized such that all the OLD (ugly) code is together so it can be chucked when we don't care about Win7 anymore (it reduces the complexity for anyone who does not care about this old stuff). 

I can give additional guidance as needed.   Please don't do too much work without checking with me first.

**Comment by vancem** [comment]
Ack, I created a duplicate of this issue.   The new issue has a bit more detail than this one, so I am closing this one.

**Comment by sharwell** [comment]
Duplicate of #549
