### ISSUE TITLE
TraceEvent.SupportFiles: Missing version on nuget.org 1.0.25

### ISSUE THREAD

**Issue by bruno-garcia** [microsoft/perfview#1900]
`perfview` specifies version 1.0.25 of Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles
https://github.com/microsoft/perfview/blob/4fb9ec6947cb4e68ac7cb5e80f50ae3757d0ede4/src/Directory.Build.props#L36

But NuGet only has u to 1.0.23. Which matches the `nuspec` on this repo:

https://github.com/microsoft/perfview/blob/4fb9ec6947cb4e68ac7cb5e80f50ae3757d0ede4/src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec#L5

I found a script that copies files from the package itself: 

https://github.com/microsoft/perfview/blob/4fb9ec6947cb4e68ac7cb5e80f50ae3757d0ede4/src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat#L10-L11

But not much more in terms of publishing a new version. Am I missing something? Should 1.0.25 be available somewhere?

**Comment by brianrob** [comment]
These packages now get posted to a different feed.  See NuGet.config: https://github.com/microsoft/perfview/blob/main/Nuget.config#L9C19-L9C19.

This is because there is a security desire for all Microsoft projects to consume Microsoft feeds.  These are publicly available though, so you should be able to consume them in your builds.

**Comment by bruno-garcia** [comment]
@brianrob not related to this issue but: These DLLs that are not open source and not available in the public nuget.org. What's the situation with redistributing them? This repo is MIT but those deps are not?

**Comment by brianrob** [comment]
This delves into an area that I'm not an expert in.  I know that some of the DLLs have EULAs associated with them that specify redistriibution limitations.  For example Microsoft.Diagnostics.Tracing.TraceEvent.AutomatedAnalysis.Analyzers has a EULA that only allows it to be consumed by PerfView: https://dotnet.microsoft.com/en-us/perfview_library_license.htm.
