### ISSUE TITLE
Unable to install tools on Ubuntu 20.04 and arm64

### ISSUE THREAD

**Issue by cincuranet** [microsoft/perfview#1902]
When running `perfcollect /install` on Ubuntu 20.04 on `arm64` the installation fails because it can't find `linux-cloud-tools-5.15.0-79-generic`. [Looks like](https://packages.ubuntu.com/focal/linux-cloud-tools-5.15.0-79-generic) this package is available only for `amd64`.

It is coming from [this line](https://github.com/microsoft/perfview/blob/main/src/perfcollect/perfcollect#L1105).

Here's the output:
```text
perflocal@dotcjade-16:~$ sudo ./perfcollect install
Installing perf_event packages.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-cloud-tools-5.15.0-79-generic
E: Couldn't find any package by glob 'linux-cloud-tools-5.15.0-79-generic'
E: Couldn't find any package by regex 'linux-cloud-tools-5.15.0-79-generic'
LTTng already installed.
perflocal@dotcjade-16:~$ uname -a
Linux dotcjade-16 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:24 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by brianrob** [comment]
Thanks @cincuranet.  Do you get a helpful error message if you run `perf` from the command line?  That might help to figure out what we need to do.

**Comment by cincuranet** [comment]
Not sure I follow. You mean this:

```text
perflocal@dotcjade-16:~$ perf

Command 'perf' not found, but can be installed with:

sudo apt install linux-tools-common                    # version 5.4.0-162.179, or
sudo apt install linux-oem-5.6-tools-common            # version 5.6.0-1017.17
sudo apt install linux-intel-iotg-5.15-tools-common    # version 5.15.0-1038.43~20.04.1
sudo apt install linux-iot-tools-common                # version 5.4.0-1021.22
sudo apt install linux-nvidia-tegra-5.15-tools-common  # version 5.15.0-1016.16~20.04.1
```

**Comment by cincuranet** [comment]
I tried removing the offending package from `perfcollect` script. As expected, the installation succeeds. I can then execute `perf` command. I can use `perfcollect collect` and the trace file seems to be having expected data when dumped using `babeltrace`. 

This begs the question, whether `linux-cloud-tools-xyz` is really needed? :)

**Comment by brianrob** [comment]
Thanks @cincuranet.  Can you confirm that this change also works on x64?  If it does, then completely reasonable to remove it.

**Comment by cincuranet** [comment]
All on x64:
*  `5.4.0-150-generic #167~18.04.1-Ubuntu`: Installs, runs and collects fine without the offending package.
* `5.15.0-83-generic #92~20.04.1-Ubuntu`: Installs, runs and collects fine without the offending package.
* `6.2.0-32-generic #32~22.04.1-Ubuntu`: Installs, runs and collects fine without the offending package.

I'll prepare PR to update the `perfcollect` script.
