### ISSUE TITLE
Machine-wide focused on new instances, ignoring existing instances

### ISSUE THREAD

**Issue by indy-singh** [microsoft/perfview#1909]
Context: https://github.com/dotnet/aspnetcore/issues/50317#issuecomment-1713809066

Scenario:-

Let's say we have nine existing w3wp.exe's running, and we are about to start a tenth instance. I want to tell PerfView to ignore the existing PIDs but capture any new instances we may spin up from that point. I would pass the existing PIDs using:-

```powershell
Get-Process "w3wp" | Select-Object -Property Id
```

This is what our current invocation looks like:-

```powershell
$dateTimeString = (Get-Date -Format o | ForEach-Object { $_ -replace ":", "." });
& C:\PerfView\PerfView.exe "/DataFile:C:\PerfView\$dateTimeString.etl" "/LogFile:C:\PerfView\$dateTimeString.log" "/BufferSizeMB:256" "/StackCompression" "/CircularMB:256" "/MaxCollectSec:150" "/KernelEvents:None" "/NoGui" "/FocusProcess:`"w3wp.exe`"" "/NoNGenRundown" "/onlyProviders=clrPrivate:0:Informational:@EventIDsToEnable=`"80 88 112`"" "/Zip:false" "/AcceptEULA" "collect"
```

Is that possible?

Cheers,
Indy

**Comment by brianrob** [comment]
There is not currently a way to say "look at new instances of a particular process, but not existing ones".  If it helps, you can use the Processes view to see which processes started during the trace.  Would that work?

**Comment by indy-singh** [comment]
Hi @brianrob.

That's a shame, we are currently using the Processes view/filter to narrow down what we care about.

It would be good if this could be added as a feature request. It's not a showstopper, but it would improve the experience.

Cheers,
Indy
