### ISSUE TITLE
Using /dumpheap with /nogui or /logfile results in hang

### ISSUE THREAD

**Issue by mahamr** [microsoft/perfview#1913]
We had a customer run into this issue (using the latest, though based on what I see in code it probably will happen with any version) - you can repro it by running the below command:
`PerfView.exe  "/DataFile:PerfViewData.etl" /BufferSizeMB:256 /StackCompression /DumpHeap /nogui collect`

The command works fine if removing /DumpHeap, or if leaving that but allowing it to pop the GUI instead of not. I believe I have the correct analysis below of the behavior.

The command above results in the below output, and hangs here indefinitely:
```
VERBOSE LOG IN: PerfViewData.log.txt
EXECUTING: PerfView /DataFile:PerfViewData.etl /BufferSizeMB:256 /StackCompression /DumpHeap /nogui collect

Pre V4.0 .NET Rundown disabled, Type 'E' to enable symbols for V3.5 processes.
Do NOT close this console window.   It will leave collection on!
Type S to stop collection, 'A' will abort.  (Also consider /MaxCollectSec:N)
Kernel Log: C:\Windows\System32\PerfViewData.kernel.etl
User mode Log: C:\Windows\System32\PerfViewData.etl
Starting collection at 9/19/2023 10:46:04 AM
Manually Stopped (NoGui)
```

I captured a dump and this is the main thread's stack:
```
09 mscorlib_ni!System.Threading.WaitHandle.WaitOne
0a PerfView!PerfView.CommandProcessor.GuiHeapSnapshot
0b PerfView!PerfView.CommandProcessor.Stop
0c PerfView!PerfView.CommandProcessor.Collect
0d PerfView!PerfView.CommandProcessor.ExecuteCommand
0e PerfView!PerfView.App.DoMain
0f PerfView!PerfView.App.Main
```

This looks to be the code here:
https://github.com/microsoft/perfview/blob/v3.1.5/src/PerfView/CommandProcessor.cs#L1901
```
        public void GuiHeapSnapshot(CommandLineArgs parsedArgs, bool waitForCompletion)
        {
#if !PERFVIEW_COLLECT
            // We'll wait on this handle until the heap snapshot completes.
            ManualResetEvent waitHandle = new ManualResetEvent(false);

            if (GuiApp.MainWindow != null)
            {
                GuiApp.MainWindow.Dispatcher.BeginInvoke((Action)delegate ()
                {
                    GuiApp.MainWindow.TakeHeapShapshot((Action)delegate ()
                    {
                        // Set the wait handle once the memory heap snapshot has been completed.
                        // This action will run in the memory dialog continuation.
                        waitHandle.Set();
                    });
                });
            }

            if (waitForCompletion)
            {
                **waitHandle.WaitOne();**
            }
#endif
        }
```

When running the app via command line, with /NoGui or /LogFile, it appears this GuiApp.MainWindow property is not set:
```
0:000> !DumpClass /d 00007ffb9937ec68
Class Name:      PerfView.GuiApp
...
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffb99399b58  40003de      258  PerfView.MainWindow  0   static 0000000000000000 MainWindow
```

Thus, it appears the ManualResetEvent is instantiated and waited on, but will never be Set() since the setting code is inside a block that will not execute if the MainWindow is null.

**Comment by brianrob** [comment]
@mahamr thank you very much for reporting this, and for the analysis.  It looks like the heap snapshot functionality in place here doesn't support capture via GUI.  I'm planning to emit a warning in this case and proceed to stop collection.
