### ISSUE TITLE
Task Field of Individual Events not Correctly Set

### ISSUE THREAD

**Issue by sgrottel** [microsoft/perfview#1928]
This seems like a simple bug to fix.

We use ETLs in our project, recorded at multiple systems, processed and analyzed by self-written tools. We use the "Task" field of the event headers to group events of various types semantically during the analysis. While the results look correct in WPA, the task field is not correctly updated when loading the ETL with the `Microsoft.Diagnostics.Tracing.TraceEvent` library.

I wrote a small console app (c++ emitting events), record it as ETL (attached), and a console app (c#) loading the events with your library to repro the issue:
https://github.com/sgrottel/etl-demo

![image](https://github.com/microsoft/perfview/assets/13036832/e2056107-6b52-495f-b2b6-9135416046f7)
Works in WPA (top half).
Console app using TraceEvent Library does not work (lower half).

Debugging the TraceEvent Library revealed the inconsistency when dispatching the event (from the correctly selected template) to the callbacks:
![image](https://github.com/microsoft/perfview/assets/13036832/689eaf4a-48f0-4791-9462-39f33dd849d0)
First line in the "watch" window on the left shows the `Task` value in the original EventHeader.
Second line shows the not updated `Task` property in the Event object which is dispatched to the callbacks.

Generated ETL file repro'ing the issue:
[etl-demo.etl.zip](https://github.com/microsoft/perfview/files/12929028/etl-demo.etl.zip)

I got a simple fix working, just setting the `task` field, similar to the `eventRecord` and `userData`.
I'll setup a pull request.

**Comment by brianrob** [comment]
Fixed via #1977.
