### ISSUE TITLE
Versioning information in docs verification

### ISSUE THREAD

**Issue by cincuranet** [microsoft/perfview#1947]
Is the "Release Notes" paragraph in https://github.com/microsoft/perfview/blob/main/documentation/TraceEvent/TraceEventLibrary.md still correct? Looks like starting with v3 the versions are in sync and released together (no "T" or "V" version numbers).

**Comment by brianrob** [comment]
You are correct - starting with V3, this is no longer correct.

**Comment by cincuranet** [comment]
Thanks. Created PR #1950 to fix that.
