### ISSUE TITLE
Since 3.1.6 PerfView never quits

### ISSUE THREAD

**Issue by rauhs** [microsoft/perfview#1957]
Had this since 3.1.6 (3.1.5 is OK):

I start perfview. I quit (Pressing "X" top right).

It closes, but the process doesn't quit. It stays open in the task manager.

It's just staying forever at:

```
UnsafeNativeMethods.GetMessageW()
Dispatcher.GetMessage()
Dispatcher.PushFrameImpl()
Application.RunDispatcher()
Application.RunInternal()
App.DoMainForGui()
App.DoMain()
App.Main()
```

Possibly related: 0a090aff1e36c81cf1bc2297c0fe53e187d0db67?

**Comment by cincuranet** [comment]
Confirmed. I can replicate it. 

The 0a090af seems like a good suspect. On the other hand it fixed stability when running tests, so I don't want to just revert it. Let me see what we can do about it.

**Comment by brianrob** [comment]
Yeah, this is my fault - I missed that this call to `Exit` was in product code and not test code.  I'm wondering if we can detect that we're running under test.

**Comment by cincuranet** [comment]
@brianrob No problem. I missed it as well. #1960 is an as clean as I can think of attempt to solve it.
