### ISSUE TITLE
What's the purpose of `updatePerfView.exe`?

### ISSUE THREAD

**Issue by cincuranet** [microsoft/perfview#1968]
What's the purpose of [`updatePerfView.exe`](https://github.com/microsoft/perfview/blob/main/src/updatePerfView.exe) in this repo?

**Comment by MagicAndre1981** [comment]
looks like a legacy tool to update Perfview when it was an internal project inside Microsoft:

`public string TargetDir = "\\\\clrmain\\d$\\public\\tools";`

**Comment by brianrob** [comment]
That's exactly right.  No longer needed, and can be deleted.
