### ISSUE TITLE
Implement an object finalization tree view

### ISSUE THREAD

**Issue by sharwell** [microsoft/perfview#201]
This tree would allow the user to see how many objects of each type are getting finalized by each process. This would be a histogram on the process and type for the events described in #200.

I managed to extract this information manually using a pivot table in excel and looking up all the type names I could find in the **Microsoft-Windows-DotNETRuntime/GC/AllocationTick** event, but it was slow, painful, and missing a great number of type names.

**Comment by stephentoub** [comment]
Just to clarify, you mean a tree view instead of or in addition to the table / Excel export it currently can generate?

**Comment by sharwell** [comment]
@stephentoub If you are referring to the table on the GCStats page, yes. I'm not sure how that table works exactly, but it appeared to be very limited in its ability¹ and I question its accuracy². 

¹ There is no ability to restrict the results to a particular range of time, and the results are not available unless a special mode is enabled. Why are the results not available from just the **FinalizeObject** event?

² The results do not at all align with information observed in the Events table for the FinalizeObject event described in #200.

**Comment by vancem** [comment]
Note that the current logic in the GCStats view works with the PRIVATE event (see my comment in #200 for more on ClrPrivate events).     

As suggested in #200, we could fix this by making the FinalizeObject event 'smart'  enough to use rundown information to look up the TypeName from the TypeId    When that is done we should also fix the GCStats view to use this new information.   

That would probably be sufficient to fix this issue.     I am hesitant to introduce new views that are truly new, so we should evaluate after that if the Events view and the GCStats view (and maybe some doecs) would be sufficient.   We may also wish to have a link on (either in the file view or in the GCStats view), that opens the 'Events' view with the proper filtering to make that discoverable.

**Comment by sharwell** [comment]
@vancem The reason I was suggesting a new view is the following:

1. The GCStats view buckets events by process (good), but doesn't allow filtering the view to a specific start/stop point. The latter limitation would prevent me from using this view in a meaningful way during the investigation of a recent regression (it's linked above).
2. The Events view shows individual events, but it doesn't show a histogram. If the Events view were modified to allow a "group by" setting on one or more columns, it could certainly serve this purpose. Note that in the event too many event instances match the current filter, the group headings would need to show the number of visible events in the group, and the total number of events in the group.

For example, if we Group By: TypeID, you might have this:

* 0x00000001 (3 of 1005 events shown)
  * Event 1
  * Event 2
  * Event 3
* 0x0029993a (400 of 1000 events shown)
  * Event 5
  * Event 6
  * ...

**Comment by vancem** [comment]
The group-by feature in the events view has been brought up previously, and is interesting, but is a non-trivial feature.     The work-around currently (which is really not bad at all), is to select the time range, process, and data columns of interest, open the view in Excel (right click open view in excel), and use excel's pivot tables (Insert -> Pivot table),  which gives you the full power of Excel to manipulate the data.

**Comment by sharwell** [comment]
The workaround is less convenient when there is not enough space on the analysis machine to install Excel. 😆 

If it's easy to implement a new "fixed" tree view, I may do that first and then come back around to implementing a more flexible Group By feature. If it's similar work either way then the intermediate step wouldn't provide much short-term value.

**Comment by brianrob** [comment]
Per @vancem's recommendation above of using the events view and Excel, closing this issue.  It is possible to take the file generated by PerfView and move it to a different machine, or just open the trace file directly on a separate machine to avoid the installation issue.
