### ISSUE TITLE
.nuspec dependencies

### ISSUE THREAD

**Issue by filipnavara** [microsoft/perfview#2016]
The latest version of the NuGet updated the dependencies which results in some incompatibility with the WinFroms out-of-process designer. That's likely an issue with the designer but I noticed that now the dependencies include `Microsoft.NETCore.Portable.Compatibility` version 1.0.2. That version is unlisted in the NuGet gallery. Is it intentional to use that version? If yes, why is it unlisted?

/cc @brianrob

**Comment by brianrob** [comment]
Thanks for reporting this @filipnavara.  This looks like a super old dependency that is not relevant anymore.  I'm not sure why it was unlisted.  I think we were just getting away with the fact that it never got restored until we fixed up the NuGet dependencies.

Either way, I've posted #2017 to remove the dependency.

**Comment by filipnavara** [comment]
Thanks for quick fix!
