### ISSUE TITLE
Vulnerability in the dependency tree

### ISSUE THREAD

**Issue by lidvarko** [microsoft/perfview#2032]
There is a vulnerability in the library dependency tree. system.net.request 4.3.0 has a dependency to system.net.http 4.3.0 that has a High severity vulnerability.

**Comment by SymbioticKilla** [comment]
You mean system.net.http?It is a transient, but it is annoying... 

Is it possible to lock system.net.request to 4.3.4?
Thanks!

![image](https://github.com/microsoft/perfview/assets/59652865/86934c69-f639-40d2-9f42-d4733762fdb4)

**Comment by MagicAndre1981** [comment]
@brianrob why does TraceEvent still require those old .net Standard 1.x libs when the TraceEvent lib is [.net standard 2.0](https://github.com/microsoft/perfview/blob/0a35b99ccf10559c4e85b55584a4f31ee375c217/src/TraceEvent/TraceEvent.csproj#L5)?

For example System.Diagnostics.Process is part of [.net standard 2.0](https://apisof.net/catalog/04e6b2f8f1d604fe13d58e6d09909d50?fx=netstandard2.0)

![image](https://github.com/microsoft/perfview/assets/8274816/5afc29a5-234c-43c8-bbfd-ed929b41e8ac)

and only required for .net standard 1.x projects which doesn't apply to TraceEvent

![image](https://github.com/microsoft/perfview/assets/8274816/f0041c62-dfd4-4bea-b5a8-b7ea290db6b4)

Best is to remove all those old ns1.x support libs.

**Comment by brianrob** [comment]
That's a goodo callout @MagicAndre1981.  I've posted #2037 for this.
