### ISSUE TITLE
Support New Cloud-Based Symbol Server

### ISSUE THREAD

**Issue by brianrob** [microsoft/perfview#2034]
Support Microsoft's new cloud-based symbol server.

**Comment by MagicAndre1981** [comment]
are there any public information available about this new symbol server?

**Comment by brianrob** [comment]
@MagicAndre1981, no, there isn't any public information.  This is a Microsoft-internal symbol server.  We'll want to add support for this, but it will only be applicable to Microsoft employees.

**Comment by MagicAndre1981** [comment]
ok, thanks

**Comment by brianrob** [comment]
Fixed via #2039.
