### ISSUE TITLE
Nuget package 3.1.13 fails to declare dependency

### ISSUE THREAD

**Issue by cg110** [microsoft/perfview#2070]
The 3.1.13 nuget package for Microsoft.Diagnostics.Tracing.TraceEvent fails to declare it has a dependency on Microsoft.Diagnostics.NETCore.Client

The dependency was added in:
https://github.com/microsoft/perfview/commit/c847ec9392312c6159434cd87312040170303a35
and shows up as a dependent dll when examining referenced dlls in nuget package explorer (along with any other tooling that walks referenced dlls to confirm all needed dlls are present):
![image](https://github.com/user-attachments/assets/7348efa9-5f91-4708-bc26-1d4d3faf6580)

I'm not sure it's needed at runtime, but the reference is there, suggesting it is needed.

**Comment by brianrob** [comment]
Thanks for reporting this @cg110.  I had noticed this during code review, but only got part of the fix in.  I've posted #2071 to finish it up.  Unless you're using EventPipe streaming support, you should be fine, and won't see the new DLL get loaded.

**Comment by cg110** [comment]
Great thank you.
