### ISSUE TITLE
TextEditorWindow: resizing moves the text around too much

### ISSUE THREAD

**Issue by BruceForstall** [microsoft/perfview#213]
When choosing "Goto Source (Def)", by default a small TextEditorWindow is opened with the output. First, the default size is too small (IMO). Second, when resizing this window, the original line of focus (presumably the line with the highest hit count of events) becomes lost. Presumably this is because wrapped lines become not wrapped, and the "line to display" gets messed up. Sometimes it's hard to find where that line of focus disappeared to.

**Comment by brianrob** [comment]
Fixed via #219.
