### ISSUE TITLE
Split TraceLog.cs into one file per type

### ISSUE THREAD

**Issue by sharwell** [microsoft/perfview#225]
@vancem I'm finding it challenging to review and work with **TraceLog.cs** in its current form. Since there are no outstanding PRs that touch this file, may I split it (just this file) and submit a PR that has one type per file? The contents of this file are already placed in a dedicated namespace so these files would remain grouped together after the change.

:memo: I would not reformat the contents of these files as part of this PR. It would be a content preserving split.

**Comment by vancem** [comment]
Can you describe the value of splitting?   I have worked in code bases that follow the one type per file convention and I did not see obvious value.   Perhaps the biggest value in the current approach is that the file acts as a 'semantic group', and give you and obvious place to put comments about the semantic group as a whole.   This is not a huge advantage (you can accomplish this with directories (although the discoverablity of a starting point for documentation is not quite so good), I don't think I would want to do this convention elsewhere (for example a TraceEventParser has many types in it, and there is value in having all these related things in the same file).    This leads me looking for a proper philosophy of when to do it and when not to, which prompts my question.

**Comment by sharwell** [comment]
> Can you describe the value of splitting?

1. It works well with split views in Visual Studio. You can split items contained in one file, but it's not as efficient.
2. Smaller files perform better in the IDE, and improve the behavior of several smaller features (e.g. code maps in the scroll bar).
3. It makes this page wonderful to use (_much_ better than the search feature): https://github.com/Microsoft/perfview/find/master

> Perhaps the biggest value in the current approach is that the file acts as a 'semantic group', and give you and obvious place to put comments about the semantic group as a whole.

This is one of the benefits of namespaces, and you actually are using namespaces this way as well.

> This leads me looking for a proper philosophy of when to do it and when not to, which prompts my question.

For top-level types, the easiest way to look at it is one type per file with no exceptions. Everything just comes together cleanly when you do this.

* Make sure folder names match the namespaces of content
* Make sure file name matches the name of the contained type

For nested types, I typically either use one file for the top-level type _or_ I will make it a partial class and use one file for each nested type. Things are only confusing if you try to mix items or partially implement separation.

**Comment by sharwell** [comment]
> for example a TraceEventParser has many types in it

It appears these are generated code. If that is truly the case, then they would be exempt from this.

**Comment by vancem** [comment]
Let me consider this.   I am out of the office on Friday and Monday, so there may be a delay.

**Comment by brianrob** [comment]
At this point, this sounds mostly like a style preference.  Given that, we are going to close this issue.
