### ISSUE TITLE
Why is ClrPrivate excluded from the NuGet build?

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#230]
I noticed that the use of `ClrPrivate` in the TraceEvent library is guarded by a [`#if !NUGET`](https://github.com/Microsoft/perfview/blob/9efe7571d92c54dab0687ae85478562f5db9c0d5/src/TraceEvent/TraceLog.cs#L774-L776) directive. Why is this? Is there any harm in unconditionally including this code?

**Comment by vancem** [comment]
This #if def is not longer useful.  PR #506 removes it.
