### ISSUE TITLE
InitialTime in ISR/DPC events incorrectly decoded

### ISSUE THREAD

**Issue by lowleveldesign** [Microsoft/perfview#234]
I want to use ISR/DPC events to measure Windows drivers performance. Unfortunately, I run into problem when decoding the **InitialTime** property from the **ISRTraceData** (I haven't yet tested DPC events, but the problem might be the same). An example ISR event looks as follows as dumped by the TraceEvent library:

```
<Event MSec=    "19,1574" PID=  "-1" PName="Process(-1)" TID=  "-1" EventName="PerfInfo/ISR"
  TimeStamp="05.20.17 23:36:22.959108" ID="Illegal" Version="2" Keywords="0x00000000" TimeStampQPC="1 996 631 531 786"
  Level="Always" ProviderName="Windows Kernel" ProviderGuid="9e814aad-3204-11d2-9a82-006008a86939" ClassicProvider="True"
  Opcode="67" TaskGuid="ce1dbfb4-137e-4da6-87b0-3f59aa102cbc" Channel="0" PointerSize="8"
  CPU="0" EventIndex="3646" TemplateType="ISRTraceData">
  <PrettyPrint>
    <Event MSec=    "19,1574" PID=  "-1" PName="Process(-1)" TID=  "-1" EventName="PerfInfo/ISR" InitialTime="03.01.1601 08:27:43" Routine="0xFFFFF8069EA8F310" ReturnValue="1" Vector="97"/>
  </PrettyPrint>
  <Payload Length="20">
       0:  ef 60 83 e0 d0  1  0  0 | 10 f3 a8 9e  6 f8 ff ff   .`...... ........
      10:   1 61  0  0             |                           .a..
  </Payload>
</Event>
```
As you can see the InitialTime value is set to *03.01.1601 08:27:43* (which seems to be a DateTime built from the first 8-bytes of the payload: `[DateTime]::FromFileTime(0x000001d0e08360ef)`). When I dumped the same .etl file to the .xml format using tracerpt this event has the following data:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Guid="{9e814aad-3204-11d2-9a82-006008a86939}" />
		<EventID>0</EventID>
		<Version>2</Version>
		<Level>0</Level>
		<Task>0</Task>
		<Opcode>67</Opcode>
		<Keywords>0x0</Keywords>
		<TimeCreated SystemTime="2017-05-20T23:36:22.959108900+0159" />
		<Correlation ActivityID="{00000000-0000-0000-0000-000000000000}" />
		<Execution ProcessID="4294967295" ThreadID="4294967295" ProcessorID="0" KernelTime="0" UserTime="0" />
		<Channel />
		<Computer />
	</System>
	<EventData>
		<Data Name="InitialTime">131397897829590968</Data>
		<Data Name="Routine">0xFFFFF8069EA8F310</Data>
		<Data Name="ReturnValue">1</Data>
		<Data Name="Vector">97</Data>
		<Data Name="Reserved">0</Data>
	</EventData>
	<RenderingInfo Culture="pl-PL">
		<Opcode>ISR</Opcode>
		<Provider>MSNT_SystemTrace</Provider>
		<EventName xmlns="http://schemas.microsoft.com/win/2004/08/events/trace">PerfInfo</EventName>
	</RenderingInfo>
	<ExtendedTracingInfo xmlns="http://schemas.microsoft.com/win/2004/08/events/trace">
		<EventGuid>{ce1dbfb4-137e-4da6-87b0-3f59aa102cbc}</EventGuid>
	</ExtendedTracingInfo>
</Event>
```
And the InitialTime value is equal to 131397897829590968, which seems to be a valid FileTime value: 
```
PS temp> "{0:dd.MM.yyyy HH:mm:ss.fffffff}" -f [DateTime]::FromFileTime(131397897829590968)
20.05.2017 23:36:22.9590968
```
I was not able to figure out the transformation they make in tracerpt, but my guess is that we are missing something in the TraceEvent library.

**Comment by vancem** [comment]
I have pushed a fix for this.  #234 Basically these events now have an 'ElapsedTimeMsec' property, which the the time the DPC or ISR took.    You can get the start time by simply subtracting this from the TimeStampMsec property, but typically you want the elapsed time.

**Comment by vancem** [comment]
I have not created a new build, but you can do so to get a fixed PerfView.  If that is a hardship I will see about making a new release.      Right now getting a signed TraceEvent nuget package is a problem but I can get you an unsigned one with the fix relatively easily (although again, you can build the TraceEvent DLL yourself.

**Comment by lowleveldesign** [comment]
@vancem thank you for the fix and you are right that it's the elapsed time I'm interested in. I wish I would have figured it out by myself, without bothering you, but I took a completely wrong assumption that the field in the payload must be of a FileTime type. I will do the build on my own - no problem.

**Comment by vancem** [comment]
Logging an issue here was the right thing to do.   I should have responded to it earlier, but I am having problem with PerfView notifications going to my spam filter and I did not see it until recently.   Good luck
