### ISSUE TITLE
SetTimeRange does not work when digit grouping symbol is space

### ISSUE THREAD

**Issue by ilabutin** [Microsoft/perfview#235]
Suppose my regional settings have space as a grouping character:

![image](https://cloud.githubusercontent.com/assets/1869103/26284805/2bbf868e-3e4c-11e7-8e7a-20d93a25ce02.png)

Then in the Stacks view times are formatted accordingly:

![image](https://cloud.githubusercontent.com/assets/1869103/26284797/0201ef26-3e4c-11e7-9253-241dc0df26a4.png)

When Set Time Range is executed the result is bad (although predictable):

![image](https://cloud.githubusercontent.com/assets/1869103/26284820/9cf1dd20-3e4c-11e7-8856-7728eb6d2e62.png)

And Copy Time Range also formats full time range with space in between:

![image](https://cloud.githubusercontent.com/assets/1869103/26284818/8e9c5c6e-3e4c-11e7-8132-0ee88b9ede81.png)

Does PerfView just use space to separate Start and End values?

Is it something that is only in use internally by PerfView? If this is true, then it should not be too difficult to fix (I can try to).

**Comment by sharwell** [comment]
> And Copy Time Range also formats full time range with space in between:

What is the expected behavior here?

**Comment by ilabutin** [comment]
>> And Copy Time Range also formats full time range with space in between:

>What is the expected behavior here (I'm not familiar enough to know)?

Well. If this functionality were intended only for putting time range into the clipboard, then I would be fine with something like `(0,000;71 837,297)`. Or just split by semicolon (I'm not sure, though, that semicolon is not used in some culture as a decimal or group separator).

But I guess that the main use case for this functionality (as per PerfView help) is to paste the result into the Start text box to set the same range into the different view. If you paste a range, PerfView is clever enough to understand that the first number should be Start and the second one should be End.

**Comment by sharwell** [comment]
@ilabutin Thanks for the update. It was actually pretty easy to correct this locally, but I spent a fair amount of additional time trying to take things a bit farther and implement a true unit test for this. It's going to take a bit longer before it's ready to submit as a pull request but I wanted to give you a quick update on the progress.
