### ISSUE TITLE
Question - TraceEvent: How to detect if a .net process is AnyCPU or real 64Bit?

### ISSUE THREAD

**Issue by MagicAndre1981** [Microsoft/perfview#281]
Is it possible to detect with TraceEvent if a process in an ETL is compiled as AnyCPU?

To see if a process is 64Bit I use the KernelTraceEventParserOnImageGroup event and check if ImageBase >= 0x100000000 so it is 64Bit (but I'm not sure if this is really correct). But this still doesn't tell me if the process is really 64Bit/x64 compiled or set as AnyCPU.

Any ideas?

**Comment by sharwell** [comment]
A 64-bit image loaded from an AnyCPU binary _is_ part of a "real" 64-bit process. You could always look at the binary on disk to see? I believe the System.Runtime.Metadata package or similar offers tools that could help, though the actual solution may be easier if this is the only data you're trying to extract.

**Comment by MagicAndre1981** [comment]
I want to get this information from an ETL. not from a exe file on disk.

**Comment by sharwell** [comment]
This is outside the areas I know about with ETL processing, but @vancem should know how to answer. Do you need to know this information just for the main executable, or for each assembly loaded by the executable? For example, an X86 or X64 executable can load an AnyCPU assembly, and vice-versa, so the process include assemblies loaded with multiple settings as long as none of them are conflicting.

**Comment by MagicAndre1981** [comment]
I would like to know this for a list of DLls/exe files that belong to my solution.

When I compile the whole solution for Any CPU and capture a trace, I often run into the issue that the trace misses a lot of events, which I don't see if I compile it as x86/x64. So I want to do testings and need to know from the ETL if my project is AnyCPU or x86/x64 to compare why I get the issues with AnyCPU.

**Comment by vancem** [comment]
The closest thing I know of in the ETL file that does what you want is to look at the 'ImageBase' field for the DLL in the Windows Kernel/Image/Load or Windows Kernel/Image/DCStop events.    This field is the address where the DLL would like to be loaded in memory, and for 'ANyCPU it MUST be a 32 bit number, but for true PE-64 format it will be something much larger (typically 0x7ffeXXXX0000).   This is likely to work well enough for your purpose.  

> When I compile the whole solution for Any CPU and capture a trace, I often run into the issue that the > trace misses a lot of events, which I don't see if I compile it as x86/x64

This is quite surprising.   

Vance

**Comment by MagicAndre1981** [comment]
this works "ok". Is there also a way to difference between Any CPU and x86? Both have 32bit ImageBase 

Currently I think of sending the result of

```csharp
var assembly = Assembly.GetExecutingAssembly();
PortableExecutableKinds peKind;
ImageFileMachine machine;
assembly.ManifestModule.GetPEKind(out peKind, out machine);
```
via my own event. This code give me the same information like Gflags.exe.

**Comment by vancem** [comment]
I don' think there is anything in current ETW events that let you distinguish between AnyCPU and x86.

**Comment by MagicAndre1981** [comment]
ok, I used the code from my last comment and raised my own events.

But it is still confusing that the .net provider doesn't log such information by default and other data like if release or debug mode.
