### ISSUE TITLE
Incorrect assembly location used in NativeDlls

### ISSUE THREAD

**Issue by ig-sinicyn** [microsoft/perfview#292]
[NativeDlls.cs](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/NativeDlls.cs#L18):
```c#
        var thisDllDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().ManifestModule.FullyQualifiedName);
```

the `ManifestModule` does not work for shadow copied dlls (e.g. for code being run by test engines). 
Path returned is `%temp%\%some_mangled_path%` and the LoadLibrary fails as there is no KernelTraceControl.dll

It looks the code is used [from multiple places](https://github.com/Microsoft/perfview/search?utf8=✓&q=GetExecutingAssembly().ManifestModule&type=) so there should be helper for it:)

I'd recommend to use `assembly.CodeBase` to locate the initial directory of the assembly. Part of our code doing the same task:
```cs
		private  static string GetAssemblyPath([NotNull] this Assembly assembly)
		{
			// DONTTOUCH: we cannot use Location to detect the path as it may refer to shadow-copied assembly.
			// DONTTOUCH: at the same time we cannot check CodeBase as it may refer to the loader codebase:
			//   If the assembly was loaded as a byte array, using an overload of the Load method that takes an array of bytes,
			//   this property returns the location of the caller of the method, not the location of the loaded assembly.
			// (c) https://msdn.microsoft.com/en-us/library/system.reflection.assembly.codebase(v=vs.110).aspx
			if (assembly.Location.IsNullOrEmpty())
				throw CodeExceptions.Argument(nameof(assembly), $"Assembly {assembly} has no physical code base.");

			var uri = new Uri(assembly.CodeBase);
			if (uri.IsFile)
				return uri.LocalPath;

			throw CodeExceptions.Argument(nameof(assembly), $"Assembly '{assembly}' has no local path.");
		}
```

Can this be fixed and pushed to `Microsoft.Diagnostics.Tracing.TraceEvent` package in near future? 🙏

**Comment by vancem** [comment]
This is the kind of thing that I would want a clean (hopefully simple) explanation why we think the new mechanism is the 'right' answer.    My understanding of shadow copying is to avoid locking DLLs (so they can be updated), but if you load from the original location you subvert that.    Maybe that is OK but it does not inspire confidence.     Sigh, I need to think about it...

Just FYI, note that even assuming I quickly agree that we should fix this, we are not at the moment set up to generate signed copies of the TraceEvent package.   This is likely to take a while (days to weeks), to resolve.   Thus if you just need the DLL that is one thing, if you need a signed official package, that is going to take longer.

Finally, can you describe the scenario where shadow copying is used?   

Vance

**Comment by sharwell** [comment]
> Finally, can you describe the scenario where shadow copying is used?

Some unit test libraries, including but not limited to xunit, shadow copy DLLs by default for testing. This can be disabled, as seen in Microsoft/vs-threading#104 or by [passing `-noshadow`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/66ef515d1babc4f52700e2ae5410f1fb1984c12a/appveyor.yml#L13) to the console runner.

**Comment by vancem** [comment]
> Some unit test libraries, including but not limited to xunit, shadow copy DLLs by default for testing. This can be disabled, as seen in Microsoft/vs-threading#104 or by passing -noshadow to the console runner.

I want to understand the scenario a bit more.  I certainly can understand how TraceEvent might be used by the harness, but I would not have expected HARNESS dlls to need the shadow copying since they 'never' change as testing proceeds (I would have only expected DLLs under test to be shadow copied).  

Am I missing something?

**Comment by ig-sinicyn** [comment]
@sharwell, @vancem thanks for quick answers:)

First, I've just workarounded the issue by copying native dlls into the shadow copy directory. So it is not blocker for us anymore and I will be happy with any approach you will take:)

Second, about my scenario. I have a pet project, performance testing framework driven by BenchmarkDotNet. I'm playing with various performance metric providers and I'm very interested in adding ETW tracing support as it will cover must of metrics I'm going to collect.

As a public library, the perf test framework have no control over environment it will be run and therefore it should work with Visual Studio test runner, ReSharper test runner, nUnit/xUnit/MsTest runners and so on. And if one of them uses shadow copying the library should not require disabling it.

**Comment by ig-sinicyn** [comment]
> My understanding of shadow copying is to avoid locking DLLs (so they can be updated), but if you load from the original location you subvert that.

Well, I've missed that:) 
I do agree the solution should be smart and the "just load it" approach will kill entire idea of shadow copying. On the other side, the runtime itself does not use shadow copying for native dlls so I'm guessing this is not a major issue.

**Comment by brianrob** [comment]
Reviewing this issue, the fundamental problem is that the native DLLs don't get copied as part of a shadow copy.  That said, we don't want to load the non-shadow copied version, as that breaks the approach of shadow copying.  I suspect the answer here is that this needs to be resolved outside of TraceEvent - specifically, the code that uses TraceEvent will need to copy the native binaries if they are needed.  I realize this is not an idea solution, but I don't think there is a clear path forward here.

Closing based on this feedback.
