### ISSUE TITLE
PerfView hangs opening GC Heap Net Mem Stacks

### ISSUE THREAD

**Issue by AArnott** [microsoft/perfview#309]
When you open this file: "\\andarno1\public\dumps\MemTrack5.etl.zip" (MSFT corpnet required)
and try to open "GC Heap Net Mem Stacks", PerfView 1.9.55 just hangs (asynchronously) for many minutes, ignores the Cancel button, and I finally have to kill the process.

Collection steps:

```
git clone https://github.com/microsoft/vs-threading
cd vs-threading
git checkout 2b8208ce
cd src\Microsoft.VisualStudio.Threading.Tests
MSBuild /t:restore
MSBuild 
```

Collect->Run
Command: `C:\Users\andarno\.nuget\packages\xunit.runner.console\2.2.0\tools\xunit.console.exe f:\git\threading\bin\Microsoft.VisualStudio.Threading.Tests\Debug\net452\Microsoft.VisualStudio.Threading.Tests.dll -method Microsoft.VisualStudio.Threading.Tests.AsyncSemaphoreTests.NoLeakForContestedRequests_ThatAreEventuallyAdmitted`
"No V3.X NGEN Symbols": unchecked
".NET Alloc": checked
all other settings at their defaults.

**Comment by sharwell** [comment]
Thanks, taking a look at this one now

**Comment by sharwell** [comment]
@AArnott The changes made in the build in #307 allow me to open the trace. It takes 49 seconds from when I double click GC Heap Net Mem to when the Select Process dialog appears, and then another 6 seconds to show the window when I click All Processes. Resolving this issue would involve two things:

1. Determine if the changes required to fix this are already in the master branch (e.g. part of #192 or #298)
2. If the fixes are not already in master, try to figure out which specific item(s) in my working branch resulted in such an improvement

**Comment by brianrob** [comment]
@AArnott I'm walking through all of the PerfView issues.  I tried to load the trace file you referenced above but the machine doesn't appear to be accessible anymore.  I'm sure this is because the issue is quite old.  Do you still encounter this issue?

**Comment by AArnott** [comment]
I actually deleted old files such as this one just a couple weeks ago. I haven't seen this repro in any case since then, so I'll close the issue. Thanks for checking.
