### ISSUE TITLE
OSExtensions should be unencrypted

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#320]
Currently the OSExtensions library is included in this repository, but only in a form that external users cannot see. This has two major problems:

1. The compiled binary itself is not obfuscated, so the code is trivially seen in disassembled form
2. The lack of clear source code appears to be a deviation from the license terms for this repository, which state that the contents are MIT-licensed and do not make an exception for the code in the OSExtensions directory

It is my understanding that the terms of the repository license already provide sufficient protection against misuse of the code in the indicated library.

**Comment by vancem** [comment]
Note that OSExtensions is not part of the PerfView build.   It is a binary that is part of the support DLLs as a separate package that PerfView simply depends on and is not covered by the license.    If push were to come to shove, we would probably simply remove everything about OSExtensions from the public repo, but that would make it much more likely that over time we would lose track of the ability to update that DLL, which would be unfortunate.
