### ISSUE TITLE
Disabling TplEtwProvider during a Collect

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#326]
I'm trying to Collect a trace from a section of code that reports a scary large number of events when TplEtwProvider is enabled. I'd like to start a data collection with the following settings, except that I want TplEtwProvider events disabled.

1. Is there any way to do this from the UI?
2. Is there a way to do this from the command line?

![image](https://user-images.githubusercontent.com/1408396/28683590-bbd5f6a0-72c6-11e7-92e3-ba5dd34d54bc.png)

:memo: My current approach is temporarily using a build with [these lines](https://github.com/Microsoft/perfview/blob/2ea34bb2bf658e0ca902efadc465a93e7d39b7cb/src/PerfView/CommandProcessor.cs#L572-L575) commented out, but I'm hoping this issue can better help other users who encounter similar situations. :smile:

**Comment by vancem** [comment]
Yes, there is a way to to both.   In general if you don't like the default events that PerfView turns on you have two options:

First, (which also happens to be the most straightforward), is that any addition providers you put in the 'AdditionalProviders' (or /Providers command line option), are set AFTER all the default ones, which means you can set them to something else.   

Setting a provider to keywords=0 level = 0 is interpreted by PerfView as disabling the provider.  Thus

adding the following to the 'Additional Providers'  (or the /Providers command line option) 

    .NETTasks:0:0 

will disable the  .NETTask (which is the TPL provider). 

Note that you can do this to any of the other providers perfVIew turns on by default.  The perfVIew log shows you exactly which providers PerfView is turns on so you can turn them off if you wish.  

Having said this, it would not be hard to add another checkbox to control this.  Sadly TPL events are verbose enough that it is not uncommon to want to turn them off.   If anyone wants to do this, I would be happy to approve it.
