### ISSUE TITLE
TraceParserGen?

### ISSUE THREAD

**Issue by rovarma** [Microsoft/perfview#336]
In the docs for TraceEvent, the TraceParserGen tool is referenced as a way to generate parsers for custom events. This seems useful, but I'm unable to find it in the repository. Is the tool (or its source) available somewhere?

I've found older copies [here](https://github.com/alex-mtx/traceparsergen) and on [OneDrive](https://onedrive.live.com/?id=D068505F1C71AB61%21124&cid=D068505F1C71AB61), but I'm not sure what the state of these are.

Thanks!

**Comment by vancem** [comment]
The copy on the OneDrive is the latest.   It has not changed in quite a while.   The other is a fork but I don't know anything about it.     

Moving it to this repo is interesting if someone wants to make a PR for it.   The one-drive thing predated the PerfView git repository.

**Comment by rovarma** [comment]
Alright, thanks. I have done so here: https://github.com/Microsoft/perfview/pull/344.

**Comment by vancem** [comment]
Resolved by #344..   Thanks @rovarma  for doing this.

**Comment by vancem** [comment]
TraceParseGen source lives in the PerfView GitHub. 

https://github.com/Microsoft/perfview/tree/master/src/TraceParserGen

You can build it simply by doing 'msbuild' in the TraceParserGen directory.   The binary ends up in bin\Debug\TraceParserGen.exe

Simple cases are simple:  TraceParserGen <manifest file> will generate a  *.cs file that has the parser for that manifest.   However there are many manifests that use unusual types or formats that will confuse the parser generator (but you can usually just skip out the bad code and use what is left, it just won't parse every event from the manifest).   

TraceParserGen /? will give you some useful help.   In particular it will tell you the two most common ways of getting manifest that you feed to it.

  OS providers can be listed using 'logMan query Providers' and a manifest obtained by doing

  * PerfView /nogui userCommand DumpRegisteredManifest PROVIDER_NAME

  EventSource manifests can be obtained from an ETL file containing EventSource data using

  * PerfView /nogui userCommand DumpEventSourceManifests etlFileName

  If the DLL containing the EventSource is available, TraceParserGen can use it directly with the /EventSource qualifier.
