### ISSUE TITLE
Event Filtering for private event tracing sessions.

### ISSUE THREAD

**Issue by Botldoiz** [Microsoft/perfview#339]
I am trying to collect events from a private event tracing session (because I only need the data from the process where the provider is running). to minimize the event overhead I also tried to apply an event filter to the provider (via the "Additional providers" field) to only collect certain events but if I do so, ERROR_INVALID_PARAMETER (code 87) is returned and perfview crashes. According to MSDN event filtering should be available for private mode event tracing, or have I been missing something?
Command of the Additional Providers field:
Microsoft-Windows-DotNETRuntime:GCKeyword:Informational:@EventIDsToEnable=1

I have also asked the question on TechNet, but unfortunately there is still no response.
TechNet link for detailed information:
[TechNet link](https://social.technet.microsoft.com/Forums/en-US/73c11628-404c-4ccf-b654-7dd3ec2c66d9/event-tracing-for-windows-enabling-event-filtering-for-private-usermode-etw-sessions-returns?forum=perfmon)

**Comment by vancem** [comment]
As you have already determined, this is mostly a question about ETW, not TraceEvent/PerfView.   I could easily believe that event filtering does not work with private sessions (or not), I just don't know.  

However, if your goal is to simply get GC events from the .NET Runtime, normal keywords/level is enough to probably get something that is good enough.   (if you only want GC events, use GC keyword and level == Informational, and that gets rid of the high volume ones (Allocation Tick).  It will be fine...

**Comment by Botldoiz** [comment]
Thank you for your response,
unfortunately all events with the GC keyword are informational, so this is not an option to get rid of the high volume events, like the Allocation Tick events. 

Best regards

**Comment by vancem** [comment]
> unfortunately all events with the GC keyword are informational

This is simply incorrect.   In particular the AllocationTick event IS Verbose, and it is quite common to turn the verbosity down to Informational to exclude it.

**Comment by Botldoiz** [comment]
You were totally right. After some testing i found out that the AllocationTick is one of the verbose events.  I thought it was an informational event because it is declared as informational on [MSDN](https://docs.microsoft.com/en-us/dotnet/framework/performance/garbage-collection-etw-events).
