### ISSUE TITLE
Could we have only trace data module separate from perfview app?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/perfview#343]
I write dotnet application and want to profile it with perfcollect. But I have no windows machine in my workplace so I can't use perfview to open trace file

So could you please split the core trace analyzer into dotnet core package so we will be able to recreate perfview in other platform?

**Comment by vancem** [comment]
It is already the case that much of the logic for working with traces is in the Microsoft.Diagnostics.Tracing.TraceEvent.dll that is built when you build the TraceEvent directory in PerfView.   This code is mostly platform neutral and we have at least a protototype that works on .NET COre (which runs on linux(see PR #315).

Indeed we have even gone quite a bit further and have prototoyped a HTML based version of PerfView that would work on all platforms.  This too is checked in   (See the HTMLJS directory in the repo)   Basically there is a service that can read data files and do all the stack processing and provide a REST api for displaying the stacks.  There is some javaScript then that talks to this REST API and readers it as HTML.   The idea is that you could [electron](https://en.wikipedia.org/wiki/Electron_(software_framework)) to simply make it look like an app (that runs anywhere).    The developer who worked on it to day has moved on, but at some point we will pick it up again and make progress (if anyone is interested in it let me know).
