### ISSUE TITLE
Scripts should not modify the NuGet packages cache directly

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#368]
Commit ab6d715d2df53545084534a8748871a021ad9e83 modified the **PerfView.SupportFiles.Populate.bat** script in a manner that corrupts the central NuGet packages cache for a user. No script in the repository should directly modify the contents of the NuGet packages cache.

:memo: Found during an audit since I just returned from vacation. This issue tracks finding an alternative solution (no immediate proposal).

**Comment by vancem** [comment]
This script does not modify the Nuget package cache, it copies things from it (it is cloning parts of the existing package to form a template for the new package. 

It would be nice to not have a dependency on the location of the Nuget cache, but it is not clear it is worth the effort.

**Comment by sharwell** [comment]
> This script does not modify the Nuget package cache, it copies things from it

Yep, I misread, thanks!
