### ISSUE TITLE
Does OSExtensions need the ComVisible and Guid assembly attributes?

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#369]
Commit cdfd4139c2d5c9a0499aa4ba16f7c264cd191e38 removed the **AssemblyInfo.cs** file altogether. Most of the attributes are replaced by build support from the new SDK, but the `ComVisible` and `Guid` attributes are not included in this. Do these attributes need to be included in this assembly or can they be omitted from future builds?

**Comment by vancem** [comment]
I don't believe either of these attributes are needed.   OSExtensions uses no COM nor does it provide COM interfaces.   Basically it is a wrapper over flat Windows APIs, and flat APIS supported by KernelTraceControl.dll
