### ISSUE TITLE
Review disabling CS1591

### ISSUE THREAD

**Issue by sharwell** [microsoft/perfview#370]
Commit 52d4bb27f743b2c461a853569385646c51d39bb9 disables CS1591 within individual files, but we also have a broad exclusion here:

https://github.com/Microsoft/perfview/blob/fbca7255dc5c3f78e2c5e5d33ce29001f8c99f50/src/Directory.Build.props#L32

:memo: This was found during an audit returning from vacation, and is a tracking issue to consolidate these exclusion mechanisms.

**Comment by brianrob** [comment]
@sharwell, I'm not concerned about this one, but am happy to take a fix for this.  I'll put this on the backlog - feel free to bring a PR for this.
