### ISSUE TITLE
Update  IisTraceEventParser Keywords

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/perfview#377]
The IisTraceEventParser's Keywords is empty now. Need to update it with the following list.

// IIS: WWW Server {3A2A4E84-4C21-4981-AE10-3FDA0D9B0F83}

            // Value               Keyword              Description
            // ------------------------------------------------------------------------------ -
            // 0x0000000000000001  UseUrlFilter         Allow tracing only selected requests
            // 0x0000000000000002  IISAuthentication    IIS authentication events
            // 0x0000000000000004  IISSecurity          IIS security events
            // 0x0000000000000008  IISFilter            IIS filter events
            // 0x0000000000000010  IISStaticFile        IIS static file events
            // 0x0000000000000020  IISCGI               IIS CGI events
            // 0x0000000000000040  IISCompression       IIS compression events
            // 0x0000000000000080  IISCache             IIS cache events
            // 0x0000000000000100  IISRequestNotification IIS request notifications events
            // 0x0000000000000200  IISModule            IIS module events
            // 0x0000000000001000  IISFastCGI           IIS FastCGI events
            // 0x0000000000002000  IISISAPI             IIS ISAPI events
            // 0x0000000000004000  IISWebSocket         IIS WebSocket events
            // 0x0000000000000000  IISGeneral           IIS general events
            // 0x0000000000004ffe  IISAll               IIS all events

**Comment by vancem** [comment]
Fixed by #381
