### ISSUE TITLE
Enable all TraceEvent Asserts for EventPipe

### ISSUE THREAD

**Issue by vancem** [Microsoft/perfview#387]
Currently there is something called DebugListenerBlock in the EventPipeParsing.cs tests for EventPipe.  

This class is designed to suppress assertions while the test is running.  This was because previously EventPipe would emit junk at the end of an event and cause many asserts to fire.   

Supressing asserts  is  hack.   With https://github.com/dotnet/coreclr/pull/14049 it should be the case that this extra space is no longer emitted.   Thus it should be possible to remove the assert supression, at least after the traces used in the tests have been updated.

Sadly it is not trivial to emit old formats that have been fixed.  Thus we will need to keep the supression around for V1 format testing, but other than that we can remove it.

**Comment by nategraf** [comment]
There is another assert as well, here https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/TraceLog.cs#L8322

I can take on looking into that if that'd be fruitful.

**Comment by vancem** [comment]
That assert is surprising to me.    It is simply saying that that there should be a entry in the list of all modules for every file that we have a file path for.   It should be true based on the code just above it (since we only add things to moduleFilesByName if we have already added it to moduleFiles.   

I would suggestion commenting it out temporarily just to see what is beyond it.

**Comment by vancem** [comment]
Looking at the code, it is more subtle, because there is a 'SetModuleFileName' which also updates one of the tables.   You can look if you want, but I am happy to look at it if you check in a file that I can use to run tests.

**Comment by vancem** [comment]
The evil DebugListenerBlock  has been removed.   I am now happy
