### ISSUE TITLE
.Net Garbage Collector  GCStats  %GC column always has value NaN

### ISSUE THREAD

**Issue by Izison** [microsoft/perfview#412]
I am collecting GC Stats for IIS process.  (customer is complaining about high values of performance counter "GC Time Spent %") I wanted to analyse what is going on. During online investigation I have found PerfView tool. I want to see same pairing of performance counter values with something more detailed data-set provided by PerfView tool. What should I look in PerfView to see around 50 % counter values.

![image](https://user-images.githubusercontent.com/32955881/31816630-5a75d19c-b591-11e7-81c3-cd6ff645ec4e.png)

Are above 2 columns right thing to look at ? 

![image](https://user-images.githubusercontent.com/32955881/31816733-bf4ceeac-b591-11e7-8c3c-d84c3db8ccdf.png)

Is there any correlation between performance counter(Time % in GC) and some information inside PerfView tool ?  What this metric actually represent? 
How to set PerfView collection settings to obtain values that can be paired/compared/paralleled with performance counter ?

**Comment by sharwell** [comment]
When using `/GCOnly`, CPU time is not recorded so all processes appear as total elapsed time 0. The column ends up evaluated as 0.0/0.0=NaN. If you enable CPU sampling (without `/GCOnly`), you should see a value for this column.

Note that the ability to show GC *pause* times is not impacted by this limitation.

**Comment by brianrob** [comment]
@sharwell is correct.  The calculation requires the amount of CPU time for the process which isn't collected with `/GCOnly` or `/GCCollectOnly`.
