### ISSUE TITLE
Make stacks more user-friendly

### ISSUE THREAD

**Issue by ilabutin** [microsoft/perfview#447]
Now that we have excellent library to make stacks more readable (https://github.com/benaadams/Ben.Demystifier) wouldn't it be good idea to implement something similar to be used in PerfView to fold stacks to hide e.g. some internal async/TPL stuff?

I realize that we cannot use this library directly as most (if not all) metadata is not present in the PerfView trace, but maybe some tricks can be applied to make stacks more user-friendly?

Most likely this should be optional, though, to enable profiling internal stuff as well.

**Comment by vancem** [comment]
Certainly a lot can be done to make stacks more friendly.   I would be supportive of this.   As you mention, I would want the option of turning it off, but that should not be hard.

**Comment by ilabutin** [comment]
Now that I'm 'done' with initial presets implementation (PR submitted), I'd like to look into this one. I know I can fold away all internals by folding everything in .NET assemblies, but in my scenarios I am actually interested in the stacks from inside .NET framework itself, but some things are producing too much noise.

I'd like to approach this by several steps and start with removal of async/await (and TPL) machinery. Namely, I'd like to have following methods folded by default:

- Task<>.InnerInvoke
- Task.ExecuteWithThreadLocal
- Task.Execute
- Task.ExecutionContextCallback
- Task.ExecuteEntry
- Task.InnerInvoke
- ExecutionContext.RunInternal
- ExecutionContext.Run
- ExceptionDispatchInfo.Throw
- For types: TaskAwaiter, TaskAwaiter<>, ConfiguredTaskAwaitable.ConfiguredTaskAwaiter and ConfiguredTaskAwaitable<>.ConfiguredTaskAwaiter do not show following methods:
    - HandleNonSuccessAndDebuggerNotification
    - ThrowForNonSuccess
    - ValidateEnd
    - GetResult
- Also fold all methods from System.ThrowHelper

@vancem what do you think? And what would be the proper place to put an option to turn this off? Some global option in the View menu (common for all opened stack windows)?

The next thing I'd like to understand is how to recalculate stack so that async methods show methods they await as a child (something that Visual Studio team recently did). I see that ActivityComputer already knows about async/await and the events that allow one to glue two stacks, but as far as I understand this is not what applied in CPU Stacks window where I'd like it to be. Could you give a guide here - am I missing something or is that something to be developed if I like it to be visible in CPU Stacks window?

**Comment by vancem** [comment]
> The next thing I'd like to understand is how to recalculate stack so that async methods show methods they await as a child (something that Visual Studio team recently did). 

This is what the 'Thread Time' views do.   In particular the 'Thread Time with Start-Stop Activities' is the view you want (if you only want CPU, then you can simply filter to only include stacks with CPU_TIME' in them).  

This view also folds much of the Task machinery by default as you want.   Tweeking these defaults  is certainly possible.

**Comment by ilabutin** [comment]
> This is what the 'Thread Time' views do. In particular the 'Thread Time with Start-Stop Activities' is the view you want (if you only want CPU, then you can simply filter to only include stacks with CPU_TIME' in them).
Yes, that's true. But 'Thread Time' view only show up when I enable "Thread time" collection. Normally I'm not interested in thread time collection, but want Task machinery folding.

The only Task-enabled view without enabling 'Thread time' checkbox  is 'Any TaskTree' which is not very helpful for typical CPU investigation.

Also I'm fine with standard Tasks (created via Task.Run, etc) show up as separate stacks. It's only async/await default folding that I'd like to happen.

What would be your suggestion here? Do you see any good changes that can be done to make 'CPU Stacks' view more friendly while not transferring all the 'Thread time' functionality to it?

**Comment by vancem** [comment]
The trivial recommendation is to simply use ThreadTime.   

It is possible show the ThreadTime views without having the context switch information.   It then just shows you basically the CPU view.   There is an existing view called 

* ASP.NET Thread Time (with Tasks) (CPU ONLY)

That does this.   The underlying ThreadTime computer 'just works' without the Context Switch.   Thus having  'Thread Time with Start-Stop Activities (CPU ONLY)'  could be interesting (it is a minor change (see the ASP.NET one above).

**Comment by vancem** [comment]
See PR #609.   Please try it out, if you believe it is useful we can add some docs and check it in.

**Comment by ilabutin** [comment]
I tried it and it's great - almost what I wish for.
There are two issues though.
1. 'STARTING TASK' entry also has AWAIT_TIME which is contributed to the parent, thus the total time is not CPU-only anymore. See screenshot:
![image](https://user-images.githubusercontent.com/1869103/37620364-0c657662-2bcd-11e8-9440-b30197b6b4cb.png)

2. Is it possible to rename STARTING TASK into e.g. ASYNC_AWAIT when task was really a scheduled continuation by async/await pattern? I see that TraceActivity has 'kind' field which might help here, but it belongs to TraceEvent library which I'm not sure how to approach.

@vancem

**Comment by ilabutin** [comment]
@vancem Sorry to disturb, but do you think this is something that can be done quickly? I'm mostly interested in solving issue 1 (not counting AWAIT_TIME into parent).

**Comment by vancem** [comment]
Sorry for letting this languish.

Just so you know, you can of course eliminate the AWAIT_TIME by excluding that name in the 'Exc Pats' or better, requiring 'CPU_TIME' to be in every stack (thus you see only CPU).

But I agree that having the AWAIT_TIME In there is probably more confusing that valuable, so I will see what we can do to eliminate it.  

On the second issue (ASYNC_AWAIT), it may be possible (some experimentation would be needed.    Most of the time we fold away STARTING TASK anyway, so making two things that we fold way by default just adds more complexity.   Can you describe the value of the distinction?

**Comment by ilabutin** [comment]
> On the second issue (ASYNC_AWAIT), it may be possible (some experimentation would be needed. Most of the time we fold away STARTING TASK anyway, so making two things that we fold way by default just adds more complexity. Can you describe the value of the distinction?

I thought it might be valuable to see whether it was async/await-generated task or manual task from code. But I have now used this for some time and it does not look like it brings lots of value. So as long as you can see how AWAIT_TIME can be eliminated it should be enough for most common use.
@vancem

**Comment by ilabutin** [comment]
Unfortunately it does not work. Following is written in the log:
```
Completed: Opening Thread Time (with StartStop Activities) (CPU ONLY) Stacks   (Elapsed Time: 0,063 sec)
Exception Occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Diagnostics.Tracing.StartStopActivityComputer..ctor(TraceLogEventSource source, ActivityComputer taskComputer) in d:\oss\perfview\perfview\src\TraceEvent\Computers\StartStopActivityComputer.cs:line 39
   at Microsoft.Diagnostics.Tracing.ThreadTimeStackComputer.GenerateThreadTimeStacks(MutableTraceEventStackSource outputStackSource, TraceEvents traceEvents) in d:\oss\perfview\perfview\src\TraceEvent\Computers\ThreadTimeComputer.cs:line 152
```

The reason seems to be that your new condition (`m_traceHasCSwitches`) leaves `m_activityComputer` uninitialized and thus `StartStopActivityComputer` can't be created since it accepts instance of ActivityComputer as a second argument.

@vancem

**Comment by vancem** [comment]
See updated PR #609

**Comment by brianrob** [comment]
It sounds like PR #609 addresses this issue.  I'm going to close this, but if I've missed something, please re-open.  Thanks.
