### ISSUE TITLE
Assertion in `SessionEndTime` fails on computer with Danish culture (UTC+1)

### ISSUE THREAD

**Issue by mikkelbu** [Microsoft/perfview#448]
The assertion `Debug.Assert(SessionStartTime <= ret)` fails on a computer with Danish culture and UTC+1. The problem is that `SessionStartTime` has already been converted to local time, but `ret` has not, hence `SessionStartTime` will be approx 1 hour larger in the comparison.

**Comment by vancem** [comment]
Fixed by PR #451
