### ISSUE TITLE
EventPipeEventSource needs to support x86 traces

### ISSUE THREAD

**Issue by nategraf** [microsoft/perfview#470]
With https://github.com/dotnet/coreclr/pull/14772 EventPipe will work on x86 Windows and therefore TraceEvent should recognise and read x86 traces generated by EventPipe

https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/EventPipe/EventPipeEventSourceV1.cs#L26

**Comment by vancem** [comment]
Nate, can you provide a *.netperf file?

**Comment by adamsitnik** [comment]
@vancem could you add me to the perfview collaborators and assign me to this issue?

**Comment by vancem** [comment]
Done

**Comment by nategraf** [comment]
Here is a trace collected on an x86 Windows build

https://microsoft-my.sharepoint.com/:u:/p/vigraf/EZI2YORpuadIk8Ge4R3NTXEBXbInuMRyY2yszI4C3veYng?e=WgvMri

**Comment by brianrob** [comment]
This was implemented a while back.
