### ISSUE TITLE
Availability of TraceParserGen binaries?

### ISSUE THREAD

**Issue by cristobalito** [Microsoft/perfview#503]
Hi, 

Been searching around for info on how to create my own parser - all paths point to using the TraceParserGen tool, but there appears to be little or no documentation on how to actually get hold of the tool. I note that #336 says that the code has been migrated to GitHub from OneDrive. Looking at the releases seems to suggest it isn't packaged. 

Does that leave compiling from source as the only option? I'm happy to help document the steps if that would be useful, but would appreciate any guidance on where it might live and if somehow packaging the tool is a viable option.

Chris

**Comment by vancem** [comment]
TraceParserGen source does live in the PerfView Repo at https://github.com/Microsoft/perfview/tree/master/src/TraceParserGen.  

 I have updated #336 with some useful information on TraceParserGen at ithttps://github.com/Microsoft/perfview/issues/336#issuecomment-356781249 in particular it tells you the simple way of using it and how to get the manifest you need to feed to it.   The TraceEvent Programmers Guide](https://github.com/Microsoft/perfview/blob/master/documentation/TraceEvent/TraceEventProgrammersGuide.md) also has a section on it.  

Building from the source is easy either use VS on the src\TraceParserGen\TraceParserGen.sln file or type msbuild in that directory.   

Note that finally you may not need a parser.   As mentioned in the [section on Dynamic TraceEvent Parsing(https://github.com/Microsoft/perfview/blob/master/documentation/TraceEvent/TraceEventProgrammersGuide.md#static-vs-dynamic-traceeventparser-parsers) you can parse at runtime (but it is slower and probably not a good idea if you generate > 1K events /sec of that type.  

If there is interest, we can make a release with a TraceEventParser.exe.  It is just that being a dev tool, you are probably already set up to build anyway, so building it yourself is probably just as easy.
