### ISSUE TITLE
Microsoft.Diagnostics.Tracing.TraceEvent is still 1.0.41 on nuget.org

### ISSUE THREAD

**Issue by onyxmaster** [Microsoft/perfview#520]
Despite https://github.com/Microsoft/perfview/releases/tag/T2.0.2 telling that it's published, the https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent/ still contains the 1.0.41 version.

**Comment by MagicAndre1981** [comment]
new version is now up:

https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent/2.0.2

**Comment by onyxmaster** [comment]
Excellent news, thank you!
