### ISSUE TITLE
should Flame Graph merge call stack in different threads?

### ISSUE THREAD

**Issue by sillyousu** [Microsoft/perfview#527]
### scenario:
A  program running identical workload in different threads.

### what did I expect to see
have all identical call stacks  merged. 

### what did I actually see instead
![flamegraph](https://user-images.githubusercontent.com/1446131/35077576-18dfe602-fc39-11e7-806c-6187ab0bdeef.PNG)

**Comment by sillyousu** [comment]
@vancem  @adamsitnik

**Comment by ilabutin** [comment]
FlameGraph is just another way to visualize what you see in CallTree tab. When I wanted to achieve your goal I just added `Thread =>AllThreads` into the `GroupPats` text box and then PerfView grouped all threads. Sometimes I even used `Thread ->AllThreads'.

Be careful and remember to have space after "Thread" and before "=>".

This approach worked, but I wonder if this is the best one.

**Comment by sillyousu** [comment]
@ilabutin  thanks a lot! Now I have a readable flame graph:
![flamegraph2](https://user-images.githubusercontent.com/1446131/35083136-84340fe0-fc58-11e7-8ad5-169ea391b517.PNG)

**Comment by adamsitnik** [comment]
@sillyousu thanks for trying out the Flame Graph! could you close the issue (it looks like solved to me)? 

@ilabutin Igor big thanks for the help!
