### ISSUE TITLE
Renaming unmerged *.etl file does not rename *.clrRundown.etl and *.kernel.etl

### ISSUE THREAD

**Issue by congyiwu** [Microsoft/perfview#552]
1. Collect a PerfView trace w/ Zip and Merge options disabled.  This creates three files:
   * PerfViewData.etl
   * PerfViewData.clrRundown.etl
   * PerfViewData.kernel.etl
2. Right click on PerfViewData.etl in the file tree view, and click Rename
3. Rename to Renamed.etl.

I expected PerfViewData.clrRundown.etl and PerfViewData.kernel.etl to be renamed as well but they were not.

**Comment by vancem** [comment]
Fixed by #559 (you will have to wait for release 2.0.5 or later)
