### ISSUE TITLE
Reviving WpfTraceEventParser

### ISSUE THREAD

**Issue by heeko** [Microsoft/perfview#554]
I'm currently working on consuming ETW events from WPF. In the repository we can find some traces of a "deactivated" WpfTraceEventParser: [TraceLog.cs](https://github.com/Microsoft/perfview/blame/ed9cc8d131564d0a62c2f41a79b51cc67335b17d/src/TraceEvent/TraceLog.cs#L857). 
I suppose it was used back in the days in the WPF performance suite. Is there any plan to revive this parser?

**Comment by vancem** [comment]
I did not realize until just now that WPF does not register its Events by default (you have to explicitly register them).     You can do this by running the following from an admin prompt.
```
wevtutil im C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpf-etw.man
```
At this point you can use the name Microsoft-Windows-WPF to turn on WPF events like this
```
PerfView /Providers=Microsoft-Windows-WPF collect
```
And perfView (via the RegisterTraceEventParser) will correctly parse the events.  

*********************
As with any ETW provider, if you find that you are processing MANY such events, and/or you want compile time support for fetching fields etc, you can make a parser of your own.   

That is what the TraceParserGen tool does (when you build this repository you build TraceParserGen).   See #336 for more on doing that.

*********************
Finally to answer your direct question, there are not plans to revive the WPF parser in the TraceEvent library.   We cleaned out 'little used' parsers from the library on premise that users who needed them could use TraceParserGen to generate them themselves.

**Comment by heeko** [comment]
Thanks a lot for the detailed answer!
