### ISSUE TITLE
System.Exception: 'The kernel provider must be enabled first and only once in a session.'

### ISSUE THREAD

**Issue by sammeboy635** [Microsoft/perfview#591]
//Example from Creators

namespace ConsoleApp4
{
    class Program
    {
        public static TextWriter Out = Console.Out;
        static void Main()
        {
            if (!(TraceEventSession.IsElevated() ?? false))
            {
                Out.WriteLine("To turn on ETW events you need to be Administrator, please run from an Admin process.");
                Debugger.Break();
                //return -1;
            }
            // create a real time user mode session
            using (var session = new TraceEventSession("ObserveProcs"))
            {
                Console.CancelKeyPress +=
                (object s, ConsoleCancelEventArgs args) => session.Stop();
                // Set up Ctrl-C to stop the session
                Console.CancelKeyPress += (object s, ConsoleCancelEventArgs args) => session.Stop();
                Out.WriteLine("1");

                // Subscribe to a callback that prints the information we wish 
                session.Source.Kernel.ProcessStart += delegate (ProcessTraceData data)
                {
                    Console.WriteLine("Process {0} Command Line {1}",
                        data.ProcessName, data.CommandLine);
                };

                // Turn on the process events (includes starts and stops).  
                //var eventSourceGuid = TraceEventProviders.GetEventSourceGuidFromName("MyEventSource"); // Get the unique ID for the eventSouce. 
                //session.EnableProvider(eventSourceGuid);
//Problem code START
                session.EnableKernelProvider(KernelTraceEventParser.Keywords.Registry);
//Problem code END
                session.Source.Process();   // Listen (forever) for events
            }
        }
    }

**Comment by vancem** [comment]
It is not clear what your complaint is.   Does the code as written above (which only enables the kernel provider) fail?   I would hope not.    HOwever if also enable the eventSource, yes, it will fail in the way you describe, but the 'fix' is to enable the eventSource after you enable the kernel provider.   

What exactly is your complaint?

**Comment by sammeboy635** [comment]
Thank you for replying. I'm am Very Sorry for the confusion in what I was looking for. I have no Complaints just a question on how to get that working to filter for only Registry Events.I Pulled this example from a sample code and was trying to learn how I could filter it and got stuck with the exception given at
(session.EnableKernelProvider(KernelTraceEventParser.Keywords.Registry);).
The 'fix' for this problem i'm having could you give some syntax of what is needed to allow for it to run.
 I'm just trying to make data usage model for registry events just FYI in what I'm trying to accomplish.
Thanks again. Really Great Work

**Comment by vancem** [comment]
@sammeboy635 

I would start with the sample code https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/Samples/31_KernelAndClrMonitor.cs 
which turns on Kernel (and also enables the .NET CLR Runtime.   

If all you want is Registry events you remove the EnableProvider call for the CLR.   

To get all the registry events you can do 

session.Source.Kernel.All += Your_Routine and filter them out (e..g _event.Name.StartsWith("Registry").

you can also use 

session.Source.Kernel.AddCallbackForProviderEvents(...) to select the names precisely and while it is more efficient it is a bit more cumbersome to use

**Comment by sammeboy635** [comment]
Thank you I figured it out now!
