### ISSUE TITLE
Do a better job getting the correct drive letter for Filename paths in ImageLoad events 

### ISSUE THREAD

**Issue by vancem** [microsoft/perfview#593]
This is from Jason Shirk, but the issue is old 
```
[Looking up symbols for sagettdext]
Symbol reader _NT_SYMBOL_PATH= {
    C:\Users\jasonsh\Documents;
    d:\springfield.fuzzing\src\build\fuzzers\sage\x64-release;
    SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*http://symweb.corp.microsoft.com;
    SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols;
    SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*https://nuget.smbsrc.net;
    SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*http://referencesource.microsoft.com/symbols;
    SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*https://dotnet.myget.org/F/dotnet-core/symbols;
    }
This can be set using the File -> Set Symbol Path dialog on the Stack Viewer.
Created SymbolReader with SymbolPath C:\Users\jasonsh\Documents;d:\springfield.fuzzing\src\build\fuzzers\sage\x64-release;SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*http://symweb.corp.microsoft.com;SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols;SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*https://nuget.smbsrc.net;SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*http://referencesource.microsoft.com/symbols;SRV*C:\Users\jasonsh\AppData\Local\Temp\symbols*https://dotnet.myget.org/F/dotnet-core/symbols
[Loading symbols for c:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll]
No PDB signature for c:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll in trace.
Data collected on current machine, looking up PDB by inspecting information in EXE.
FindSymbolFilePathForModule: searching for PDB for DLL c:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll.
FindSymbolFilePathForModule: c:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll does not exist.
[Failed to find PDB file for DLL c:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll]
Failed to to find PDB for c:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll
Could not find PDB file.
```
The problem is that the image actually lives on 

d:\springfield.fuzzing\src\build\fuzzers\sage\x64-release\sagettdext.dll

The issue is quite old and at its heart the issue is that imageLoad events sometimes have too little information, and in such cases we ultimately just 'guess' that drive is the system drive.  (see indexer of the class KernelToUserDriveMapping in KernelTraceEventParser.cs)

I believe this issue has been mentioned to the ETW folks but seems to be hard to fix.   We can 'fix' the problem here by probing at least the fixed drives.    Obviously this can't be done when the data file is not on the same machine (but at least we can fix that case).

We should check to see if this is being fixed at the OS level, and if not, do what we can here.

Note that merging the file should work around the issue of not finding the PDB.

**Comment by vancem** [comment]
There is a discussion (and a bug) on the windows team to look at this (but no commitment yet on fixing it).  See my mail e-mail thread 'No ImageID event for events with missing drive in image path' for details.   3/8/2018 from Aaron Robinson. 

That is of course the ideal solutionl

**Comment by vancem** [comment]
The windows bug that tracks this. 

Bug 15624698: ETW event doesn't reliably return complete file path

**Comment by brianrob** [comment]
Closing this issue now that this is being tracked in the OS.
