### ISSUE TITLE
How do I TURN OFF some providers that PerfView turns on by default?

### ISSUE THREAD

**Issue by vancem** [Microsoft/perfview#598]
The overhead of collecting events is interfering with my profile.  How do I make my collection leaner.

**Comment by vancem** [comment]
PerfView was designed to make it pretty easy to get the right events for a wide range of performance issues without having to think about it.    By default

* PerfView collect

collects what is needed for a wide variety of CPU investigation.   IT collects CPU samples every 1 msec, as well as a bunch of CLR events, and other events.  The philosophy is that if it is 'cheap' it and proven to  be useful then it is included.   You can expect a 3% perf hit when collecting.    However this data only handles CPU investigations (Not blocked time). 

* PerfView /threadTime collect

Is designed for 'everything else'  Its overhead varies more but it is typically in the 10-15% range.   The philosophy here is 'if it is general purposed and not too expensive, include it'  Thus it includes a wide variety of extra providers (many more than just PerfView collect. 

If you want to know exactly which providers are turned on, you need only look at the 'log' button (lower right corner) when the trace was collected (it also turns up in the 'PerfView' events in the trace).   Generally however, people don't much care.

#How do I turn the PerfView defaults off?  

Generally the default work well, however sometimes (typically in high throughput server scenarios), there is so much happening that the overhead of some providers is perturbing the results (you can tell because lots of time is spent in the ETW functions in the operating system).    You can use the 'Exclude Item' option in PerfVIew to 'exclude' this overhead, but this is not perfect.   If you really don't need the data, it is better simply not to collect it.    First you have to see which events are the problem.   You do that by looking at the 'Advanced Group -> Event Stats' view.   This view shows you the counts of every event in the trace.   Those near the top are the ones that potentially purturb your trace.   

## turning off Kernel events

It is a good rule of thumb that any events MORE numerous than the 'PerfInfo/Sample' event (this is the event fired every 1msec to measure CPU).  is of concern.     If this event is a kernel event you can turn it off with the /KernelEvents option.  There is a name called 'default' and another called 'threadTime' which represents the default and /threadTime options for the kernel events.   You can see all the possible kernel events by doing 'PerfView /?'  or by simply looking in the PerfView log and seeing what kernel events are turned on (and thus which ones you may wish to turn off.   Typically the only one that gets verbose that is on by default is the networking events.   For example here is a option that turns off the network kernel events.

* /kernelEvents:default-NetworkTCPIP 

You can also approach it from the other side and only turn on ONLY what is needed, but keep in mind in order to decode stacks you need a certain minmum (in particular the Process, Thread and Image.  Thus the minimum Kernel events that do CPU profiling are 

* /kernelEvents=process+thread+ImageLoad+Profile 

## turning off other non-kernel events one at a time

PerfView turns on a variety of providers by default, but it also allows you turn them back off.   You do this by using setting their keywords and level to 0.   For example the Task Parallel library (TPL) in .NET is sometimes too verbose.  It's PerfView name is .NET Tasks (you find this out by looking in the log for all the providers that PerfView turns on). and then add the option

* /providers=.NETTasks:0:0 

Turning both keywords and level to 0, in PerfVIew tells it to disable the provider completely.  

## turning off other non-kernel events in bulk

The option above works OK if there is only one provider that is causing grief.  If you want to ONLY have the providers you need an no more it is awkward.   You want a way to simply tell PerfView not to start an providers you did not ask for.   You CAN do this in PerfView.   PerfView only turns on these other providers if you use at least the 'default' CLR events.   Thus if you 'turn off' clr events, you will also turn off all the other default providers as well.  

Not you can simply say

* /clrEvents=none

To do this, but that is very extreme.   In particular it does not event include the JIT compiler events that allow you to decode .NET STacks.  Thus you will not have symbolic names for JIT compiled code.  This is usually NOT what you want.  Instead use the 'JitSymbols' name which includes JUST the events needed to decode JIT compiler symbols.  Thus

* perfView /clrEvents=JITSymbols /kernelEvents=process+thread+ImageLoad+Profile  collect

Is the 'leanest' collection you can get that still includes events needed to actually decode the stacks.   This is what you might use if you were doing a CPU investigation and wanted the lowest possible overhead.

If you need still lower overhead, you can use the /CPUSampleMSec:XXX option to collect fewer CPU samples (the default is once ever millisecond, per core).   Thus

* perfView /clrEvents=JITSymbols /kernelEvents=process+thread+ImageLoad+Profile /CPUSampleMSec:10 collect

Has about 1/10 the overhead (since it only samples every 10 msec).  This can allow you to lower the overhead to pretty much anything you desire.

**Comment by tiagonapoli** [comment]
Thanks so much, @vancem!
I wasn't able to do a cpu profiling in production due to the overhead, and if I selected only CPU Samples there were a lot of broken stacks, due to missing JIT Stacks

The example you added was exactly what I needed:
```

**Comment by kayle** [comment]
@brianrob The gui now seems to treat level 0 as Always instead of disabled. I didn't try command line. Is that a recent change? Should it be documented somewhere?

**Comment by brianrob** [comment]
@kayle to my knowledge, nothing here should have changed.  Level 0 has always been `LogAlways`.  Are you seeing behavior differences between two versions?  If so, please do file a new issue so we can track it appropriately.

**Comment by kayle** [comment]
@brianrob No, I guess I was misinterpreting this from the above post:
> Turning both keywords and level to 0, in PerfVIew tells it to disable the provider completely.

In my case, I was trying to disable some keywords by setting only the level to 0:
`Microsoft-Windows-DotNETRuntime:ThreadTransferKeyword|ContentionKeyword|ThreadingKeyword:0`

Looks like setting keywords to 0 is what actually disables a provider (and then the level is ignored)? Is it possible to disable only specific keywords from a provider? My best workaround was setting level to 1 which was enough to prevent the threading events from being logged.
