### ISSUE TITLE
Microsoft.Diagnostics.Tracing.TraceEvent 2.0.6 Version only supports .NET4.7.1

### ISSUE THREAD

**Issue by edwin-alvarez** [Microsoft/perfview#605]
can you please allow Microsoft.Diagnostics.Tracing.TraceEvent 2.0.6 to be used with .NET4.6.2 is forcing 4.7.1
also please include Missing reference to Microsoft.Win32.Registry

**Comment by vancem** [comment]
Please try version 2.0.10.    There was an issue that was fixed that was probably your problem.

I just tried it on project that was built against V4.6 and it worked for me.
