### ISSUE TITLE
Microsoft.Diagnostics.Tracing.TraceEvent Version 2x not supported in WIN7

### ISSUE THREAD

**Issue by edwin-alvarez** [Microsoft/perfview#610]
I had to go back to version 1.0.41.0, good think it was just a matter of changing version nuget. will be good to upload doc to mention that.

**Comment by vancem** [comment]
I don't have easy access to a Win7 machine at the moment, however I know of no reason why traceEvent would not work on a Win7 machine.   

I am going to close this, but feel free to reopen.  Just give me more information on what exactly you tried and how it failed so there is something to investigate.
