### ISSUE TITLE
CPU Sampling exception and method name are both inverted

### ISSUE THREAD

**Issue by CMicalF** [Microsoft/perfview#615]
In the lines below in TraceEventSession.cs, the exception text and the method name do not match the described behavior. Here it seems to be setting the "sampling interval", which is the inverse of the "sampling rate". So if cpu100ns is too large, the exception should be either "CPU Sampling interval is too high" or "CPU sampling rate is too low".

Similarly, ETWControl.SetCpuSamplingRate should be renamed to ETWControl.SetCpuSamplingInterval for correctness. I can't see the source for ETWControl in this Repo, but my testing verified that using this set the interval to the specified value, not the rate.

var cpu100ns = (CpuSampleIntervalMSec * 10000.0 + .5);
if (cpu100ns >= int.MaxValue || ((int)cpu100ns)
    throw new ApplicationException("CPU Sampling **rate** is too high.");
var succeeded = ETWControl.**SetCpuSamplingRate**((int)cpu100ns);

**Comment by vancem** [comment]
I have a fix, but won't close this until it is merged.

**Comment by vancem** [comment]
This fix is in.
