### ISSUE TITLE
"Very Fragmented Ephemeral" condemn reason is incorrect

### ISSUE THREAD

**Issue by kkokosa** [Microsoft/perfview#616]
In _Condemned reasons for GCs_ section of _GCStats_ view, there is a column named _"Very Fragmented Ephemeral"_ with an additional _"Ephemeral generations are VERY fragmented, doing a full GC"_ description.

This is however incorrect. This reason internally refers to `gen_max_high_frag_e_p` condition, which is set if fragmentation of generation 2 (`max_generation`, see `dt_high_frag_p ` below) is big enough to fit generation 1:

```
if (dt_low_ephemeral_space_p (check_only_p ? tuning_deciding_full_gc : tuning_deciding_condemned_gen))
{
	...
	local_condemn_reasons->set_condition (gen_low_ephemeral_p);
	...
	
	//It is better to defragment first if we are running out of space for
	//the ephemeral generation but we have enough fragmentation to make up for it
	//in the non ephemeral generation. Essentially we are trading a gen2 for 
	// having to expand heap in ephemeral collections.
	if (dt_high_frag_p (tuning_deciding_condemned_gen, 
						max_generation - 1, 
						TRUE))
	{
		high_fragmentation = TRUE;
		local_condemn_reasons->set_condition (gen_max_high_frag_e_p);
	}
}

BOOL 
gc_heap::dt_high_frag_p (gc_tuning_point tp, int gen_number, BOOL elevate_p)
{
	BOOL ret = FALSE;
	switch (tp)
	{
		case tuning_deciding_condemned_gen:
		{
			dynamic_data* dd = dynamic_data_of (gen_number);
			float fragmentation_burden = 0;
			if (elevate_p)
			{
				ret = (dd_fragmentation (dynamic_data_of (max_generation)) >= dd_max_size(dd));
			}
			...
		}
	}
	return ret;
}
```

I suggest changing the column name and description to the "_Ephemeral Low with Very Fragmented Gen2_" and "_We are running low on the ephemeral segment but gen2 is fragmented enough to compensate that, doing a full GC_".

**Comment by vancem** [comment]
@Maoni0 @jeffschwMSFT.   He is complaining about the logic of the CondemnedReasonsHtmlHeader in GCStats.cs.

**Comment by Maoni0** [comment]
that's fine...please feel free to submit a PR.

**Comment by vancem** [comment]
Sure.
