### ISSUE TITLE
Build troubles: cannot open include file 'assert.h'

### ISSUE THREAD

**Issue by jazzdelightsme** [Microsoft/perfview#623]
Repro steps:

1. Install Windows (recent rs4_release).
2. Install VS 2017 Community, with .NET and C++ desktop workloads.
3. Downloaded perfview source (circa 3/28/2018).
4. Attempt build.

(failed, needed 8.1 SDK, among other errors)

5. Installed 8.1 SDK (Visual Studio Installer, Modify, Individual Components, Windows 8.1 SDK)

(still lots of errors, including .NET Standard/Core problems, "can't open assert.h")

6. Install .NET 4.7.1 stuff. (because maybe that will let me target .NET Standard 2.0?) (Visual Studio Installer, Modify, Individual Components, .NET Framework 4.7.1 SDK and Targeting Pack)

(still have .NET Standard/Core problems)

7. Install .NET Core SDK separately (don't know why this isn't part of VS Installer...) (https://www.microsoft.com/net/download/windows, "Download .NET Core SDK 2.1.101")

Still have lots of errors. It looks like the "real one" is a failure to include "assert.h":

Severity |	Code |	Description |	Project |	File |	Line |	Suppression State
--- | --- | --- | --- | --- | --- | ---
Error |	C1083 |	Cannot open include file: 'assert.h': No such file or directory | 	ETWClrProfilerX86 | 	c:\src\perfview-master\src\etwclrprofiler\stdafx.h |	7	

`assert.h` seems like a pretty basic header... but could be coming from many different places. Where *should* it be coming from? Could someone who is able to build throw in /showIncludes and tell me where ETWClrProfilerX86 is getting assert.h from?

**Comment by MagicAndre1981** [comment]
I see the file here "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\assert.h". So Install the C++ workload and the Windows 10 SDK (currently 16299 is last SDK for stable Win10 version) in VS2017 Installer.

**Comment by jazzdelightsme** [comment]
I also have that file at that location. However, VC does not try to include it. Looking at build output, it seems that VC defaults to using 10.0.10240.0 in the include path instead, even though it does not have that SDK installed (I would bet $ that the 10240 location is where your build is picking it up from, too, which you could see if you turn on `/showIncludes`).

So I think this is a VC defaults problem (why would they set that default include path, if you don't even have that SDK installed??), and you folks are able to build because at some point you installed that SDK (perhaps that was what used to be the default installed with VS).

I will complain to the VS/VC people and see what comes of it. In the meantime, y'all should decide if that's really the SDK you want to target.

**Comment by MagicAndre1981** [comment]
Install the 10240 SDK (and best all Win10 SDKs) in VS2017 installer.

**Comment by jazzdelightsme** [comment]
Actually, the "Windows Universal CRT SDK" component installs the same headers (at the same 10240 SDK path), and it's several hundred MB smaller to install, so unless anybody thinks we need the entire 10240 SDK, I'll propose that people install that instead.

**Comment by MagicAndre1981** [comment]
I always install everything from Win10 SDKs to be safe
