### ISSUE TITLE
Question: possible to use EventSource in Xamarin.Forms and capture events on Android phone?

### ISSUE THREAD

**Issue by MagicAndre1981** [Microsoft/perfview#624]
I've created an app with Xamarin.Forms that targets Android and UWP (16299) with .net standard 2.0 library to share the code and the views. Can I raise here EventSource events and is there a way to capture them on Android 7.1.2 (LineageOS 14.1)?

**Comment by vancem** [comment]
I do not personally have no experience trying to use EventSource on the Xamarin platform.   

My expectation is that there is no particular support, but there is a good chance that basic EventSource-EventListener functionality works (easiest way is to try it).  

Thus you can make an EventListener that logs to a file and it should work anywhere (including Android).   

I don't know of more than that.

**Comment by vancem** [comment]
I would work with the mono group to see if they could port the .NET Core version of EventSource/EventListener.   It should mostly 'just port'.   I could believe however that that is more than you want to do, but I don't have better advice.
