### ISSUE TITLE
Asp.Net Stats doesn't show for ASP.NET Core 2

### ISSUE THREAD

**Issue by sinapis** [Microsoft/perfview#636]
I've collected a session using PerfView on ASP.NET Core 2 WEB API assembly, but I can't see the stats I'm interested in. Here is what I see:

![image](https://user-images.githubusercontent.com/15230040/38586512-a241d986-3d26-11e8-9c53-fd034215d25a.png)

Here is what I expected to see:
![image](https://user-images.githubusercontent.com/15230040/38586523-b767532c-3d26-11e8-92c0-3fa24021a13d.png)

Are these stats missing for .Net Core, or am I doing something wrong?

**Comment by vancem** [comment]
These events are not emitted by ASP.NET Core.    In theory they have better events but PerfView has not been specialized to make a report for them.

**Comment by sinapis** [comment]
Is there a workaround? How would I go about analyzing thread time for asp.net core apps?

Can you elaborate more about "better events" - is there a way for me to access them and create a report outside of perfview?

**Comment by vancem** [comment]
There is no analog for the ASP.NET **Stat page**, but it is not clear whether it worth creating on for ASP.NET Core 5.     However there is an analog for the ASP.NET Thread Time (with Tasks), which is really the interesting one.   You simply use the Thread Time (with StartStop activities).  

You will find under the 'Activities' node a 'Microsoft.AspNetCore.Hosting.BeginRequest' node for each request which allows you to drill into what is happening on any particular request.   

You can also look in the 'Events' view for the Microsoft-Diagnostics-DiagnosticSource events.  You will see them for the BeginRequest events and the 'Stop' event has the duration.    This can be useful for determining statistics.

**Comment by sinapis** [comment]
Where is the Activities node? I can't find it in the view 
![image](https://user-images.githubusercontent.com/15230040/39236452-9cf17c3c-4881-11e8-8852-9e55dfcdcbc5.png)

I also can't find the event "Microsoft-Diagnostics-DiagnosticSource":
![image](https://user-images.githubusercontent.com/15230040/39236588-dc3e50fe-4881-11e8-90b7-e0f66d47623b.png)

Note I collected the default + marked "Thread Time". I recorded while sending and receieving requests from ASP.NET Core 2 web API app.

**Comment by vancem** [comment]
What version of the .NET Runtime and PerfView are you using?    These are relatively recent additions (although I would have to research to find out exactly when).  

Here is what I get when I run the MVC sample on a 2.1 version of the runtime, while collecting with  PerfView 2.0.12.

![image](https://user-images.githubusercontent.com/8459414/39260342-0c15a52a-486e-11e8-95e0-411fec26de61.png)

This happens to be the most current stuff, but much of it has worked for a while.  

You know you have a recent-enough PerfView if you see this line in the log when you start collection (with ThreadTime turned on).  
```
Enabling Provider:Microsoft-Diagnostics-DiagnosticSource Level:Informational Keywords:0xfffffffffffff7ff Stacks:1 Values:FilterAndPayloadSpecs=HttpHandlerDiagnosticListener/System.Net.Http.Request@Activity2Start:Request.RequestUri
```
I would have expected a V2.0 .NET Core Runtime would be enough, but I have not actually tried that personally.

**Comment by sinapis** [comment]
I got burned by Google giving the first result here: https://www.microsoft.com/en-us/download/details.aspx?id=28567

Never noticed the obsolete warning.

So finally I can see activities!
But not there yet since I can't see my code. Could it be it's under BROKEN? Hoe can I fix that?
![image](https://user-images.githubusercontent.com/15230040/39292954-50759964-4940-11e8-9229-6e0f83c352c9.png)

Is this the duration:
![image](https://user-images.githubusercontent.com/15230040/39302623-eaa9042e-495b-11e8-8e13-65c27d2c67f5.png)
Can you explain difference between Activity1 and Activity2 and what does time mean in start vs stop?

**Comment by vancem** [comment]
> But not there yet since I can't see my code. Could it be it's under BROKEN? How can I fix that?

Hmmm, that certainly does not happen for me.   What operating system are you using, and is this a 64 bit or 32 bit process?   

However I notice in your screenshot above the two nodes you opened, have a very small metric and might be 'noise', and the nodes with a large amount of time were left unopened.  Those are the more interesting nodes to open.    If you are running on a reasonably current version of Windows (2012 or later) things should 'just work' (e.g. they do for me), but I need more information before I can say more.  A better screenshot would help, but what would help more is if you publish your ETL.ZIP file somewhere I can get at it

> Can you explain difference between Activity1 and Activity2 and what does time mean in start vs stop?

ASP.NET uses a logging infrastructure called DiagnosticSource when it instrumented its code.   There is a 'bridge' from this logging infrastructure to EventSource/ETW (which is what PerfView uses natively), ETW is a STATIC logging system (you decide the names of your methods at compile time).   Thus they are given very generic names (Activity1 and Activity2 ...) but then when you turn them on, you map the DiagnosticSource to these generic events.    Thus PerfView asked that the BeginRequest be mapped to Activity1.   You can see the specific source and event in the payload.  

The time is the time of the event happened (it is displayed as the number of MSec fromt the beginning of the trace).    If you display both starts and stops, PerfView is smart enough to subtract the two and report it as DURATION_MSEC in the stop activity.

**Comment by GomesNayagam** [comment]
if you could tell me how do i get database connection pool(ado.net) stat, i would love to see in perfview.
