### ISSUE TITLE
A very suspicious reference path from PrivateImplementationDetails

### ISSUE THREAD

**Issue by kkokosa** [microsoft/perfview#638]
When analyzing Heap Snapshot of [nopCommerce](https://github.com/nopSolutions/nopCommerce), very strange references are shown, for example for `CacheEntry` instances:

![perfview_bug01](https://user-images.githubusercontent.com/11159779/38868057-1ed01b38-4246-11e8-8a5e-3efa52f30991.png)

Many comes from `<PrivateImplementationDetails>.GUID` classes are used for array initializers. For example, the heaviest one `040AAE3FE52CFC22160CC39DFBB7ADE6B14284C7` comes from `Microsoft.CodeAnalysis.CSharp.dll`:

```
[CompilerGenerated]
internal sealed class <PrivateImplementationDetails>
{
    // ...
   internal static readonly <PrivateImplementationDetails>.__StaticArrayInitTypeSize=32 040AAE3FE52CFC22160CC39DFBB7ADE6B14284C7;
    // ...
   [StructLayout(LayoutKind.Explicit, Pack = 1, Size = 32)]
   private struct __StaticArrayInitTypeSize=32
   {
   }
    // ...
}
````

used in `Microsoft.CodeAnalysis.CSharp.BuiltInOperators.GetSimpleBuiltInOperators` method:

```
   // Token: 0x060011E8 RID: 4584 RVA: 0x0004C93C File Offset: 0x0004AB3C
   .method assembly hidebysig 
  	instance void GetSimpleBuiltInOperators (
		valuetype Microsoft.CodeAnalysis.CSharp.UnaryOperatorKind kind,
		class [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.ArrayBuilder`1<valuetype Microsoft.CodeAnalysis.CSharp.UnaryOperatorSignature> operators
	) cil managed 
   {
   // ...
   /* 0x0004AC3B 8DD3020001   */ IL_00F3: newarr    [System.Runtime]System.Int32
   /* 0x0004AC40 25           */ IL_00F8: dup
   /* 0x0004AC41 D0DC180004   */ IL_00F9: ldtoken   field valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=32' '<PrivateImplementationDetails>'::'040AAE3FE52CFC22160CC39DFBB7ADE6B14284C7'
   /* 0x0004AC46 288504000A   */ IL_00FE: call      void [System.Runtime]System.Runtime.CompilerServices.RuntimeHelpers::InitializeArray(class [System.Runtime]System.Array, valuetype [System.Runtime]System.RuntimeFieldHandle)
  /* 0x0004AC4B 28E7110006   */ IL_0103: call      instance valuetype [System.Collections.Immutable]System.Collections.Immutable.ImmutableArray`1<valuetype Microsoft.CodeAnalysis.CSharp.UnaryOperatorSignature> Microsoft.CodeAnalysis.CSharp.BuiltInOperators::GetSignaturesFromUnaryOperatorKinds(int32[])
   /* 0x0004AC50 A43502001B   */ IL_0108: stelem    valuetype [System.Collections.Immutable]System.Collections.Immutable.ImmutableArray`1<valuetype Microsoft.CodeAnalysis.CSharp.UnaryOperatorSignature>
   // ...
}
```

It is impossible that such static fields reference `Microsoft.Extensions.Caching.Memory.CacheEntry` as shown above... Not sure how to interpret that.

**Comment by vancem** [comment]
It is hard to know if there is a bug here or not.  More information is certainly needed for the issue to be actionable.    I agree it looks suspicious.  

Including the trace will help.   

It would also be will be useful to also capture a dump of the GC heap when clicking the 'save ETL' checkbox as well.   This uses a very different way of capturing the data, and if they differ, that is more clearly indicates a bug.

**Comment by brianrob** [comment]
Per @vancem's comment, a repro is required here.  Closing.
