### ISSUE TITLE
Figure out a better way of signing the TraceEvent Nuget package

### ISSUE THREAD

**Issue by vancem** [microsoft/perfview#673]
Currently there is a project TraceEventPackageSigning\TraceEventPackageSigning.csproj whose sole purpose is to sign the Microsoft.Diagnostics.Tracing.TraceEvent.*.nupkg using the Microbuild framework.  

This project (as well as the EtwClrProfilerSigning project) should not exist, as what we want to do (sign nuget packages), should be a 'standard' thing that should be well supported by Microbuild.  

I tried numerous things to get this to work in a simple way (using just one csproj and my last attempt was this commit

    *https://github.com/Microsoft/perfview/commit/3a8e3741863864d102fb7a64f78767e834ff8421

There are two issues, the first is that we are signing twice (first the DLL then the nuget package, and the second is that you are actually have several DLLs (one for netstandard1.6, one for 2.0 and one for net45), which cause MSBUILD to be invoked recursively before running the nuget packaging.  

In my last attempt above the issue was that the microbuild infrastructure was not loaded at the time of the nuget packaging.   

At this point I bailed and built something I 'knew would work (the TraceEventPackageSigning project). which is where things stand.   Ideally we go back and figure out how to make this work more simply.  This issue tracks that.

**Comment by brianrob** [comment]
Closing this issue as it's fine to keep this extra project.
