### ISSUE TITLE
Default symbol path for Microsoft Symbol Server should go to the secure site

### ISSUE THREAD

**Issue by iliasashaikh** [microsoft/perfview#698]
The Symbol path for Microsoft Symbol server by default is set to SRV*C:\Users\Ilias\AppData\Local\Temp\symbols*http://msdl.microsoft.com/download/symbols

It probably needs to be changed to SRV*C:\Users\Ilias\AppData\Local\Temp\symbols*https://msdl.microsoft.com/download/symbols

i.e. go the secure site. The default wasnt working for me and then when I updated the link, it was able to download the symbols.

**Comment by brianrob** [comment]
@leculver, @noahfalk, do you know if we should be defaulting to the SSL version of msdl.microsoft.com for symbols?

**Comment by sharwell** [comment]
We should be defaulting to https, yes

**Comment by noahfalk** [comment]
I am not aware of any reason not to use the SSL option.

**Comment by brianrob** [comment]
Sounds good.  Thanks all for the confirmation.

**Comment by HMartyrossian** [comment]
Brain, can we close this issue?

**Comment by brianrob** [comment]
Fixed via #1125.
