### ISSUE TITLE
Reading back Generated Events with ETL Viewer

### ISSUE THREAD

**Issue by andd64** [microsoft/perfview#699]
I'm trying to add some custom events, capture an ETL session, and read them back with a viewer such as GPUView, WPA, mXa.  However, the payload data, including GUID name, isn't correctly shown.

I tried the following with the SimpleEventSourceFile sample.  
-Add a call to GenerateManifest(Log.GetType(), Log.Name).  Save this manifest as manifest.xml.
> wevtutil im manifest.xml
The console window prints this out:
**** Warning: The resource file for publisher Microsoft-Demos-SimpleMonitor was not found or could not be opened.

resourceFileName: Microsoft-Demos-SimpleMonitor

GPUView/WPA still doesn't show the payload.

I then tried adding the resource and message flags:
>wevtutil um manifest.xml
>wevtutil im manifest.xml /rf:TraceEventSamples.exe /mf:TraceEventSamples.exe
The console window prints this out:
**** Warning: The resource file for publisher Microsoft-Demos-SimpleMonitor does not contain the metadata resource.
Make sure to link the .bin file generated by the Message Compiler into the
specified binary.

resourceFileName: TraceEventSamples.exe

GPUView/WPA still doesn't show the payload.

PerfView is the only tool that can correctly parse the payload.

What am I doing wrong? Any advice?  Looks like I may be missing some metadata?

**Comment by andd64** [comment]
Okay made some progress with this.  Adding the Microsoft.Diagnostics.Tracing.EventRegister nuget package was key.  Not sure if this is the best way to do this, but it seems to work:
Add `<EtwManifestForceAll>true</EtwManifestForceAll>` to the project file.
Reopen the project and build.
There should now be a manifest and dll file, i.e. TraceEventSamples.Microsoft-Demos-SimpleMonitor.etwManifest.dll and TraceEventSamples.Microsoft-Demos-SimpleMonitor.etwManifest.man.

Register this manifest file, pointing to the dll for the resource/message file:
wevtutil im TraceEventSamples.Microsoft-Demos-SimpleMonitor.etwManifest.man /rf:"${FullPathTo}\TraceEventSamples.Microsoft-Demos-SimpleMonitor.etwManifest.dll" /mf:"${FullPathTo}\TraceEventSamples.Microsoft-Demos-SimpleMonitor.etwManifest.dll"

Both GPUView and mXa correctly parsed the manifest file, and showed the correct provider name and payload info.  For some reason, WPA still had issues parsing the data, but for me getting GPUView/mXa to work was more important.

If anyone else has a better way of doing this, please share. =)

**Comment by brianrob** [comment]
@andd64, apologies for the delay in responding to this.  It sounds like you are unblocked so that is good.  What you did is reasonable, which is to register the manifest for other tools to be able to consume your events.  Both WPA and PerfView should not require this, as the manifest is written into the ETL file and both tools know how to consume the manifest.

Either way, it sounds like you are unblocked, so closing.
