### ISSUE TITLE
ETWReloggerTraceEventSource::SetPayload size

### ISSUE THREAD

**Issue by mikepal2** [microsoft/perfview#702]
line 234: must be ``` curBlobPtr = newCurBlobPtr;  ``` instead of  ``` curBlobPtr += newCurBlobPtr ```
https://github.com/Microsoft/perfview/blob/29788fe1dc799dc317d0a90f46bfae4ac6ccd333/src/TraceEvent/ETWReloggerTraceEventSource.cs#L234

**Comment by brianrob** [comment]
Fixed via #689.
