### ISSUE TITLE
perfview stop fails to stop a running CLI perfiew when -CollectMultiple: is specified

### ISSUE THREAD

**Issue by patricktg** [microsoft/perfview#709]
While running perfview collect -CollectMultiple, a perfview stop is done, which triggers the ETL.zip to complete, but the original perfview process is still running.  A subsequent perfview stop says their are no perfview sessions running. If the collect with the same command line is attempted, a second window pops up saying the log file is already in use until the extraneous perfview.exe is killed/end task from Task Manager.

Perfview version 2.0.15 is in use, running on Windows Server 2012 R2 Standard.

Here's the CLI that was running while a perfview stop was ran:
perfview collect -LogFile:pv-preSchannelIIS.log -NoView -CircularMB=435 -ThreadTime -TrustPdbs -Merge:true -Zip:true -ClrEvents=Default,threading -kernelEvents=default-Profile -TplEvents:Default -Providers:Microsoft-Windows-IIS -StopOnEventLogMessage:System@"TLS protocol" -MaxCollectSec:129600 -CollectMultiple:3 PVpreSchannelIIS.etl

Here's the perfview stop that was ran:
perfView stop -Providers:Microsoft-Windows-IIS

**Comment by brianrob** [comment]
@patricktg this is expected behavior.  `perfview collect` is designed to remain live until collection is stopped and the trace file is written.  `perfview stop` can only be run after a corresponding `perfview start`.
