### ISSUE TITLE
ETW EnableKernelProvider is not working on docker Windows Container (Windows Server Core)

### ISSUE THREAD

**Issue by Pellared** [Microsoft/perfview#724]
Environment:
- Microsoft.Diagnostics.Tracing.TraceEvent.2.0.19
- docker: Version 18.06.0-ce-win72 (19098)
- image: repository: microsoft/windowsservercore; tag: ltsc2016; iamge ID: 7d89a4baf66c

I have created a console application that monitors Kernel Events.
When I run it inside a docker container using powershell then I get the following exception:

```
System.UnauthorizedAccessException: Error Starting ETW:  Access Denied (Administrator rights required to start ETW)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.InsureStarted(EVENT_TRACE_PROPERTIES* properties)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at XYZ.<StartAsync>b__38_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at XYZ.<StartAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at XYZ.UnhandledExceptionHandler.<ExecuteAsync>d__6.MoveNext()
```

Add the beginning there of the program there is check:
```
if (TraceEventSession.IsElevated() != true)
{
   Logger.Log("Must be elevated(Admin) to run this program.");
   Environment.Exit(1);
}
```
passing. I have also added a double check in powershell:
```
$isRunAsAdministrator = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
if (-not $isRunAsAdministrator) {
    throw "requires to be run as Administrator"
}
```
still everything passing

The code fails when running:
```
public async Task StartAsync()
{
    await Task.Run(() =>
    {
        var sessionName = "XYZ Kernel Logger";
        using (s_kernelSession = new TraceEventSession(sessionName))
        {
            s_kernelSession.EnableKernelProvider(
                KernelTraceEventParser.Keywords.FileIOInit |
                KernelTraceEventParser.Keywords.Process |
                KernelTraceEventParser.Keywords.ImageLoad |
                KernelTraceEventParser.Keywords.FileIO |
                KernelTraceEventParser.Keywords.Registry |
                KernelTraceEventParser.Keywords.NetworkTCPIP
                //|
                //KernelTraceEventParser.Keywords.ReferenceSet
                );

            //s_kernelSession.EnableKernelProvider(KernelTraceEventParser.Keywords.FileIOInit | KernelTraceEventParser.Keywords.Process | KernelTraceEventParser.Keywords.ImageLoad);
            s_kernelSession.Source.Kernel.FileIORename += FileIORenameEvents;
            s_kernelSession.Source.Kernel.FileIORead += FilterIOEvents;
            s_kernelSession.Source.Kernel.FileIOWrite += FilterIOEvents;
            s_kernelSession.Source.Kernel.ImageLoad += processImageLoadEvent;
            s_kernelSession.Source.Kernel.ProcessStart += processStartEvent;
            s_kernelSession.Source.Kernel.RegistrySetValue += registrySetEvent;
            s_kernelSession.Source.Kernel.TcpIpConnect += tcpConnect;
            //s_kernelSession.Source.Kernel.FileIOMapFile += FilterMemory;

            s_kernelSession.Source.Process();
        } // using
    }); // await
}
```

Any ideas what can be wrong? 
Is Microsoft.Diagnostics.Tracing.TraceEvent.2.0.19 working inside a Windows Container?

**Comment by Pellared** [comment]
Might be related to: https://github.com/Microsoft/perfview/pull/393

**Comment by vancem** [comment]
The only flags allowed in a container are the process thread, imageload profile and context switch.

The I believe the code is correct and does not need to be changed (Also it worked before).  

I am in conversation with the Windows OS team about this, with a bug tracking it.   We will see what comes of it.

**Comment by vancem** [comment]
OK after consulting with the OS folks I determined that my problem (and likely yours, it is the same symptom) is that you are using a very old (2 years) version of windowsServerCore .

Please get the version number for your OS (cmd -c ver)   You should get something like 

Microsoft Windows [Version 10.0.17134]
The third number (the build number) needs to be >= 16299.   

Sadly the current 'latest' tag for a windowservercore (which is the default is this very old 14393 build (over 2 years old).  Thus it is VERY easy to run into this problem.  

You can see the version of windows 10 [here](https://en.wikipedia.org/wiki/Windows_10_version_history) Basically you want Redstone 3 or later.  

You can get a redstone 4 version by using its 1803 tag like so
```
docker run -it microsoft/windowsservercore:1803 cmd
```

Note that you can run PerfView on windowsServerCore.  It works fine, but because it is a GUI app it detaches from the console (unless it is in a batch file).   If you follow the instructions in the users guide for automated collection it basically just works (the /logFile option supresses the GUI).  

Finally you can also run TraceEvent on windows/nanoserver.   However you need  to use the 'PerfViewCollect' rather than PerfView.  PerfViewCollect is a .NET Core app but has the same command line interface as PerfView (it only does collection).   I will be announcing this in a bit.

**Comment by Pellared** [comment]
Do you know if/when the Windows Server Core would support more flags (kernel events)?
I am mostly interested in FileIO, Registry and NetworkTCPIP. I think they would be very valuable.

Of course I understand that anything you say would be just an estimation. I just need to take a decision is it worth to wait for a newer Windows Server Core version or should I start using Hyper-V in our CI pipeline.

**Comment by vancem** [comment]
I don't know of any plans to add more kernel events (over the existing support for CPU, and Context Switch events) to light weight windows docker containers.   

Note that if you run a ETW session on the host OS, you will see the kernel events. I realize this is not helpful in many scenarios, but I wanted to point it out.

**Comment by Pellared** [comment]
Thanks a lot.
