### ISSUE TITLE
CLR Startup flags empty for server/concurrent GC for .NET core processes

### ISSUE THREAD

**Issue by MatthiasWeiser** [Microsoft/perfview#767]
Currently there is no way to see for a .NET core 2.1 process if the garbage calculator is configured for server and concurrent garbage collection. CLR Startup flags are shown as None. The values are shown for .NET framework processes.
It would be nice if the behavior is consistent with the .NET framework.

**Comment by vancem** [comment]
This is actually a request for the .NET Core.  Please log the issue at https://github.com/dotnet/coreclr/issues
