### ISSUE TITLE
how to find connection pool stat

### ISSUE THREAD

**Issue by GomesNayagam** [Microsoft/perfview#770]
i use few performance counter Microsoft SQL Stats/* to find and debug open connection and pool stat to figure out any txn or connection is not closed. How do i see those in perfview.

**Comment by vancem** [comment]
PerfView mostly does not interact with Performance Counter data.  

However there is a small amount of overlap that may be useful.

You can ask PerfVIew to log an event every N seconds to the trace by using the /MonitorPerfCounter option.   Here is some help on that.  
```
    [-MonitorPerfCounter:STRING,...]     This is of the form CATEGORY:COUNTERNAME:INSTANCE@NUM where
                            CATEGORY:COUNTERNAME:INSTANCE, identify a performance counter (same as
                            PerfMon), and NUM is a number representing seconds.  The @NUM part is optional
                            and defaults to 2.  The value of the performance counter is logged to the ETL
                            file as an event ever NUM seconds
```
This allows you to see these values at a low frequency so you can then drill into 'bad' ranges in the CPU or ThreadTime view to see what was going on in more detail.  

You can also ask PerfView to stop a trace based on a performance counter with the /StopOnPerfCounter (see help).   This can be useful to see what was happening just before some counter (e.g. CPU usage or Memory consumption) spiked.
