### ISSUE TITLE
Stackwalker broken when running PerfView64 on 64bit binary.

### ISSUE THREAD

**Issue by pranavsharma** [Microsoft/perfview#771]
![perfview_error](https://user-images.githubusercontent.com/2732907/47386527-b9db7680-d6c1-11e8-9864-f6a514ebe0d2.png)

**Comment by vancem** [comment]
This dialog box is not a indication that PerfView is broken, but simply that the operating system stackwalker  could not do a good job.   There is no 'fix' in PerfView.   Please see the troubleshooting link as indicated to determine what to do.
