### ISSUE TITLE
New tread created for every GC/Start event

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#777]
https://github.com/Microsoft/perfview/blob/0f77be5938135af9a64c2f928c44b19dc7dbc048/src/TraceEvent/TraceLog.cs#L1994

The **GC/Start** event is resulting in `isThreadCreateEvent` getting set to true.

Assigning to @vancem since this was likely introduced by #763.

**Comment by vancem** [comment]
Closing fixed by #778.   \\clrmain\tools\PerfView.exe has the fixed copy.  The offical  github copy was never broken (the break postdated the last release).
