### ISSUE TITLE
Clarification on Microsoft.Diagnostics.Tracing.TraceEvent 2.0.29 license

### ISSUE THREAD

**Issue by joshfree** [Microsoft/perfview#779]
Posting on behalf of a user who emailed the support link on https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent/ :

> Hello!
> Licensing question here - I see that Trace Event is licensed under the .Net license on the download page (yet has no .js files), but the LICENSE.TXT file contains the MIT license.
> So how is Trace Event licensed?
> Thank you!

cc: @vancem

**Comment by vancem** [comment]
TraceEvent should work just like all the other .NET libraries.    We will fix this.

**Comment by vancem** [comment]
PR #792 harmonizes the nuget package and the source code.   They now both use https://github.com/Microsoft/perfview/blob/master/LICENSE.TXT which is consistent with how licensing works in the https://github.com/dotnet/corefx repo.

**Comment by vancem** [comment]
This will show up in version 2.0.31 or later of the TraceEvent package.
