### ISSUE TITLE
Question: Set ContextId instead of ActivityId

### ISSUE THREAD

**Issue by Xhanti** [Microsoft/perfview#787]
Hi,

I wanted to know if there is way to use **_Microsoft.Diagnostics.Tracing.EventSource_** to set the ContextId instead of the ActivityId. I see  **_Microsoft.Diagnostics.Tracing.EventSource_**  has **_SetCurrentThreadActivityId_** and I'm trying to accomplish something similar but with the ContextId. The motivation behind this is that I want my events to line up a bit nicer with the asp.net events in Perfview. 

What I've got now is this:

![image](https://user-images.githubusercontent.com/2096304/48117001-73187f80-e270-11e8-819a-7593e8065fda.png)

Which works, but I want to see if I can do a bit better and only use ContextId to 'stitch' events together.
Any guidance (an example you can point to for instance) would be greatly appreciated

Thanks
cc: @vancem

**Comment by vancem** [comment]
ContextId is simply a field in the AspNetReq/Start event.  This field does not exist for other events (in particular your Portala-EventSource/Count.  Of course you could make such a field in your event (just make a parameter called ContextId, and pass it the current activity ID), and it would show up in the events view.  

Note that the ASPNetTrace provider is old and uses conventions (like ContextId) that are not recommended (and don't set the ActivityID which is recommended).    Thus realize that you are building on unrecommended conventions....  That can be OK, but you should be aware of it.
