### ISSUE TITLE
License info for Microsoft.Diagnostics.Tracing.TraceEvent inconsistency between NuGet and github.

### ISSUE THREAD

**Issue by rpajak-solarwinds** [Microsoft/perfview#788]
They are different licenses of Microsoft.Diagnostics.Tracing.TraceEvent in [source code](https://github.com/Microsoft/perfview/blob/T2.0.19/LICENSE) (MIT) and in [NuGet ](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent/2.0.19) ([MICROSOFT .NET LIBRARY](https://go.microsoft.com/fwlink/?LinkId=329770))?
Is it on purpose? If not then what is the proper license? 
We want to consume version 2.0.19 of the library.

**Comment by vancem** [comment]
This is a dup of #779 

As mentioned there, TraceEvent should work like the rest of the .NET Library.
