### ISSUE TITLE
Data Collection of Microsoft.Diagnostics.Tracing.TraceEvent 

### ISSUE THREAD

**Issue by rpajak-solarwinds** [Microsoft/perfview#789]
The [MICROSOFT .NET LIBRARY](https://go.microsoft.com/fwlink/?LinkId=329770) license states that the library can send some data to Microsoft. . Please answer the following questions:

1. What data is Microsoft collecting from our use of the library? 
2. What is Microsoft is doing with it? 
3. Can the data collection be operationally turned off? If yes, then how?

**Comment by vancem** [comment]
The TraceEvent library contains no Microsoft telemetry built into it.     It is not sending any data.  
The license is a generic one for all of .NET and permits this for the library, but we don't actually do it for TraceEvent (nor are we likely to do so).
