### ISSUE TITLE
Manifest of custom EventSource provider not dumped into the rundown information

### ISSUE THREAD

**Issue by chhornung** [Microsoft/perfview#796]
Steps to reproduce (happens with PerfView 2.0.26 and also current code at the time of this writing - d654385a):

- Create a C# application with an EventSource provider.
- Start a PerfView trace with the custom EventSource provider enabled and with a circular buffer.
- Start the C# application.
- Let the application and the trace run until the circular buffer has been filled and the start of the C# application is no longer contained in the buffer.
- Make the C# application generate some events.
- Stop the PerfView trace (I did it on the command line and I did specify the provider again to the stop command).
- Open the trace file in PerfView and observe that the events from the custom EventSource provider are not decoded, i.e. they are listed with the GUID of the provider and the numerical event IDs.

I am running .NET Framework 4.7.2 on Windows 7 x64, if that matters.

My investigation shows that it might have to do with the keywords of the manifest rundown event. When I look at such a manifest event, e.g. right after startup of the C# application, I see that the event comes with `Keywords="0x00FFFFFFFFFFFFFF"`. In the log file and PerfView source code, however, I find that the rundown routine only enables keywords `0x1000000000000000` (CommandProcessor.cs line 3257), which does not have set bits in common with the mask provided in the event. If I change that to `0xFFFFFFFFFFFFFFFF`, the manifest is dumped into the rundown information and the events are decoded as desired. But I do not know if that would be an appropriate fix and I will leave the details to the PerfView/ETW experts.

**Comment by vancem** [comment]
I have not looked at it carefully but I do note that the current keyword is in a reserved range, which may be what his causing the problem.    Changing it to something outside that range is certainly a good idea.

Can you see if it is fixed with the #803 pull request?

**Comment by chhornung** [comment]
Yes, I can confirm that https://github.com/Microsoft/perfview/pull/803 fixes it.
Thanks a lot!
