### ISSUE TITLE
Feature request: Performance counter trigger - make trigger interval configurable

### ISSUE THREAD

**Issue by matthew-churcher** [microsoft/perfview#799]
Having triggers from performance counters is really useful.  Sadly there is undocumented behavior which means triggers only activate if above the threshold for 3 consecutive seconds.

Sadly I'm often asked to investigate issues which are long over within 3 secs of any symptoms showing.

It would be really useful to override this parameter so that I can trigger after a single (or more) results over a threshold or test for triggers more (or less) frequently that 1000ms.

Thanks. Ping me if that needs clarifying further or would like to discuss.

**Comment by vancem** [comment]
There is a qualifier that does MinSecForTrigger which defaults to 3 that makes the trigger interval configurable and you can set it to 1 to get it to trigger more quickly.

You probably want the perf counter to be polled more frequently than 1 / sec.   (e.g. PerfCounterPollMSec = 1000).    It would be reasonable straightforward to make that configurable as well, (The plumbing for it should look a lot like MinSecForTrigger).    You would probably want to change MinSecForTrigger to be a float. along with it.

**Comment by matthew-churcher** [comment]
I totally missed that "/MinSecForTrigger", sorry I did try to review the docs and code. Thanks for the response. I'll leave the ticket open in case any one wants to tackle the polling interval.

**Comment by matthew-churcher** [comment]
Ah I know why I didn't use it.. It doesn't work!  MinSecForTrigger is documented as working for a stop trigger. When used with the start trigger it doesn't appear to have an effect. I also note some forums with similar complaints.

> PerfView logging started at 29/11/2018 08:59:17
[EXECUTING: PerfView collect /merge:false /zip:false /LogFile:perfview.log /DataFile:PerfViewData.etl /AcceptEULA /LowPriority /CircularMB:2048 /BufferSizeMB:2048 /ThreadTime /NoV2Rundown /NoNGenRundown /NoView /CPUSampleMSec:499 /StartOnPerfCounter:ASP.NET v4.0.30319:Requests Current: > 25 /MinSecForTrigger:1 /MaxCollectSec:10]
[StartOnPerfCounter active waiting for trigger: ASP.NET v4.0.30319:Requests Current: > 25]
[ASP.NET v4.0.30319:Requests Current:=14.0: Waiting for trigger of 25, CurVal 14.0]
Waiting for start trigger 10 sec.
ASP.NET v4.0.30319:Requests Current:=7.0
Waiting for start trigger 20 sec.
ASP.NET v4.0.30319:Requests Current:=18.0
Waiting for start trigger 30 sec.
ASP.NET v4.0.30319:Requests Current:=13.0
[Counter is at 28.0 which is above the trigger for 0 sec.  Need 3 sec to trigger.]
Waiting for start trigger 40 sec.
ASP.NET v4.0.30319:Requests Current:=13.0
Waiting for start trigger 50 sec.
ASP.NET v4.0.30319:Requests Current:=9.0

**Comment by vancem** [comment]
I will take a look at this...

**Comment by dennisjlee** [comment]
I'd like to contribute a fix for this, though I can't assign the issue to myself. Hopefully I'll be able to send a pull request soon.

**Comment by brianrob** [comment]
Thanks @dennisjlee.  I'll assign this issue to you.

**Comment by dennisjlee** [comment]
@brianrob or anyone else, friendly ping on this - could anyone help me review my PR please?

**Comment by dennisjlee** [comment]
@brianrob thank you! How does the release schedule work for PerfView?

**Comment by brianrob** [comment]
PerfView releases are on-demand.  I try to do at least one per month just to make sure changes don't sit for too long.  The last one was on 3/8.  Is this something that you're in need of?  I can trigger one soon if needed, or otherwise, will get to it in the next few weeks.

**Comment by dennisjlee** [comment]
This feature would be a nice-to-have for some of my team's production
monitoring needs, be so if it's not too much trouble we would appreciate a
release sooner rather than later. Thanks so much Brian!

**Comment by brianrob** [comment]
This has been released and is available here: https://github.com/microsoft/perfview/releases/tag/P2.0.55.  Thanks!
