### ISSUE TITLE
Does TraceEvent library can resolve system call?

### ISSUE THREAD

**Issue by rainkin1993** [Microsoft/perfview#802]
System call field in original ETW events are memory addresses, does TraceEvent library provide an API to resolve the memory address to system call name?

**Comment by vancem** [comment]
I assume you are talking about the events generated /kernelEvent=SystemCall? .

Note that by default the SysCallExit comes with a stack trace, which typically is more useful to you than the entry address (which is in the SysCallEnter's address) (and it also gives you the return status which is likely to be useful).   

To answer your question, yes The TraceEvent library can decode the address into a symbolic name, however symbolic lookup is never trivial.   This is what the TraceLog class does (provides events AND stacks  (and symbol decode).   

The GetCodeAddressIndexAtEvent method is the thing that given an events (like the SystemCallEnter event), can find the CodeAddressIndex (which is a id that represents the symbolic name of a virtual address).   

If you look at the code base for IntructionPointerCodeAddressIndex, you will find places where this kind of thing was done for the  SampleProfile event's InstructionPointer address.   

However I suspect you will find that the symbolic name for this entry point may not be useful to you.
