### ISSUE TITLE
TraceEvent:  How do I translate FileKey to a File Name for FileIo events?

### ISSUE THREAD

**Issue by fryeware** [Microsoft/perfview#804]
I'm attempting to use TraceEvent (v2.0.30) to monitor file system activity in a real-time session.  I'm using the FileIo provider within NT Kernel Logger.   Many of the events i receive (roughly half) don't have a FileName property populated.  I vaguely remember a few years ago having a similar situation and at that time I was calling FileIDToFileName off of KernelTraceEventParser which took in a FileKey and returned the file name.  I see that method is still there, but it appears to never return anything.  Is this expected?  What's the right way to translate FileKey?

**Comment by vancem** [comment]
There is a kernel event called FileIOName that holds both the file Key and the file name.  TraceEvent has support for seeing these events and using them to look up names for other File Events.   (see FileIONameTraceData).

You do have to turn these on (The DiskFileIO flag to the kernel provider does this).  

If you are using Microsoft-Windows-Kernel-File, I assume the keyword KERNEL_FILE_KEYWORD_FILENAME == 0x10 (do a logman query providers Microsoft-Windows-Kernel-File) will do something similar, but the identity of the event will be different so the existing TraceEvent logic needs to be tweeked to recognize this new event.
