### ISSUE TITLE
Getting new file name from FileIORename ETW event

### ISSUE THREAD

**Issue by rpajak-solarwinds** [Microsoft/perfview#826]
Is it possible to monitor file rename so that I know what was the previous and new file path?

I thought that it would simple require hooking to the `FileIORename` event, but the payload (`FileIOInfoTraceData`) contains only the previous file path in the `FileName` property.

    kernelSession.Source.Kernel.FileIORename += FileIORename
    ...
    
    private void OnFileIORename(FileIOInfoTraceData data)
    {
        var prevFilePath = data.FileName;
        var newFilePath = ?
        ...
    }

**Comment by vancem** [comment]
The kernel events are what the are.   If after looking at any events around the rename to see if the new path is in any of them (it may not be), then I don't think it can be done. 

You can try turning on the Microsoft-Windows-Kernel-File to see what that produces (maybe they are better).    A 'logman query providers Microsoft-Windows-Kernel-File' shows the keywords you can use
```
0x0000000000000010  KERNEL_FILE_KEYWORD_FILENAME
0x0000000000000020  KERNEL_FILE_KEYWORD_FILEIO
0x0000000000000040  KERNEL_FILE_KEYWORD_OP_END
0x0000000000000080  KERNEL_FILE_KEYWORD_CREATE
0x0000000000000100  KERNEL_FILE_KEYWORD_READ
0x0000000000000200  KERNEL_FILE_KEYWORD_WRITE
0x0000000000000400  KERNEL_FILE_KEYWORD_DELETE_PATH
0x0000000000000800  KERNEL_FILE_KEYWORD_RENAME_SETLINK_PATH
0x0000000000001000  KERNEL_FILE_KEYWORD_CREATE_NEW_FILE
0x8000000000000000  Microsoft-Windows-Kernel-File/Analytic
```
I would turn these on and see what data it produces...
