### ISSUE TITLE
Typo in inlining code

### ISSUE THREAD

**Issue by davmason** [Microsoft/perfview#845]
I was looking at the source to see how perfview constructs a name out of the TraceData classes, and I think this is a typo:
https://github.com/Microsoft/perfview/blob/d9cde4ef13b80b72e05ea3a4d64790a13806a33c/src/TraceEvent/Computers/TraceManagedProcess.cs#L1398-L1407

Shouldn't it be data.**InlineeNamespace** on line 1405?

**Comment by vancem** [comment]
Yes, that is a typo.  I have it fixed locally and will resolve when I check this in.
Thanks for alerting us.

**Comment by vancem** [comment]
Fixed by #854
