### ISSUE TITLE
CS0436 warnings from Zip library's copy of "Contract.cs"

### ISSUE THREAD

**Issue by pharring** [Microsoft/perfview#85]
Building the Zip library results in a bunch of warnings indicating that "Contract" is multiply defined (in both mscorlib and locally).
Why do we include a private, dummy copy of "Contract.cs" in this project?
Is there a desire to run on frameworks that don't have System.Diagnostics.Contract?
If not, it looks like it would be safe to delete that file.

**Comment by vancem** [comment]
I have bitten the bullet and upgraded the solutions to V4.5 and gotten rid of the ZIP library.   

This fixes the original issue.
