### ISSUE TITLE
Do not close trace we are attaching to in EnsureStarted

### ISSUE THREAD

**Issue by RubenHesselbaek** [Microsoft/perfview#850]
[0001-Add-m_Attach-flag-to-prevent-InsureStarted-to-close-.patch.txt](https://github.com/Microsoft/perfview/files/2759461/0001-Add-m_Attach-flag-to-prevent-InsureStarted-to-close-.patch.txt)

If we try to attach to an allready running trace, the trace is restarted in ensureStarted, since StartTraceW returns ALLREADY_EXISTS

**Comment by RubenHesselbaek** [comment]
I might be using the library wrong, but on our server, we start a realtime trace where we enable the CLR provider.
Each application then monitors the trace for Events and filter based on the processId, to only log GarbageCollection events related to that specific application.
Unless I apply this patch, the trace is closed whenever an application attaches.

**Comment by vancem** [comment]
There is a TraceEventSessionOptions.NoRestartOnCreate that is specifically there to supress the restart.    Note you may also be interested in TraceEventSession.Attach.

Please reopen if this does not address your concern.
