### ISSUE TITLE
Analysing .net core Server GC ETW causes debug assertion.

### ISSUE THREAD

**Issue by peteri** [Microsoft/perfview#853]
Profiling .net core 2.1 applications when the GC mode is server (on an 8 core machine) the GCPerHeapHistory parse throws a debug.assert exception on line 4740 in CLrTraceEventParser in the HeapIndex property. This is because the Count is 4 and the HeapIndex in Server GC mode has values from 0..NoOfCores (0..7 in my case). This also means the spot check (ret<6) further down in HeapIndex.cs will presumably fail when the version number is higher than 3.

Note I'm unclear if the Count should be checked against the HeapIndex for version three traces.

See attached xperf trace converted to .csv file (I've filtered it to just the GCPerHeapHistory events) for example. ThreadId 47592 is running in Desktop mode and ThreadId 31216 is running in Server mode.

[BadTrace.zip](https://github.com/Microsoft/perfview/files/2763787/BadTrace.zip)

**Comment by vancem** [comment]
Adding Maoni and Jeff who know more about the details of GCPerHeapHistory and what we can expect from it 

@Maoni0  @jeffschwMSFT

**Comment by peteri** [comment]
Thanks, no particular rush as I'm using the GCHeapStats instead, but the asserts could do with fixing.

**Comment by Maoni0** [comment]
Count is just the # of generations we track GenData of so it's 4. it should not be compared against HeapIndex... I don't think this assert is valid.

**Comment by vancem** [comment]
Fixed by #868
