### ISSUE TITLE
`SysConfig/VolumeMapping` events are not delivered

### ISSUE THREAD

**Issue by nonmanager** [Microsoft/perfview#855]
When using `TraceEvent`, the `FileName` property of file-related events is sometimes delivered with an incorrectly formatted kernel path. For example, it contains `C:\Device\HarddiskVolume25\foo.bar` instead of `D:\foo.bar`. It happens only if the drive in question is mounted after the ETW session is started (say, a USB key is inserted).

It turns out that [this heuristic](https://github.com/Microsoft/perfview/blob/688a8564062d51321bbab53cd71d9e174a77d2ce/src/TraceEvent/Parsers/KernelTraceEventParser.cs#L3501) kicks in and adds the system drive prefix (`C:`) because the appropriate kernel-to-user drive mapping cannot be found (`\Device\HarddiskVolume25` to `D:` in the example above). In turn, the mapping is missing because the [event callback](https://github.com/Microsoft/perfview/blob/688a8564062d51321bbab53cd71d9e174a77d2ce/src/TraceEvent/Parsers/KernelTraceEventParser.cs#L374) for `SysConfig/VolumeMapping`, which should insert it, is never called. And indeed, no matter how I configure the tracing session, `VolumeMapping` (and other `SysConfig` events) are nowhere to be found, even if I manually look for them by instrumenting the `RawDispatch` callback. I tried both on Win10 and Win7.

When I collect kernel events with PerfView, `SysConfig` events do appear (without a timestamp, though):
![image](https://user-images.githubusercontent.com/28230891/51328456-b57dea00-1a73-11e9-9476-437ee434b764.png)

I can also read them from the generated file using `TraceEvent`. However, the events seem to originate during ETL merging, not during trace collection. I can't find them in the "raw" ETL files right after collection, only in the final, merged ETL. Another hint that merging does something is the following: If a drive is disconnected while the trace is being collected, and I plug it in only during merging, the `VolumeMapping` event for that drive appears. In the opposite case (connected at collection time, disconnected at merge time), the event is missing.

Are `SysConfig` events special in any way? How can I get them to appear with `TraceEvent` in real-time sessions?

**Comment by vancem** [comment]
To my knowledge, the VolumeMapping events are added to the trace as part of the 'merge' operation (notice that they have a timestamp of 0, which almost certainly not a 'normal' timestamp.

In theory if you are collecting from an unmerged file, it should try to create the mapping on the fly (see KernelTraceEventParser.cs PopulateFromLocalMachine()).   

Note that fundamentally there is a problem if drives come and go (which seems to be your scenario), because the drive state at the time the events are logged is not the same as the time that the drive mapping is created.   

This issue (and the fact that it is heuristic), is known, but it is unclear if the TraceEvent library can do anything about it.   

I am closing the issue, but if you believe there is something that can be done in the TraceEvent library feel free to open it again with the suggestion.

**Comment by nonmanager** [comment]
Thanks for replying!

In our scenario there are no files involved, we process kernel events on the fly. If `VolumeMapping` events are only added as part of `merge`, then indeed, there is no mechanism in place that would amend the mapping initially created by `PopulateFromLocalMachine()` when a drive comes or goes.

A solution could be to repopulate the mapping as needed, in order to make it more accurate for real-time sessions. More concretely, if no suitable mapping is found by [this](https://github.com/Microsoft/perfview/blob/688a8564062d51321bbab53cd71d9e174a77d2ce/src/TraceEvent/Parsers/KernelTraceEventParser.cs#L3496) point, `PopulateFromLocalMachine()` could be called again in order to refresh the mappings and retry before falling back on the heuristic. This would make the kernel-to-user path conversion successful with removable drives. What do you think?

Otherwise, is there anything wrong with just forwarding the kernel path without applying any heuristics to it? It is easier to deal with a pure kernel path (such as `\Device\Harddisk9\foo\bar.txt`) than its counterpart prepended with a drive letter, which looks like a valid user path, but it isn't (`C:\Device\Harddisk9\foo\bar.txt`).

**Comment by vancem** [comment]
In a world where drives come and go, there is no way to be 'right' without help from outside (basically something has to tell you when the mappings change).   Thus I am not thrilled with the idea of heuristically calling PopulateFromLocalMachine() at various points.  

I would not be averse, however to adding a 'hook' to get 'help' from the outside.   Thus if a KernelTraceEventParser had a delegate  'string MapKernelFilePathToUserFilePath(string)' that you could set to take over this mapping.   By default it would just do what it does today, but if that is not good (as in your case, you can set this (you can simply set it to the identity function if you wish to simply have the kernel path), and gives you control.    Should be pretty simple to implement if you want to do create a PR to do that.

**Comment by nonmanager** [comment]
Closed. The "hook" for path mapping is here: https://github.com/Microsoft/perfview/commit/a7f8dffcd7a09ec3483f98b4c19e617b353c3750
