### ISSUE TITLE
Default dump file name - add timestamp

### ISSUE THREAD

**Issue by ilabutin** [Microsoft/perfview#876]
By default PerfView uses `PerfViewData.etl` file name and will overwrite existing one without any confirmations.
I try not to forget to rename it in the Collect dialog to something meaningful, but that does not always happen.
Suggestion is to append timestamp to the file name so it by default would be: `PerfViewData_YYYYMMDD_HHMMSS.etl`.

It will also bring little visual help in the list of files - it will be obvious when dumps were collected (if user does not rename/remove the timestamp part).

**Comment by vancem** [comment]
I considered this option really early on in the development of PerfView, but ultimately decided against it.    Yes, you avoid overwriting data, which is good, but frankly you end up creating ALOT of files, and these files are BIG.   It also complicates scripting cases where the start and the stop are done by separate processes (the stop has to search for the 'oldest' and even that is technically not correct).    This pushed me to 'keep it simple' and simply have a default name.   Yes you may lose data, but data is rarely that precious (you can recollect it easily).  

So I would like to keep the current DEFAULT (especially now that there are many users who expect the current behavior).  

I would not be averse to having some way asking for this (we can remember this preference on a per-user basis).    I just never care enough to pursue it.    If you are interested, make me a pitch about how you want it to work, and I will likely approve it.
