### ISSUE TITLE
Chocolatey only comes up with version 1.9.0

### ISSUE THREAD

**Issue by mlsomers** [Microsoft/perfview#878]
There have been 37 since... 
It would be great if new releases would show up in Chocolatey.
See https://chocolatey.org/docs/create-packages for details on creating a package.

**Comment by ilabutin** [comment]
PerfView 2.0.26 is now on Chocolatey: https://chocolatey.org/packages/perfview
I'll be maintaining it there and update as soon as new versions are released.

**Comment by mlsomers** [comment]
Super, just installed it :-) Thanks!

**Comment by jzabroski** [comment]
@ilabutin  Just a thought, but I think this project and others would benefit from a dotnet tools extension for chocolatey similar to `dotnet push` but maybe `dotnet pushchocolatey`

**Comment by ilabutin** [comment]
@jzabroski Could be, but since releases here are not made often I'll maintain them manually for a start. If we see increased frequency of releases, then I'll consider more automated way.
