### ISSUE TITLE
Suggest add System.Memory as a dependent package for TraceEvent NuGet

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/perfview#886]
**Issue:**

In the latest TraceEvent library (2.0.36), there is an hidden dependency for .NET Fx of System.Memory.

**Repro steps:**

* Create a .NET Fx (4.6.1 in this case) project and reference TraceEvent.
* Run the following code:

```csharp
  string etlx = TraceLog.CreateFromEventPipeDataFile(@"A-NetPerf-File.netperf");
  Console.WriteLine($"eltx: {etlx}");
```

**Expected:**
The netperf file being converted to etlx correctly.

**Actual:**
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

**Work around**
Add package reference to `System.Memory` in the user's project.

```xml
    <PackageReference Include="System.Memory">
      <Version>4.5.2</Version>
    </PackageReference>
```

But the exception won't be found until runtime.

**Proposal for the fix**
In the nuspec for TraceEvent, claim System.Memory as its dependency.

**Comment by pharring** [comment]
Wasn't this already addressed with #870 by removing the use of `Span<T>`?

**Comment by vancem** [comment]
Yes, #870 should remove the dependency.   Note that we have not published a new package (although we have built them).   You can try out \\vancem1\public\Microsoft.Diagnostics.Tracing.TraceEvent.2.0.38.nupkg.  If it looks OK, I will push it to nuget.    @mpeyrotc are you happy with the lastest TraceEvent package?

**Comment by xiaomi7732** [comment]
@vancem / @pharring yes, I didn't notice the dependency is removed by #870. Just built the tip of the code and verified the change and it worked without the dependency of System.Memory.

I'll close this issue and abandon the PR. Thanks for pointing it out.
