### ISSUE TITLE
Question: Is there any plan to make PerfView usable on Linux?

### ISSUE THREAD

**Issue by NatElkins** [Microsoft/perfview#893]
Is there any plan in the near or far future to make PerfView usable on Linux?  Looks like the main blocker is Windows-specific code in EtcClrProfiler projects.  Do you have any sense of how large of an effort it would be?

**Comment by vancem** [comment]
See https://github.com/Microsoft/perfview/issues/903, which is about MacOS, but all the solutions are actually cross platform so your question is basically the same.  

As you will see from that issue, things are a bit different (you will use a dotnet command to actually collect the traces), but there is alot of work that has already been done (the PerfViewJS code checked into this repo).  

I am going to close this so we have only one thread of conversation on that issue.
