### ISSUE TITLE
Unable to start collection on Windows 10

### ISSUE THREAD

**Issue by jsheetzati** [microsoft/perfview#944]
I am unable to start PerfView.exe and start collection on Windows 10 64 Bit. I have tried running the program in different directories but get this error every time. Unsure what else to try.

```
Started with command line: "C:\stuff\PerfView\PerfView.exe" /RestartingToElevelate:  /BufferSizeMB:256 /StackCompression /MinSecForTrigger:0 GuiCollect
PerfView Version: 2.0.42  BuildDate: Mon, 06 May 2019 15:51:42 GMT
PerfView Start Time 6/2/2019 9:29:38 PM
Started: GuiCollect
Warning: PdbScope not found at C:\stuff\PerfView\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at C:\stuff\PerfView\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Collection Dialog open.
Completed: GuiCollect   (Elapsed Time: 0.121 sec)
Started: Collecting data C:\stuff\PerfView\PerfViewData.etl
[Kernel Log: C:\stuff\PerfView\PerfViewData.kernel.etl]
Kernel keywords enabled: Default
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
Completed: Collecting data C:\stuff\PerfView\PerfViewData.etl   (Elapsed Time: 0.567 sec)
Exception Occurred: System.Runtime.InteropServices.COMException (0x800700B7): Cannot create a file when that file already exists. (Exception from HRESULT: 0x800700B7)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.MainWindow.<>c__DisplayClass13_0.<ExecuteCommand>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
An exceptional condition occurred, see log for details.
```

**Comment by brianrob** [comment]
I'm wondering if by chance you have an existing PerfView ETW session running.  Can you try running ```perfview abort``` and see if that fixes things?

**Comment by jsheetzati** [comment]
Great, thank you for that! I had rebooted a couple times and was still seeing that error. Abort command seemed to clean it up.

One other quick question that I could not find in the manual. In the "Processes" window, does PerfView report the bitness of the OS and not the process? I was trying to diagnose some broken stacks for my 32 bit process and noticed PerfView always reports bitness as 64 bit and does not line up with the "Platform" tab in Task Manager.

From the screenshot, PerfView reports Visual Studio as 64 bit. Everything in my "Processes" window is reporting as 64 bit.
![image](https://user-images.githubusercontent.com/15350893/58885683-4282b200-86a8-11e9-9edd-65964ac45c82.png)

**Comment by brianrob** [comment]
@jsheetzati, the processes table(s) should report bitness of the process, though it's not always correct.  Certainly not all of these processes are 64-bit.  I was able to reproduce this on my machine as well.  Can you file an issue for this please?

**Comment by jsheetzati** [comment]
https://github.com/microsoft/perfview/issues/946

**Comment by PawanKartikS** [comment]
In `PerfViewData.cs`, the bitness is decided as:
```c#
writer.Write("{0}{1}", process.Is64Bit ? 64 : 32, listSeparator);
```

Shouldn't you be calling `IsWow64Process()` along with the process `HANDLE` to check if a process is 64 bit or not?
