### ISSUE TITLE
Wondering what APIs to use to query PerfView with only code

### ISSUE THREAD

**Issue by Kavignon** [microsoft/perfview#949]
Hi, 

I understand PerfView is a wonderful tool created by the Microsoft team, and I'm grateful for its existence! I'd like to if there are any APIs I can use directly to query the tool as a service or would I need to dive deeply into the source code and find the public APIs on my own for my purposes?

**Comment by eric-b** [comment]
Did you found this page: https://github.com/microsoft/perfview/blob/master/documentation/TraceEvent/TraceEventProgrammersGuide.md#what-you-can-do-with-the-traceevent-library

It describes essentially the library Perfview is using.

**Comment by Kavignon** [comment]
Thanks, @eric-b, I missed that page!
