### ISSUE TITLE
Significant rounding errors occur in the Stack Window for "large" StackSources

### ISSUE THREAD

**Issue by daklimek** [Microsoft/perfview#95]
If you open this stack viewer, it shows a metric of 91million, but if you change all of the floats to doubles it shows 97million. \vspfs3\public\daklimek\devenvCopy.codeSizecallTree.perfView.xml

internal double m_inclusiveMetric;
        internal double m_inclusiveCount;
        internal double m_exclusiveMetric;
        internal double m_exclusiveCount;
        internal double m_exclusiveFoldedMetric;
        internal double m_exclusiveFoldedCount;

Ideally, we would do the summation using doubles instead of floats but keep them stored as floats to save memory.

**Comment by vancem** [comment]
There are a LOT of tree nodes, so we really don't want to increase their size.   The 'obvious' suggestion of using doubles does that.  I would rather avoid that.   

I am going to close the issue for now, as I think the cure is worse then the disease.   We can reopen, if more data suggests that the tradeoff has changed.
