### ISSUE TITLE
E: Unable to locate package linux-tools-4.4.0-17763-Microsoft

### ISSUE THREAD

**Issue by tdevere** [microsoft/perfview#974]
On Microsoft Windows [Version 10.0.17763.615]
I've added support for Windows Subsystem for Linux and setup Ubuntu 
18.04 (uname -r  4.4.0-17763-Microsoft ). During setup for perfview I run into the following failure:

Installing perf_event packages.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-tools-4.4.0-17763-Microsoft
E: Couldn't find any package by glob 'linux-tools-4.4.0-17763-Microsoft'
E: Couldn't find any package by regex 'linux-tools-4.4.0-17763-Microsoft'
E: Unable to locate package linux-cloud-tools-4.4.0-17763-Microsoft
E: Couldn't find any package by glob 'linux-cloud-tools-4.4.0-17763-Microsoft'
E: Couldn't find any package by regex 'linux-cloud-tools-4.4.0-17763-Microsoft'

There doesn't appear to be packages for my specific build.  Will this change in the future?

**Comment by brianrob** [comment]
Can you provide the exact steps that you're running?  This actually looks like PerfCollect (http://aks.ms/perfcollect).

**Comment by tdevere** [comment]
*sorry for the delay*

Hi, I'm following the steps outlined here: Preparing Your Machine 
https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md

****@****:~$ sudo ./perfcollect install
[sudo] password for *****:
Installing perf_event packages.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-tools-4.4.0-17763-Microsoft
E: Couldn't find any package by glob 'linux-tools-4.4.0-17763-Microsoft'
E: Couldn't find any package by regex 'linux-tools-4.4.0-17763-Microsoft'
E: Unable to locate package linux-cloud-tools-4.4.0-17763-Microsoft
E: Couldn't find any package by glob 'linux-cloud-tools-4.4.0-17763-Microsoft'
E: Couldn't find any package by regex 'linux-cloud-tools-4.4.0-17763-Microsoft'
LTTng can be installed using default Ubuntu packages via the Ubuntu package feeds or using the latest
stable package feed published by LTTng (PPA feed).  It is recommended that LTTng be installed using the PPA feed.

    If you select yes, then the LTTng PPA feed will be added to your apt configuration.
    If you select no, then LTTng will be installed from an existing feed (either default Ubuntu or PPA if previously added.

Would you like to add the LTTng PPA feed to your apt configuration? [Y/N]Y
Adding LTTng PPA feed and running apt-get update.
 LTTng (Linux Trace Toolkit Next Generation) project repository.
For more information: http://lttng.org

Most of the LTTng utilities are now packaged in Debian/Ubuntu, but this PPA offers the latest stable versions. Ubuntu 12.04 and up are supported.

Problems, questions, comments?
Please let us know: http://lttng.org/contact

You can also report bugs at: https://bugs.lttng.org/projects

==== SETTING UP LTTng 2.x ====

LTTng 2.x features a unified trace-control client "lttng" to control both kernel tracing (through lttng-modules) and userspace tracing (through UST). The client itself is shipped in the "lttng-tools" package.

To install the toolchain:
$ sudo apt-add-repository ppa:lttng/ppa
$ sudo apt-get update
$ sudo apt-get install lttng-tools lttng-modules-dkms babeltrace

You may also want to install:
liblttng-ust-dev: To compile applications instrumented with UST tracepoints
python3-babeltrace: Python bindings for babeltrace

Once the modules are installed correctly, you can start tracing right away. No need to reboot!

You can now refer to http://lttng.org/quickstart to use the kernel or userspace tracers.

==== Daily build packages ====

If you prefer living on the edge, you can use the latest development versions in the daily PPA: https://launchpad.net/~lttng/+archive/daily
 More info: https://launchpad.net/~lttng/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease [3226 B]
Get:4 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease [3226 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://ppa.launchpad.net/lttng/ppa/ubuntu bionic InRelease [20.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:8 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [94.8 kB]
Get:9 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages [94.8 kB]
Get:10 http://ppa.launchpad.net/lttng/ppa/ubuntu bionic/main amd64 Packages [3920 B]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [477 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [709 kB]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [162 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [4976 B]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [2476 B]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [589 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [195 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4004 B]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [259 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [11.9 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [4156 B]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [997 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [305 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [6636 B]
Get:25 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4000 B]
Get:26 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1856 B]
Fetched 4205 kB in 19s (225 kB/s)
Reading package lists... Done
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://ppa.launchpad.net/lttng/ppa/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Installing LTTng packages.
Reading package lists... Done
Building dependency tree
Reading state information... Done
lttng-modules-dkms is already the newest version (2.10.x+stable+git1153+201906241916~ubuntu18.04.1).
lttng-tools is already the newest version (2.10.x+stable+git4078+201905242102~ubuntu18.04.1).
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  liblttng-ust-ctl4
The following packages will be upgraded:
  liblttng-ust-ctl4 liblttng-ust0
2 upgraded, 0 newly installed, 0 to remove and 96 not upgraded.
Need to get 229 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/lttng/ppa/ubuntu bionic/main amd64 liblttng-ust0 amd64 2.10.x+stable+git2275+201908021901~ubuntu18.04.1 [150 kB]
Get:2 http://ppa.launchpad.net/lttng/ppa/ubuntu bionic/main amd64 liblttng-ust-ctl4 amd64 2.10.x+stable+git2275+201908021901~ubuntu18.04.1 [79.2 kB]
Fetched 229 kB in 11s (19.9 kB/s)
(Reading database ... 69232 files and directories currently installed.)
Preparing to unpack .../liblttng-ust0_2.10.x+stable+git2275+201908021901~ubuntu18.04.1_amd64.deb ...
Unpacking liblttng-ust0:amd64 (2.10.x+stable+git2275+201908021901~ubuntu18.04.1) over (2.10.x+stable+git2271+201907042017~ubuntu18.04.1) ...
Preparing to unpack .../liblttng-ust-ctl4_2.10.x+stable+git2275+201908021901~ubuntu18.04.1_amd64.deb ...
Unpacking liblttng-ust-ctl4:amd64 (2.10.x+stable+git2275+201908021901~ubuntu18.04.1) over (2.10.x+stable+git2271+201907042017~ubuntu18.04.1) ...
Setting up liblttng-ust-ctl4:amd64 (2.10.x+stable+git2275+201908021901~ubuntu18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up liblttng-ust0:amd64 (2.10.x+stable+git2275+201908021901~ubuntu18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

later if I try to run the sample collect i get the following error

****@****:~$ sudo ./perfcollect collect sampleTrace
Zip and unzip are not installed.
Run ./perfcollect install
or install zip and unzip manually.

**Comment by brianrob** [comment]
Worked with @tdevere offline on this.  The issue is that this is on WSL2 which doesn't have support for perf_events.  The solution is to run use a machine with a true Linux host unless/until WSL2 supports perf_events.
