### ISSUE TITLE
facing Stack Broken in trace, we cannot Neng image for managed application

### ISSUE THREAD

**Issue by zgf** [microsoft/perfview#978]
Hi Folks,

we are facing 90%+ Stack Broken but we cannot Neng image for the managed application.
I went through the troubleshooting page. 
I was just wondering how to resolve this problem without Neng all dll?

System: Win server 2016
Application: amd64 .Net managed application.
Perfview version: latest.

Example:
\\redmond\exchange\Performance\performancedata\15.20.2103.000\BasicDomain_Store_Perf\ReadMail\AllInOne\PerfmonCollector_DART_ExPerf\19-07-07_06.43.19_Daily Test Pass\PerfData.zip 

Command collecting perfview trace:
d:\tools\PerfView Collect d:\PerfViewData.etl   -LogFile=d:\CPUAndMemory.log /BufferSize:3072 /Circular:0 /MaxCollectSec:120 /KernelEvents=Process+Thread+Profile+ImageLoad /ClrEvents=GC+Loader+Stack  /Zip /AcceptEULA /NoView  /NoGui

I tried the "PerfView.exe EnableKernelStacks", but not work.
it does not always throw 90%+ Stack Broken if our application workload is very low, it can work fine or only13-60% stack broken.

**Comment by zgf** [comment]
I tried the "PerfView.exe EnableKernelStacks", but not work.
it is not always throw 90%+ Stack Broken, if our application workload is very low, it can works fine or only13-60% stack broken.

**Comment by billwert** [comment]
You need a bigger buffer - 3GB is very unlikely to be big enough for a 120 second trace. If a significantly larger buffer does not help, your next step is to collect fewer events (GC+Loader+Stack is a lot, potentially.
