### ISSUE TITLE
Perfview errros out with KernelTraceController.dll on WIndows 2019

### ISSUE THREAD

**Issue by NageshGundapuneni** [microsoft/perfview#994]
OS Build: Windows 2019 version 1809 ( OS Build 17763.678)
Seeing issues with Pefview on this build.
![PerfView-Error](https://user-images.githubusercontent.com/54646840/63893962-52a4e780-c9a0-11e9-9180-71fab3e47247.PNG)

**Comment by brianrob** [comment]
This was resolved offline and no longer repros.  Closing.
