### ISSUE TITLE
User/kernel space split in TraceEvent

### ISSUE THREAD

**Issue by swift-kim** [microsoft/perfview#996]
I encountered an error while analyzing trace data collected from my applications using _TraceEvent_ library. I used the _dotnet-trace_ tool from [diagnostics](https://github.com/dotnet/diagnostics) to trace 32 bit .NET Core processes on Linux ARM64 machine.

I looked into the source code of the library and it turned out that _TraceLog_ was counting all user space instruction pointers as kernel addresses as follows.

https://github.com/microsoft/perfview/blob/20fa6275c593c68bbd6e6a53c95fbf314304b48c/src/TraceEvent/TraceLog.cs#L2908-L2916

The method assumes that all addresses above 0x80000000 are kernel addresses (32 bit case). However, the user space size is not generally the same for all systems. For example, the default virtual address split is 2G/2G and 3G/1G on Windows and Linux respectively, and on my ARM64 machine, each 32 bit process has 4G user space.

Can anybody help with this? If this is old code base before the cross-platform .NET, should I fix the code?

**Comment by viewizard** [comment]
https://www.kernel.org/doc/Documentation/arm64/memory.txt ?

**Comment by brianrob** [comment]
@swift-kim, this is likely just old and from when .NET was Windows-only.  Can you tell me how this is showing up for you?

**Comment by swift-kim** [comment]
@brianrob I was trying to convert trace data into speedscope format using [_dotnet-trace_](https://github.com/dotnet/diagnostics/blob/2a8bc1af48f9379d56cc24eec4aa7b2d82eb4433/src/Tools/dotnet-trace/TraceFileFormatConverter.cs#L51), but I could see only a bunch of unresolved symbols (`?!?`) in the output file since the following method failed in the very beginning of reading an event log. The root cause is what I've described above. My trace data is piled up wtih instruction pointers which usually start with 0xEFxxxxxx and definitely `ProcessForAddress()` shouldn't return proc 0.
https://github.com/microsoft/perfview/blob/20fa6275c593c68bbd6e6a53c95fbf314304b48c/src/TraceEvent/TraceLog.cs#L8162-L8166

**Comment by swift-kim** [comment]
[Trace-sample.zip](https://github.com/microsoft/perfview/files/3572725/Trace-sample.zip)

I attached my sample trace data. The archive contains 4 application traces in 3 formats. I temporarily modified the value `0x80000000` to larger one to convert original nettraces into ETLX and speedscope format properly.

**Comment by swift-kim** [comment]
It's hard to find the virtual address boundary between the user-kernel space programmatically. Can it be possibly passed to the TraceEvent library at runtime as an environment variable by user? (so that it can work for any platforms)

**Comment by swift-kim** [comment]
This issue has not received any attention, and I don't need a fix as my platform now supports aarch64 ;)
